### ISSUE TITLE
4.17 - No results shown in quickJump / quickMove when typing in Thunderbird 60.9

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#11]
This is a regression caused by moving the search panel to a separate xul file (necessary for compatibility with Thunderbird 70, where search boxes are represented by an entirely different element).

below is a quick fix (note that I cannot upload xul files directly, therefore the add-on is in a xip archive and must be extracted first before installation):

[QuickFolders-wx-4.17.1pre4.zip](https://github.com/RealRaven2000/QuickFolders/files/3814526/QuickFolders-wx-4.17.1pre4.zip)

**Comment by michauk** [comment]
working, thx

**Comment by RealRaven2000** [comment]
nice one. Bug was caused by swapping out the `type="search"` attribute for `is="search-textbox"` (usage with the newer search-textbox control)

**Comment by RealRaven2000** [comment]
fixed in 4.17.1

**Comment by PissedFirefoxUser** [comment]
QuickFolders-wx-4.17.1pre4.xpi Worked perfectly. Thank you!

**Comment by michauk** [comment]
Nice support, I appreciate especially because I can't work without this plugin anymore (to jump / move mails mainly). And as a developer, too :)

**Comment by thaoleduc** [comment]
I have the same problem, I already download QuickFolders-wx-4.17.1pre4.zip. It works well
