### ISSUE TITLE
FEATURE REQUEST: quickJump list - option to list more than 25 search results, persistently

### ISSUE THREAD

**Issue by boldcompany** [RealRaven2000/QuickFolders#119]
Thank you for an extremely excellent, useful tool.

One small item would make it even more useful. Suppose a user has folders named such that they have secondary meanings (for example, "p2" in the folder name means priority 2). Such folders are scattered and nested throughout many directories in various email accounts. The user would like to search for all the "p2" folders and work with the items in those folders.

The QuickFolders quickJump feature _almost_ provides the needed functionality. When searching in quickJump, the results list can show folders matching "p2", for example.

However, the list is limited to 25 folders. Also, the list only remains visible as long as active searching occurs; once the user clicks somewhere else, the list disappears.

Please consider adding a "folder search" feature. It would function the same as the existing quickJump feature, except that (a) it would show all matching folders, not just 25; and (b) it would be persistent - similar to how mail search works. Instead of showing a persistent list of mail items, it would show a persistent list of folders.

One really cool implementation would be to make this a "smart tab" feature. When the user sets up a new smart tab, the user would specify a folder search instead of just dragging a specific folder. This would create a saved folder search. When such a smart tab is right-clicked, all currently matching folders would be listed and selectable. The beautiful thing is that this would map to your existing layout and tools, while adding the ability to obtain a persistent list of searched folders.

Thank you for your consideration!

**Comment by RealRaven2000** [comment]
I was just working on some advanced setting features for quickJump / quickMove [issue #118], adding a User Interface for setting these, so I decided to at least add a setting for the maximum number of results:
![image](https://user-images.githubusercontent.com/6314674/110776516-0d7d9900-8258-11eb-9fa7-5b61c4a977e7.png)

Saving the search as a search folder is obviously more difficult as my search algorithm is proprietary and cannot be easily baked into an Thunderbird advanced search. The other problem is that these searches always search for Emails, not for folders. But I agree that displaying it in either a QuickFolders tab (Let's call that "pinned search") or a Thunderbird Mail tab would be neat. Implementing this as a QuickFolders tab would probably a lot easier to implement as most of the ingredients are already coded. It could also be more dynamic as it would refresh the search results every time the tab is clicked. 

Would this be sufficient for what you want to do with it or does the list have to always been shown (and not just when you jump to or move mail to a folder)?

Test version for maximum number. (To change settings, go to QuickFolders Pro tab and click advanced search settings in the premium features box:
![image](https://user-images.githubusercontent.com/6314674/110777438-05722900-8259-11eb-9d98-611a3b1754c9.png)


[QuickFolders-wx-5.4pre83.zip](https://github.com/RealRaven2000/QuickFolders/files/6122454/QuickFolders-wx-5.4pre83.zip)
(To install, download then drag the zip file into Thunderbird Add-ons Manager)

**Comment by boldcompany** [comment]
@RealRaven2000, thank you so much for your quick and thorough response. 

Boosting the max results in the advanced search settings in 5.3pre83 indeed helps!

It is so exciting to hear your thoughts. The solutions you mention are exactly what would help. A "pinned search" QuickFolders tab would be a fundamental productivity boost; and if it's possible, the Thunderbird Mail tab would also be helpful. 

Many thanks for taking the time to address this request. The addition of this functionality would be extremely useful.

**Comment by RealRaven2000** [comment]
**TO DO**
I just thought of something - I am listing newsgroup accounts in the exclusion list. That is not necessary as you cannot move mail to newsgroups anyway, so these will have to be removed from the list! Patched version will be posted soon.

**Comment by RealRaven2000** [comment]
Patched version (which doesn't list newsgroups or any accounts you cannot file messages to) below. I also finally removed preferences.css from the options dialog, so the number inputs look a lot better. Might add a bit of spacing later.

[QuickFolders-wx-5.4pre95.zip](https://github.com/RealRaven2000/QuickFolders/files/6129843/QuickFolders-wx-5.4pre95.zip)

**Comment by boldcompany** [comment]
Thanks, trying 5.4pre95 now.

Just to confirm: This doesn't already include the new features (pinned search/mail tab), correct? Just an improvement to the existing functionality?

**Comment by RealRaven2000** [comment]
> Thanks, trying 5.4pre95 now.
> 
> Just to confirm: This doesn't already include the new features (pinned search/mail tab), correct? Just an improvement to the existing functionality?

No I am stilling mulling that one over... will hopefully come too, eventually.

**Comment by RealRaven2000** [comment]
Implemented in 5.4 published on ATN today

**Comment by boldcompany** [comment]
Noticed that this ticket was closed.

It looks like the main feature request wasn't included in the published 5.4 version. Would you be willing to leave this request open until the feature request is (or isn't) implemented?

**Comment by RealRaven2000** [comment]
> Noticed that this ticket was closed.
> 
> It looks like the main feature request wasn't included in the published 5.4 version. Would you be willing to leave this request open until the feature request is (or isn't) implemented?

I went by the title "option to list more than 25 results" - that's why I don't like feature requests that have many different functions in them - they will never be completed. Please open a new issue for whatever you consider is the "main feature" - you can reference this number #119 in it if you like.
