### ISSUE TITLE
Make QuickFolders compatible with Thunderbird beta 88

### ISSUE THREAD

**Issue by aprojanos71** [RealRaven2000/QuickFolders#126]

**Comment by RealRaven2000** [comment]
https://addons.thunderbird.net/en-US/thunderbird/pages/appversions/ doesn't list the beta as viable option (strict_max_version won't allow setting to 88.0b1) but I will post a version at issue #114. Closing this one as duplicate

**Comment by RealRaven2000** [comment]
I posted a test version here:

https://github.com/RealRaven2000/QuickFolders/issues/114#issuecomment-808898383
