### ISSUE TITLE
Unable to scroll through all the folders in a Quickfilter folder.

### ISSUE THREAD

**Issue by dpennekamp5353** [RealRaven2000/QuickFolders#127]
I can only scroll through about 1/3/ the folders.

**Comment by RealRaven2000** [comment]
How many folders and where? Are you referring to the dropdown menus and could you provide a screenshot? I think with Tb78 there is a hard limit of 100 folders... as a workaround, you can use the quickJump / quickMove button (or the shortcuts Shift+J / Shift+M if you have a QF Pro license), You can access any folder much quicker with this. and you can type in the parent name (or first letters) followed by a forward slash "/" if you want to restrict the number of results. If you hit the Enter button it will jump into the top folder in the suggestion list:

![image](https://user-images.githubusercontent.com/6314674/112880353-3c9e6200-90c2-11eb-9195-72f1a1a1d3dd.png)

**Comment by fredstluka** [comment]
+1 for QF Pro.  Shift-M (move), Shift-T (copy), and Shift-J (jump)
are awesome!  I've been using Thunderbird for over a decade and
Netscape Messenger for a decade before that, and I can't imagine
how I got by without QF Pro.

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by dpennekamp5353** [comment]
Thanks! Your response helped me resolve the issue. Using Quickfilters is 
the answer, easier and faster! Doug Pennekamp
