### ISSUE TITLE
Move sent message to folder

### ISSUE THREAD

**Issue by Chri7819** [RealRaven2000/QuickFolders#129]
Hi All

An additional great feature would be to select a folder while writing an email and after the email was sent (and
stored in "Sent" folder), be moved to selected folder.
This should also work with Exchange using EULA.
Would be really great.

Thanks
Chris

**Comment by RealRaven2000** [comment]
There is already an Add-on that does exactly that - I highly recommend installing it alongside QuickFolders - it's called "[Copy Sent to Current](https://addons.thunderbird.net/en-US/thunderbird/addon/copy-sent-to-current/?src=search)" and has a target folder picker. But the most suerpior way of using is to answer emails from their locations (e.g. if you are already in a folder for a group) and then your answer will be saved in the same folder alongside the conversation. Switch on "threaded view" and have a tidy inbox forever.

**Comment by Chri7819** [comment]
I searched hours to find such an Add-on, but failed. Happy to hear that this already exist, many thanks for that. I`ll try.
The second issue you mentioned, I know this setting, tried to activate it but I can`t. I think it`s because I`m using this Add-on for Exchange account [https://addons.thunderbird.net/de/thunderbird/addon/owl-for-exchange/](url).

Thanks.

**Comment by RealRaven2000** [comment]
> I searched hours to find such an Add-on, but failed. Happy to hear that this already exist, many thanks for that. I'll try.
> The second issue you mentioned, I know this setting, tried to activate it but I can't. I think it`s because I`m using this Add-on for Exchange account [https://addons.thunderbird.net/de/thunderbird/addon/owl-for-exchange/](url).
 
Just a note on github comments / replies - it looks like your quote characters are wrong (when you use the backslanted quote this opens a `code section`) - if you click on the edit option in github and then toggle to preview you can see the effects:

![image](https://user-images.githubusercontent.com/6314674/113301754-44931780-92f7-11eb-8a13-27f97615a18c.png)
![image](https://user-images.githubusercontent.com/6314674/113301843-5a084180-92f7-11eb-91c6-a883e158f0ea.png)

So if you write something like "let's" make sure you use the straight single quote (beside the Enter key on a US keyboard, under the @ sign on a UK keyboard)

As regards the setting, it's in the linked Copy Sent to Current Add-ons:
![image](https://user-images.githubusercontent.com/6314674/113302432-f2062b00-92f7-11eb-9c21-0b2d3cf050f0.png)

[x] Default is the current folder
and Default to "move original message" [x] 
are the most important settings. I think this should also work on an Exchange server - the Add-on will move the mail and delete from "Sent" (unless you want a copy there as well) locally first and then update on the server.
