### ISSUE TITLE
Feature Request: Escape key to "Cancel quickMove" completely

### ISSUE THREAD

**Issue by fredstluka** [RealRaven2000/QuickFolders#134]
I hit Shift-M and the quickMove text box appears.  Good!

But I did it accidentally.  (Meant to hit Cmd-M to minimize the Thunderbird window to the Dock.)  So I hit Escape.  The quickMove text box disappears.  Good!

But the red "1" still shows, and I think the message that I chose to not move is still queued up to be moved when I later specify a destination folder.  That's a problem.  I may accidentally move the message as part of a future move when I'm really just trying to move a totally unrelated message to a totally unrelated folder.

To clear things, I have to click the "folder and arrow" icon between the settings cog and the red "1".  This drops down a menu from which I choose "Cancel quickMove".  I think Escape should have done that automatically.

I realize that QF offers a feature of gradually accumulating a set of messages and then finally specifying a destination folder later.  And clearing that list via Escape may be undesirable in certain scenarios.  But when there's only one message in the list, it seems harmless for Escape to clear the list, as I assumed it would do.  Make sense?

Thanks!
--Fred

**Comment by RealRaven2000** [comment]
Yeah it does make sense; I am not even sure how many people would use the "accumulation" feature mainly because it is very easy to repeat the last move with the "auto-fill" feature.

**Comment by fredstluka** [comment]
Axel,

Yeah, I don't use the accumulation feature.  For that exact reason.
I just repeat the last move.  Or I use the standard Thunderbird
technique of selecting multiple messages -- a range of messages
via Shift-Click and/or specific messages via Cmd-Click.  And then
move them.

But, if you have users who DO use it, maybe it makes sense to
keep the current behavior of Escape.  However, in that case,
perhaps hitting Escape a 2nd time would do a "Cancel quickMove"?

I like the visual feedback.  One Escape closes the text box, but
(unfortunately?) doesn't do a Cancel.  But it DOES still show the
red "1" that indicates a message is queued up to move.  The 2nd
Escape would do the Cancel, which also deletes the red "1".  From
that visual feedback, users should figure out pretty quickly what
the 2nd Escape did.

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by RealRaven2000** [comment]
> Axel, Yeah, I don't use the accumulation feature.  For that exact reason. I just repeat the last move.  Or I use the standard Thunderbird technique of selecting multiple messages -- a range of messages via Shift-Click and/or specific messages via Cmd-Click.  And then move them. But, if you have users who DO use it, maybe it makes sense to keep the current behavior of Escape.  However, in that case, perhaps hitting Escape a 2nd time would do a "Cancel quickMove"? I like the visual feedback.  One Escape closes the text box, but (unfortunately?) doesn't do a Cancel.  But it DOES still show the red "1" that indicates a message is queued up to move.  The 2nd Escape would do the Cancel, which also deletes the red "1".  From that visual feedback, users should figure out pretty quickly what the 2nd Escape did.

Generally, a good suggestion. Problem: the edit box that handles the ESC event has just been removed. So it is hard to implement... I think the next best solution would be a simple option to say what ESC should do:

![image](https://user-images.githubusercontent.com/6314674/114431380-5908c700-9bb7-11eb-8aec-40d01dfdcf82.png)

This could be set to "false" by default so as to not surprise existing users and you could just tick the box and use ESCAPE once the way you want to.

**Comment by fredstluka** [comment]
Axel,

Perfect!

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by RealRaven2000** [comment]
Implemented in this version:

[QuickFolders-wx-5.5pre6.zip](https://github.com/RealRaven2000/QuickFolders/files/6309755/QuickFolders-wx-5.5pre6.zip)

Interestingly, Shift+Escape already clears the list - this was implemented through [[Bug 26660](http://quickfolders.org/bugzilla/bugs/show_bug.cgi@id=26665)]  in v. 4.15

**Comment by RealRaven2000** [comment]
Forgot the initialization of the checkbox in advanced settings when loading. Fixed here:

[QuickFolders-wx-5.5pre7.zip](https://github.com/RealRaven2000/QuickFolders/files/6309807/QuickFolders-wx-5.5pre7.zip)

**Comment by fredstluka** [comment]
Axel,

Perfect!  Escape now behaves exactly as I wanted.  And the
checkbox is preserved when I close and re-open the advanced
settings.

BTW, on my Mac, yes, Shift-Escape DID already clear the search
list.  I hadn't noticed that until you mentioned it.  But it did NOT
clear the search list if I'd already hit Escape to hide the text box.
Only if the text box was still showing.

Also, with this new version, Shift-Escape still does not clear the
search list if I first close the text box by clicking on the red '1",
or by clicking on the quickMove button to the left of it.  Again,
only if the text box is still showing.

That makes sense.  As you said the Escape event handler is tied
to the text box.  That's fine with me.

Feel free to close this ticket.

Thanks!
--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by RealRaven2000** [comment]
Implemented in 4.55 / 4.21.2 published today
