### ISSUE TITLE
Gray area shown below email list in wide view

### ISSUE THREAD

**Issue by d3xd3x** [RealRaven2000/QuickFolders#14]
This problem appears when Thunderbird is started in layout > wide view with current folder toolbar disabled.

It's also described on  Bugzilla in [[bug 26735]](https://www.mozdev.org/bugs/show_bug.cgi?id=26735)

**Comment by RealRaven2000** [comment]
So it appears the overlay loader makes an unwanted copy of messapaneboxwrapper causing the gray area to appear. Here is a quickfix:

[QuickFolders-wx-4.17.2pre5.zip](https://github.com/RealRaven2000/QuickFolders/files/3879800/QuickFolders-wx-4.17.2pre5.zip)

known issues: the styling of the current folder toolbar  from options window (changing the styles to something else than the silver bar) is borked by this. Most likely gotta adjust some CSS rules.

**Comment by PanosMich** [comment]
QuickFolders-wx-4.17.2pre6 worked great for me.

**Comment by RealRaven2000** [comment]
Fixed in Version 4.17.3 - released on 26/11/2019

**Comment by d3xd3x** [comment]
Thanks a mill for all the time spent and a great chat ;-) I'm a bit new to this community, is there a "like button" or a star rating or anything I can click to say Thank you?  @RealRaven2000 ?

**Comment by RealRaven2000** [comment]
> Thanks a mill for all the time spent and a great chat ;-) I'm a bit new to this community, is there a "like button" or a star rating or anything I can click to say Thank you? @RealRaven2000 ?

Not here on github - but you can leave a review on ATN: 
https://addons.thunderbird.net/thunderbird/addon/quickfolders-tabbed-folders/
just click the blue "Write a Review" button to leave a rating!
