### ISSUE TITLE
quickMove: parent folder containing an underscore not suggested as parent

### ISSUE THREAD

**Issue by cjhabs** [RealRaven2000/QuickFolders#148]
Using the "move" functionality, a folder containing an underscore is not recognized. It does not show up in the folder list and if I key the folder name it says that the parent does not exist.
thunderbird 68.10.0 64 bit
ubuntu 18.04

**Comment by RealRaven2000** [comment]
This may be a side effect of the latest changes in the search algorithm which allows treating _ as a word boundary in folders and parent location, so that you can find the folder "Marks_Shoe" by typing "Sh". And also a folder like 001_Marketing by typing "mark"

**Comment by RealRaven2000** [comment]
Tried it by renaming a folder in Thunderbird 68, it comes up as a suggestion:

![image](https://user-images.githubusercontent.com/6314674/116250711-df9bd780-a765-11eb-9ad2-7d75191570ea.png)

What's your folder name?

**Comment by RealRaven2000** [comment]
Second test, starting a folder name with underscore, works for me too:

![image](https://user-images.githubusercontent.com/6314674/116250821-00fcc380-a766-11eb-8150-8fb08095d92f.png)

**Comment by RealRaven2000** [comment]
Third test, looking for subfolder withint "Turbo_Duck":

![image](https://user-images.githubusercontent.com/6314674/116251035-31446200-a766-11eb-8b94-a7750040892e.png)

Test 4 - I think I found it:

![image](https://user-images.githubusercontent.com/6314674/116251130-45885f00-a766-11eb-90c2-a510cabd9f08.png)

So I can reproduce the issue, that's a good 1st step.

**Comment by RealRaven2000** [comment]
QuickFix for version Thunderbird 68 (this also affects the Tb78 version, so a quick test from your side would be appreciated):

[QuickFolders-wx-4.21.4pre1.zip](https://github.com/RealRaven2000/QuickFolders/files/6385051/QuickFolders-wx-4.21.4pre1.zip)

To install, download the zip file and drag into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment]
You will probably get the same test result with a folder name containing a space as this is the way the parent folder name was split:

```
function isParentMatch(folder, search, maxLevel, parentList) {
  ...  
  let folderNameMatches = f.prettyName.toLowerCase().split(/[_ ]/);
  // [issue 148] splitting prevents full name to be matched!
  if (folderNameMatches.length>1) {
    folderNameMatches.push(f.prettyName.toLowerCase()); // add the full string
  }
  // ignore 1-character matches
  if (folderNameMatches.some(a => a.startsWith(ancestors[maxLevel]) && a.length>1)) {  
    ... 
}
```

**Comment by jaysmithgit** [comment]
For what it is worth, we use the underscore character as a word separator in paths and folders.

.../.../.../clients/a-d/albertson_mary_jane

Using QF 5.5.2 searching is working fine in this regard.

**Comment by RealRaven2000** [comment]
I suggest re-testing this (It should still work) after implementation of issue #155
