### ISSUE TITLE
New line characters "\n" displayed in version 5.5.2

### ISSUE THREAD

**Issue by macdeport** [RealRaven2000/QuickFolders#150]
![qf-5 5 2-load-setting-210430](https://user-images.githubusercontent.com/26068595/116697998-2b4bbc80-a9c4-11eb-8304-7dae58d3bf79.jpg)

**Comment by RealRaven2000** [comment]
Good catch. This is a regression from converting all (localized) strings into the new json format. [mx l10n] Fixed version below:

[QuickFolders-wx-5.6pre2.zip](https://github.com/RealRaven2000/QuickFolders/files/6405663/QuickFolders-wx-5.6pre2.zip)

**Comment by macdeport** [comment]
Fixed 👍
