### ISSUE TITLE
consolidating tool bars, and show on top instead of bottom

### ISSUE THREAD

**Issue by Molckons** [RealRaven2000/QuickFolders#16]
Hi,

Need a way to be able to move the tool bar to top (at least)

currently it's equipping 2 tool bars

one for main, which has the groups, and another at bottom (which has the ability to be selected and move the message to one of folders at main tool bar)

same if I open an email (as a window), the tool bar shows at the bottom

anyway, to be able to put in same tool bar?

if not, at least to be on top

regards,
![snap 1 - Main window - 2 tool bars](https://user-images.githubusercontent.com/33968715/69466450-20373a80-0d95-11ea-9af8-8a055dc6e46a.JPG)
![snap 2 - Message window - 2 tool bars](https://user-images.githubusercontent.com/33968715/69466451-20373a80-0d95-11ea-875e-ae4a6a6210bb.JPG)

**Comment by RealRaven2000** [comment]
Do you mean like this?

![image](https://user-images.githubusercontent.com/6314674/69467447-e90a5e80-0d7f-11ea-910b-5796fad63f32.png)

I am getting this view when I start up in classic view and then switch to column view. The QuickFolders toolbar shows the favorite tabs (I have around 100, but I filter them with categories so they do not show up at the same time; usually I make do with 2 rows of tabs)

The toolbar on the top right is called "Current Folder Bar" although I would like to rebrand it as "Navigation bar". In classic view, it's in the ideal position (center screen) as it minimizes mouse mileage. in column view, it should ideally be in a vertical arrangement between the thread view and the preview.

Try to start with classic view and then switch to Vertical View. If that helps, please try out this preview version: (4.17.3 prerelease 13)

[QuickFolders-wx-4.17.3pre13.zip](https://github.com/RealRaven2000/QuickFolders/files/3881836/QuickFolders-wx-4.17.3pre13.zip)

**Comment by Molckons** [comment]
Hi,

Switching the view to classic, then restart
resolves the problem, and then i could change the view back to vertical
but after restarting the app, the issue returns back

however, trying 
QuickFolders-wx-4.17.3pre13.zip
it got resolved permanently

thanks for your quick support

**Comment by RealRaven2000** [comment]
Fixed in Version 4.17.3 - released on 26/11/2019
