### ISSUE TITLE
'What's new' text appears upon F5

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#175]
I saw the 'what's new' text on my QuickFolder toolbar. I clicked that text, read the resulting window and then dismissed that window. Later, I pressed F5 whilst viewing a 'Junk' folder. So doing caused the 'what's new text' to reappear. Once I repeated the steps to get rid of that text, I pressed F5 when in my inbox - and the same thing happened again. But then the problem stopped being reproducible.

QuickFolders 5.6.5
Thunderbird 78.11.0 x64
Windows 10

**Comment by RealRaven2000** [comment]
I believe this is actually due to Event Listeners not being cleared and will be fixed in the next version. I will upload some test versions here later.

**Comment by RealRaven2000** [comment]
Can you try this attached version?
[QuickFolders-mx-5.6.6pre20.zip](https://github.com/RealRaven2000/QuickFolders/files/6778484/QuickFolders-mx-5.6.6pre20.zip)
please download and drag into your Thunderbird Add-ons Manager to install.

Once you have installed and clicked "what;s new" don't do anything for a few seconds to see if the message comes up without any interaction. If it does, install it over the version (your current version doesn't have the patch that removes the event listener so it might still play into this on the first update)

**Comment by LinuxOnTheDesktop** [comment]
Thanks. I did not really understand your instructions. However, after installing the test version attached to this issue, and then clicking 'what's new', and restarting Thunderbird, the following happened. An 'initialising message' appeared, rather than the 'drag here' text (cf. #176); and F5 does not erroneously cause the 'what's new' text to appear. The latter problem was intermittent but so far as I can tell it - and the problem of #176 - are solved. Well done!

**Comment by RealRaven2000** [comment]
> Thanks. I did not really understand your instructions. However, after installing the test version attached to this issue, and then clicking 'what's new', and restarting Thunderbird, the following happened. An 'initializing message' appeared, rather than the 'drag here' text (cf. #176); and F5 does not erroneously cause the 'what's new' text to appear. The latter problem was intermittent but so far as I can tell it - and the problem of #176 - are solved. Well done!

What I meant is that pressing F5 didn't cause anything, I think it was some timer that ran and it just randomly kicked in when you pressed F5. There are no event listeners that pay attention to reloading that's why I said to just wait whether the button came back after a few seconds. The label "Initialising QuickFolders…" is currently hard coded and not translated, but I think it's ok as it is only temporary anyway.

By the way I will close the issue myself once I release this version so it remains available for other users in this phase.

**Comment by RealRaven2000** [comment]
I think this one is fixed for now (as of 5.7) - feel free to reopen if it happens again
