### ISSUE TITLE
 Hide instructions on how to set up QuickFolders at startup (if tabs are already defined)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#176]
Upon starting Thunderbird, and before the icons for my QuickFolders get drawn, I see text about setting up those folders. That is: upon start-up, and when one has some QuickFolders set-up, the addOn acts, briefly, as if one did _not_ have those folders set-up. It's visually jarring, especially since one naturally starts to read the text at issue, only to find that, a moment later, that text disappears.

QuickFolders 5.6.5
Thunderbird 78.11.0 x64
Windows 10

**Comment by RealRaven2000** [comment]
As a start, there is a setting extensions.quickfolders.initDelay which is defaulting to 2.5 seconds (2500 ms), can you try shortening that? It was necessary with the legacy version but might not be important anymore.

**Comment by RealRaven2000** [comment]
I have added a different placeholder text. Also shortened the delay - which btw you can change on the QF preferences "advanced" tab:
![image](https://user-images.githubusercontent.com/6314674/124751525-a1b5ef00-df1e-11eb-9eae-4dd69fcb2efa.png)



[QuickFolders-mx-5.6.6pre17.zip](https://github.com/RealRaven2000/QuickFolders/files/6776725/QuickFolders-mx-5.6.6pre17.zip)

To install test version, download the zip file, then drag it into Tb Add-ons Manager.

**Comment by LinuxOnTheDesktop** [comment]
Fixed in the latest test version.

**Comment by RealRaven2000** [comment]
> Fixed in the latest test version.

Thanks for the feedback - Reopening -  I will close the issue myself once I release this version officially, so it remains available for other users in this phase.

**Comment by RealRaven2000** [comment]
Added some detail to "What's new" screen with localisation:

[QuickFolders-mx-5.6.6pre21.zip](https://github.com/RealRaven2000/QuickFolders/files/6778915/QuickFolders-mx-5.6.6pre21.zip)

To install test version, download the zip file, then drag it into Tb Add-ons Manager.

**Comment by RealRaven2000** [comment]
Fixed in Release 5.6.6
