### ISSUE TITLE
Unreliable search if space and other delimiting characters (-_&+.@) are combined in search string

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#177]
If a folder is jumped to that contains consecutive " " and "-" characters then the automatically filled result from the last succesful quickMove / quickJump operation cannot be executed by hitting the [Enter] key anymore:

Example: searchin for the folder "reply- from - raven"
![image](https://user-images.githubusercontent.com/6314674/124757697-c3ff3b00-df25-11eb-8907-83faf752e6cb.png)

then jumping to the folder and opening the quickJump panel again:
![image](https://user-images.githubusercontent.com/6314674/124757769-d7120b00-df25-11eb-8186-8ad5059bd374.png)

Observed behavior:
- no search results are suggested
- Enter does not jump to the folder

Expected behavior:
- the menu entry should be shown
- Enter does should jump to the folder

Also, if we enter the correct folder name it will fail to match after the first space which follows a -  : 
![image](https://user-images.githubusercontent.com/6314674/124758179-3a9c3880-df26-11eb-8767-2a258d1f7fae.png)

no results are shown in dropdown as soon as the "f" is entered:
![image](https://user-images.githubusercontent.com/6314674/124758210-425bdd00-df26-11eb-82af-40f95d5abbb0.png)

**Comment by RealRaven2000** [comment]
Here are 2 test version, one for Thunderbird 68 (as it has the same regression after implementing the "spaced" syntax)

[QuickFolders-mx-5.6.6pre20.zip](https://github.com/RealRaven2000/QuickFolders/files/6778370/QuickFolders-mx-5.6.6pre20.zip)

[QuickFolders-wx-4.22.1pre9.zip](https://github.com/RealRaven2000/QuickFolders/files/6778369/QuickFolders-wx-4.22.1pre9.zip)

As always, these versions can be installed by downloading the zip file (5.* for Tb78, 4.* for Tb68 and older) and then dragging the zip file into Thunderbird Add-ons Manager.

**Comment by Clstei** [comment]
I just tested the test version "QuickFolders-mx-5.6.6pre20.zip" and can confirm that the problem is solved. The quick jump / quick move now works as expected - even for complicated folder names (with spaces and dashes) e.g. "X-Y - MyFolder".

**Comment by RealRaven2000** [comment]
> I just tested the test version "QuickFolders-mx-5.6.6pre20.zip" and can confirm that the problem is solved. The quick jump / quick move now works as expected - even for complicated folder names (with spaces and dashes) e.g. "X-Y - MyFolder".

That's good news, note that I also enable "in-string" search as long as the text you enter is at least 3 characters long. I hope this change doesn't return too many irrelevant results...

**Comment by RealRaven2000** [comment]
Fixed in Releases 5.6.6 and 4.22.2
