### ISSUE TITLE
QuickFolders doesn't load Toolbar on Thunderbird startup but does when reloading from Add-ons Manager

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#178]
> I have a problem with QuickFolders 5.6.5 Pro (TB 78.11.0 64-bit) since the last update.
> - QuickFolders bar does not appear when starting TB
> - After deactivating the add-in and reactivating it, it works once, after restarting TB it is not visible again
> > (translated from original German support request) Ich habe eine Problem mit QuickFolders 5.6.5 Pro (TB 78.11.0 64-Bit) seit dem letzten Update.
> > - QuickFolders-Leiste erscheint bei Start von TB nicht 
> > - Nach deaktivieren des Add-Ins und wieder Aktivieren funktioniert es einmalig, nach erneutem Start von TB wieder nicht sichtbar

**Comment by RealRaven2000** [comment]
The user sent me a debug log captured on Application startup, which contains the following line:

```
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIMsgFolder.subFolders]"  
nsresult: "0x80004005 (NS_ERROR_FAILURE)" 
location: "JS frame :: 
jar:file://///10.10.10.60/Archiv/Database/Thunderbird/Profiles/ACB/extensions/quickfolders@curious.be.xpi!/chrome/content/api/
ex_accounts/implementation.js :: traverseSubfolders :: line 142"  data: no] implementation.js:142:25
```

THis is a substitue API to avoid the [Thunderbird not asking for additional permissions bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1710359) which resulted in 1000s of users not being automatically updated. Here is a test version which removes the experimental ex_accounts API and instead adds the permission-required version (requesting accountsRead permission):

[QuickFolders-permissions-5.6.6pre22.zip](https://github.com/RealRaven2000/QuickFolders/files/6784175/QuickFolders-permissions-5.6.6pre22.zip)

It contains all the latest bugfixes and improvements planne for maintenance verison 5.6.6. To install, please download the zip file and drag it into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment]
The previous version (although using the official `accounts` API) exhibited similar behavior, which brings me to the conclusion that one of the accounts may be "unusual" on the target system. Here is a version that should skip "bad" accounts (hopefully only one of them is) and just look at the other ones for license validation. It will log any errors during account conversion (through my experimental ex_accounts library) for further investigation:

[QuickFolders-mx-5.6.6pre25.zip](https://github.com/RealRaven2000/QuickFolders/files/6785907/QuickFolders-mx-5.6.6pre25.zip)

**Comment by tmetro** [comment]
>Here is a version that should skip "bad" accounts...

I can confirm this version resolved the issue for me.

I didn't test extensively. Just two restart cycles. On the first load the extension initialized and showed the toolbar with the "what new" button. On the 2nd load the extension initialized and showed the toolbar, as expected.

>to avoid the Thunderbird not asking for additional permissions bug...

I was prompted to grant rather wide permission to the extension upon install.

**Comment by jobisoft** [comment]
> I was prompted to grant rather wide permission to the extension upon install.

FYI: https://support.mozilla.org/en-US/kb/permission-request-messages-thunderbird-extensions#w_have-full-unrestricted-access-to-thunderbird-and-your-computer

QuickFolders is being converted but still depends on core components like it did in the last years, and that is why you need to grant that full, unrestricted access permission. Like you have done for the last years (without being explicitly asked). The new permission system just makes that more obvious.

**Comment by RealRaven2000** [comment]
> > Here is a version that should skip "bad" accounts...
> 
> I can confirm this version resolved the issue for me.
> 
> I didn't test extensively. Just two restart cycles. On the first load the extension initialized and showed the toolbar with the "what new" button. On the 2nd load the extension initialized and showed the toolbar, as expected.
> 
> > to avoid the Thunderbird not asking for additional permissions bug...
> 
> I was prompted to grant rather wide permission to the extension upon install.

That part is by design (with all legacy Add-ons that have been converted to experimental Add-ons. You may also have noticed that pure "mail extensions" never add a toolbar, because there is no technically possibility to do this at the moment). The problem is that when I add the original "accounts" API back it will (nonsensically) ask for additional permissions, except it won't ask directly but only display this icon:
![image](https://user-images.githubusercontent.com/6314674/124976296-f9d81880-e026-11eb-9f3d-20997ad3dcaa.png)

I had 6000 users who missed this for at least a full month and thus never updated. Nevertheless I want to return to using the official "accounts" API as soon as possible and then the Add-on will fail for you again. That's why you should please take a look at the debug log with the version 
5.6.6pre25 because it will be able to tell you which of your accounts made it fail. The official API will just fail silently and then nobody will know what caused it! If that's what caused the issue you should see at least on line like this:@

convertAccount failed: `account` `ex`

If you see this you can potentially get a lot more info by clicking on the last 2 words.

**Comment by RealRaven2000** [comment]
How to generate a debug log on Thunderbird startup:

Open Error console with Ctrl+Shift+J, then configure it like this:

- enable the following panels:
![image](https://user-images.githubusercontent.com/6314674/124977067-f2fdd580-e027-11eb-8a72-db4cd50ca87e.png)


- restart Thunderbird

- once you're sure QuickFolders has loaded, open Error console again and you can capture the output like this:
![image](https://user-images.githubusercontent.com/6314674/124977107-00b35b00-e028-11eb-8410-cd3c1b612980.png)

Moreover if you can find a line starting with **_convertAccount failed_**, you can expand account and ex(ception) to get more information.

**Comment by RealRaven2000** [comment]
@TbSync from Thunderbird is working on a fix in the core code, here is a test add-on:
[accounts_folders.zip](https://github.com/RealRaven2000/QuickFolders/files/6787003/accounts_folders.zip)

This will list all accounts (if everything is ok) when you install it, looking like this:
![image](https://user-images.githubusercontent.com/6314674/124984994-cb136f80-e031-11eb-9449-fba70d536b74.png)

You can click on "accounts" for a closer look:
![image](https://user-images.githubusercontent.com/6314674/124985057-e2525d00-e031-11eb-985d-7056334da837.png)

Now see if you get the same output when you restart Thunderbird (I suspect something will cause an exception like it did in QuickFolders)

**Comment by RealRaven2000** [comment]
If anyone experiencing this bug wants to help even more, here are 4 test builds of Thunderbird that _should_ fix the problem - this would make it easier to land the patch quickly and fix it for everybody else:

win64: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/N8kiFKp0Q2S-u5NKG-HCpg/runs/0/artifacts/public/build/target.zip
win32: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/P9wLlADRQKWXYm3ukBN8CQ/runs/0/artifacts/public/build/target.zip
linux64: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/BK6U0vzfTVClXNET6C_wng/runs/0/artifacts/public/build/target.tar.bz2
linux32: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/HYBSUi_aQ96oK8rf1vcdHQ/runs/0/artifacts/public/build/target.tar.bz2

**Comment by tmetro** [comment]
> Thunderbird is working on a fix in the core code, here is a test add-on:
> [accounts_folders.zip]

Upon install I saw the object dump in the error console without error. But upon restart there was none, and no log message that I could find by filtering on "accounts" or "folders".

Anyway, just sharing that feedback as this was the quickest of the items you listed that could be tried. I see there are a pile of other things to try, so no need to respond. I'll give the others a try as time permits.

**Comment by jobisoft** [comment]
@tmetro : Could you try one of the thunderbird builds [linked by RealRaven](https://github.com/RealRaven2000/QuickFolders/issues/178#issuecomment-876740488) together with the official add-on version? The error we see should not be fixed in tha add-on, but in core code and the linked builds try to do that.

**Comment by RealRaven2000** [comment]
Related bug with patch by @jobisoft is here:
[accounts api fails on subFolders](https://bugzilla.mozilla.org/show_bug.cgi?id=1719739)
THis is going to land in Thunderbird 78.12, which is great news for Add-ons authors who need to use the accounts API on startup.

**Comment by jobisoft** [comment]
This is *probably* going to land in 78.12. No approval yet.

**Comment by RealRaven2000** [comment]
> This is _probably_ going to land in 78.12. No approval yet.

On thing that occurs to me with converting _all_ folders for the accounts, could this be improved by making it a "lazy getter"? I mean I have users with thousands of folders and am afraid calling this on startup could potentially cause delays or at least performance issues... Also the splash screen / licenzing code was "blocking" some of the following functionality, so I need to check whether I can all this stuff a lot later which probably would also fix the problem... 

I understand having a folder getting in accounts is handy, but initially all we care about are the actual main account properties (identities / mail addresses) and not the actual "meat of all the data"...

**Comment by jobisoft** [comment]
The information is just read from the DB, the "conversion" is just hiding stuff not needed in the WebExt. It would be interesting to do benchmarking on large profiles, however. 

You delay the startup of your add-on notably, I believe the delay by accounts.list() is only a fraction of that.

You splash screen should have never blocked anything, IIRC we delayed the splash screen until the licence had been calculated and then spun of the splash screen, independent of your remaining code. Nothing is waiting for the splash to finish, is there?

**Comment by RealRaven2000** [comment]
> The information is just read from the DB, the "conversion" is just hiding stuff not needed in the WebExt. It would be interesting to do benchmarking on large profiles, however.
> 
> You delay the startup of your add-on notably, I believe the delay by accounts.list() is only a fraction of that.
> 

Well, actually ... I was planning to drop the init delay down from 2500ms to 250ms because of user complaints (they need to know that they have configured tabs, and the default place holder text showed instructions on how to drag new folders in. I replaced this with a label "Initialising QuickFolders…" for the start and the instruction text will only come up when the tabs UI is actually initialized. I was thinking of dropping the delay altogether at some stage.

see issue #176  for details...

**Comment by jobisoft** [comment]
Ok, valid point. Lets get some benchmarking. I will create test addon and make a topic box post to ask other devs to test their own profiles.

**Comment by jobisoft** [comment]
[benchmark.zip](https://github.com/RealRaven2000/QuickFolders/files/6791894/benchmark.zip)

This adds a browser action button, which will benchmark a call to `accounts.list()` and write the result to the console.

**Comment by RealRaven2000** [comment]
> [benchmark.zip](https://github.com/RealRaven2000/QuickFolders/files/6791894/benchmark.zip)
> 
> This adds a browser action button, which will benchmark a call to `accounts.list()` and write the result to the console.
> 
> Edit: https://thunderbird.topicbox.com/groups/addons/Tdd8555451ea5cb59/benchmarking-accounts-list links back to here

Could a kind user with many accounts / folders please run the benchmark? This would be really valuable for @jobisoft and potential performance fixes in Thunderbird Core in the future.

**Comment by RealRaven2000** [comment]
I believe this one is resolved through using John's method of opening a promise in the installation listener:

```
  await new Promise((resolve) => {
    if (startupFinished) {
      if (isDebug) console.log("QuickFolders - startup code finished.");
      // Looks like we missed the one send by main()
      resolve();
    }
    callbacks.push(resolve);
  });
```
