### ISSUE TITLE
Allow single-key keyboard shortcuts

### ISSUE THREAD

**Issue by fanis** [RealRaven2000/QuickFolders#18]
Please consider adding the ability to press a single keyboard character to use the shortcuts quickMove / quickJump / etc, to allow for easier single-hand operation (for example: left hand uses keyboard, right hand uses mouse). This could be a configurable option.

The current best possible practice would be to cluster those shortcuts near, for example, the left SHIFT, so that you can use your left hand for all of it: SHIFT+Z, SHIFT+X, SHIFT+S, SHIFT+D. However, this can be error prone and would be improved by allowing pressing a single key.

**Comment by RealRaven2000** [comment]
Here is a trial version, you can now switch off the SHIFT accelerator individually for quickJump, quickMove and quickCopy:

![image](https://user-images.githubusercontent.com/6314674/71520359-960e5480-28b3-11ea-89bf-2181d6372dad.png)

This is 4.17.5 prerelease 25

[QuickFolders-wx-4.17.5pre25.zip](https://github.com/RealRaven2000/QuickFolders/files/4005507/QuickFolders-wx-4.17.5pre25.zip)

**Comment by RealRaven2000** [comment]
Implemented in 4.17.5 released on 27/12/2019

**Comment by fanis** [comment]
Nice job, this works splendidly and I believe improves usability for whoever wants to use it. I'm now using: "G" for jump/go, "S" for move, and "C" for copy.

**Comment by RealRaven2000** [comment]
> 
> 
> Nice job, this works splendidly and I believe improves usability for whoever wants to use it. I'm now using: "G" for jump/go, "S" for move, and "C" for copy.

Thanks! Leave a positive review [on ATN](https://addons.thunderbird.net/en-US/thunderbird/addon/quickfolders-tabbed-folders/) if you get time.

**Comment by RealRaven2000** [comment]
> 
> 
> Nice job, this works splendidly and I believe improves usability for whoever wants to use it. I'm now using: "G" for jump/go, "S" for move, and "C" for copy.

Thanks! Leave a positive review [on ATN](https://addons.thunderbird.net/en-US/thunderbird/addon/quickfolders-tabbed-folders/) if you get time.

Also, it's good if you mention GitHub - the more people use github for flagging issues (and requesting new functinos) the better the Add-on is going to get.
