### ISSUE TITLE
'What's new' notice seems temporarily to enable toolbar 

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#182]
It seems that when the 'what's new' notice is displayed, any window showing the contents of an email has this toolbar

![image](https://user-images.githubusercontent.com/47056543/125728845-fa14eaf1-4842-470f-b16e-3219eb60d878.png)

- even though I had that toolbar disabled. [EDITED.]

Also - and this seems a problem in itself - it is not obvious, from the toolbar itself, how to disable the toolbar. The toolbar does have a 'cog' icon, but clicking it merely opened the full option window in which the relevant option is hard to find. After some fiddling around, I discover that this is the requisite option:

![image](https://user-images.githubusercontent.com/47056543/125728702-b0719f1c-dbfb-495a-8047-d9b9948e575d.png)

I submit that that option should be easier to find.

QF 5.6.6
TBird 78.11.0
Linux Mint 20.2 Cinnamon

**Comment by RealRaven2000** [comment]
> It seems that when the 'what's new' notice is displayed, any window showing the contents of an email has this toolbar
> 
> ![image](https://user-images.githubusercontent.com/47056543/125728845-fa14eaf1-4842-470f-b16e-3219eb60d878.png)
> 
> * even though I had that toolbar enabled.
> 

I guess you meant "I had that toolbar disabled"? From the screen shot it looks like it's happening on Single Message windows? (when you open a message in new window)?

**Comment by RealRaven2000** [comment]
I wasn't able to reproduce this - neither displaying the "What'#s new" button on the left nor clicking on it to show the splash screen would display the current folder (navigation) toolbar in single messages windows.

**Comment by LinuxOnTheDesktop** [comment]
> I guess you meant "I had that toolbar disabled"? 

I did. Apologies. I have corrected my post.

I am unsure why I had the problem and you did not. I do find the following though. On a second Linux Mint computer, when I received the 'QuickFolders was updated! See what's new' message, and I then opened an email, I found that the toolbar appeared for _approximately one second_ and then disappeared.

**Comment by RealRaven2000** [comment]
The Splash screen "what's new" which was shown on Add-on update, has been disabled in 5.7 because it was too disruptive. Does this fix the issue for you?

**Comment by LinuxOnTheDesktop** [comment]
> The Splash screen "what's new" which was shown on Add-on update, has been disabled in 5.7 because it was too disruptive. Does this fix the issue for you?

No. Whilst the news window is open - the news window that, now, does not open automatically - the problem obtains.
