### ISSUE TITLE
I fear that the feature comparison page will boggle

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#192]
The text on https://quickfolders.org/premium.html#featureComparison is too long and in places that text confuses. Here are some (perhaps not all) of the specific parts that confuse.

'[ . .] Premium features that are unrestricted to licensed users': 'unrestricted to' is not really English. 'Premium' - if here being used as an adjective - should not be capitalised.

'For non-licensed users, the premium features can be restricted' - _can_ be? Not 'are'?

Also: I think you should make it plainer that there are now (yes?) three licenses, at least in a sense. For, there is: unlicensed; licensed; and thirdly a kind of super-license.

**Comment by RealRaven2000** [comment]
> The text on https://quickfolders.org/premium.html#featureComparison is too long and in places that text confuses. Here are some (perhaps not all) of the specific parts that confuse.

some of this particular section is outdated and still stems from the "one single Pro license" days. It's actually hard to put into words if wanted to describe the behavior completely, and it would be even more detailed

> '[ . .] Premium features that are unrestricted to licensed users': 'unrestricted to' is not really English. 'Premium' - if here being used as an adjective - should not be capitalised.

fixed.
> 'For non-licensed users, the premium features can be restricted' - _can_ be? Not 'are'?
> 
> Also: I think you should make it plainer that there are now (yes?) three licenses, at least in a sense. For, there is: unlicensed; licensed; and thirdly a kind of super-license.

Yeah I think one of the choices,  "unlicensed" is probably not a good label, but I don't want to use "free" either as there is a overlap with the "free as in freedom" idea of open source software. I was thinking of "unpaid" or "unfunded", but am not too sure where and how to summarize this correctly as of yet. I definitely need to review the top paragraph or the premium features page as well.

**Comment by RealRaven2000** [comment]
I think it should be a little clearer now... I also added Impressum / GDPR pages to my commercial Add-ons. If you find anything else that needs immediate improvement, please add below.

**Comment by RealRaven2000** [comment]
I will close this one for now, if you have new suggestions for improving feature comparison, please add them below!
