### ISSUE TITLE
Junk folder tab doesn't get focus when clicked (IMAP)

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#198]
I've just updated to Thunderbird 91, and there's something odd about the way that the junk folder tab behaves now. I set up a QuickFolders tab by dragging the appropriate folder to the QuickFolders tab bar, but when I click on the tab the focus doesn't move to it; Thunderbird continues to display the folder that I was viewing previously. All the other QF tabs work just fine. I'm using QF Pro 5.7.

![image](https://user-images.githubusercontent.com/6314674/130687053-733e760a-efe1-48d2-9799-80a970178344.png)

**Comment by RealRaven2000** [comment]
For additional detail in the error log, please enable the  debug mode on QuickFolders Settings / Advanced:
![image](https://user-images.githubusercontent.com/6314674/130687964-d8a6ba32-c924-4393-81c7-97040bdf5eb7.png)

 ...then right-click the debug option to also enable `extensions.quickfolders.debug.folders.select`

![image](https://user-images.githubusercontent.com/6314674/130688021-f40c2abe-fdbf-4902-a130-491b8132fe83.png)

**Comment by RealRaven2000** [comment]
Here is a test version. Not quite sure wheter it is 100% right yet. Tb91 doesn't have a simple gFolderTreeView.mode anymore but instead an array gFolderTreeView.activeModes, so the processing here must be slightly different to make sure the current view mode supports navigating to the folder. Thunderbird suppoorts combining multiple view modes at the same time, so there may be some weird untested combinations here that may lead to unexpected results.

[QuickFolders-mx-5.7.1pre4.zip](https://github.com/RealRaven2000/QuickFolders/files/7042223/QuickFolders-mx-5.7.1pre4.zip)

To install, download the zip file and drag it into Thundebird Add-ons Manager.

**Comment by HPG1972** [comment]
Just a test to see if I can comment now.

**Comment by HPG1972** [comment]
Testing: contents of error console:
[Error console 2021-08-25T1200Z.txt](https://github.com/RealRaven2000/QuickFolders/files/7046870/Error.console.2021-08-25T1200Z.txt)

**Comment by RealRaven2000** [comment]
Fixed in 5.7.1 released today
