### ISSUE TITLE
Subfolders with with length of 1 character omitted from quickJump search results

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#199]
Since QuickFolders 5.6 (presumably?), 1-character long subfolders are submitted when entering a search string that contains "/". E.g:
The subfolder QF/2 is not  found when entering "qf/2/"

![image](https://user-images.githubusercontent.com/6314674/131103071-b181796b-1da1-445b-a587-75c8dad1d3a7.png)

Instead the message "No matching parent folders!" is displayed

**Comment by RealRaven2000** [comment]
Fixed in 5.7.1 - released today

**Comment by edkett** [comment]
PERFECT!!! That's it. Now it works, I'm so happy you made my day and probably more than this.
