### ISSUE TITLE
Moving folders via the QF toolbar seems no longer to work

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#200]
**My system**

QF 5.7.1
Windows 10 Pro
License: 'Pro'

**The steps that generate the problem.**

1. Find a folder in Thunderbird's 'tree' view.
2. Begin to drag that folder, and hover over a QuickFolder (on the QF bar) that has subfolders.
3. Navigate to a subfolder.
4. Release the drag.
5. The result: the following error message.
![image](https://user-images.githubusercontent.com/47056543/131519039-4bfeb582-46e7-469e-a1d8-e0fda54be73e.png)

**Further information**

Perhaps I misunderstand something.

Moving emails works.

Moving folders via shift-M does work.

**_Ah: the error message itself tells me what I need to do!_**

EDITED.

**Comment by RealRaven2000** [comment]
Thanks. You cannot move folders via the subfolder tabs - I think this might overkill, so quickMove is probably the best way to do this.
