### ISSUE TITLE
Integration for Postbox v7

### ISSUE THREAD

**Issue by benosman** [RealRaven2000/QuickFolders#22]
Hello,

I use QuickFolders on Postbox v5, and really like it. I've held back upgrading to newer Postbox versions due to lack of this extension.  So, thank you for your work!

I noticed that they have reintroduced add on support in the form of [Postbox Labs](https://www.postbox-inc.com/product/labs) to v7.  I can't find any developer documentation to point you to unfortunately, but they seem to be xpi files as before.

I wondered if you would consider integration with v7 of Postbox?

On the off chance, I did try to load this extension (after changing install.rdf to permit v7) but got the following error:

```
Incompatible Extension
Postbox can only use the system dictionaries installed on your Mac.
```

**Comment by RealRaven2000** [comment]
I have done some conversion of FiltaQuilla for the new Postbox7 (we actually integrated its code into the Postbox source directly); can't say that I have much of a incentive to rewrite the code to make it work, as there are a lot of changes necessary and it's hard to test in a platform that I do not use regularly. On top, I really don't know how many Postbox users would actually be interested - there are no statistics on Postbox users on ATN.

If only I had another developer who uses Postbox regularly...

**Comment by RealRaven2000** [comment]
I am going to put this to the side for the moment - if you're highly interested get back to me in 6 months. Support for other platforms than Thunderbird (Seamonkey / Postbox) is probably unlikely as it takes too many resources.

**Comment by benosman** [comment]
Time flies - it is two years since your last comment, not 6 months.

I've stuck with Postbox 5 so I can keep QuickFolders running, but it is getting harder now on newer versions of macOS. I've scoured the web for other email clients, but just don't click with any right now.

I get that this is likely not viable for you to work on, but for your work with FiltaQuilla, did you uncover any docs for Postbox 7 extensions? 

I have no experience of Thunderbird extensions but I do know Javascript well.

**Comment by RealRaven2000** [comment]
> I've stuck with Postbox 5 so I can keep QuickFolders running, but it is getting harder now on newer versions of macOS. I've scoured the web for other email clients, but just don't click with any right now.
> 
> I get that this is likely not viable for you to work on, but for your work with FiltaQuilla, did you uncover any docs for Postbox 7 extensions?

To be honest I didn't waste any time with Postbox after the owners decided top not even pursue allowing side-loading of Add-ons. the risk of writing anything and being cut off like this has just no relation to the benefits, and we have rather substantial changes coming up in Thunderbird, so we really need to keep struggling to stay in sync with that plattform.

If you are interested in better filtering solutions I highly recommend looking into Betterbird - for instance, they implemented the mixed "any" / "all" search terms, and I intend to support things like merge or assistant to work better with this technology. Also need to look into whether backup / restore is fully compatible.
