### ISSUE TITLE
[QuickFolders] 5.8.3 - `...licenser.forceSecondaryIdentity` no longer works

### ISSUE THREAD

**Issue by ranman3g** [RealRaven2000/QuickFolders#220]
With release of 5.8.3, and TB 91.2.1 (64bit) QuickFolders no longer recognizes Pro license  key issued to a secondary email address.

As an example:

Account profile Primary email address:  myname@example.com
Account profile Secondary identity email address: applicationname@example.com

License key purchased and generated with applicationname@example.com email address: 
QF-applicationname@example.com:2022-11-02;093fef807fd9f3f1db6f471d95ad38c6fecfb17bf166e7f3c3fa5097c8f5a27e 26984810ea283c4c85502150163a727f7ad73d422681f02d147ba5c123308d97

Configuration
`extensions.quickfolders.licenser.forceSecondaryIdentity` set to **TRUE**

QuickFolders options->licenses reports:

> "The email address that is bound to the license key [applicationname@examplecom] is currently not listed in any of your email accounts..[]..."

AFAIK, this configuration worked prior to QuickFolders 5.8.3.
Toggling  configuration flag and rebooting TB showed no change in behavior.

Thanks for looking into this.
-Kent I.

**Comment by RealRaven2000** [comment]
Can you test this version please?

[QuickFolders-mx-5.9pre11.zip](https://github.com/RealRaven2000/QuickFolders/files/7620512/QuickFolders-mx-5.9pre11.zip)

**Comment by RealRaven2000** [comment]
Fixed in 5.9, released on 30/03/2022
