### ISSUE TITLE
Time conditionals

### ISSUE THREAD

**Issue by vanguardemails** [RealRaven2000/QuickFolders#227]
HI,
Could you please add options for dynamic greeting depending on the current time.

similar to:
var date = new Date();
if (date.getHours() <  5) return "Good night";
if (date.getHours() < 12) return "Good morning";
if (date.getHours() < 16) return "Good afternoon";
if (date.getHours() < 21) return "Good evening";

return "Good night";

example from: jobisoft/quicktext

Many thanks
M.S.

**Comment by RealRaven2000** [comment]
Writing a parse that supports boolean or mathematical expressions like you showed is very difficult. If we stick to the current syntax of SmartTemplates variables, such as:

`%variable(option1,option2,option3,...)%`

...what would be the most convenient way of implementing this?

Maybe something like this:
```
%insertFirstConditional(operator1,operand2+operator2,result2{,operandN+operatorN,resultN]}%

%insertFirstConditional(time,<5,"Good night",<12,"Good morning",<16,"Good afternoon,<21,"Good evening")%
```

By the way I think we you might still be able to use a Javascript "scriptlet", as implemented by Benito van Zander in [bug 25676](https://quickfolders.org/bugzilla/bugs/show_bug.cgi@id=25676)


```
%{% 
(function() { 
  var date = new Date();
  if (date.getHours() < 5) return "Good night";
  if (date.getHours() < 12) return "Good morning";
  if (date.getHours() < 16) return "Good afternoon";
  if (date.getHours() < 21) return "Good evening";

  return "Good night";
})()  
%}%
```

You need to enable the undocumented about:config switch

`extensions.smartTemplate4.allowScripts = true`

I have not tested this - but feel free to try it out.

**Comment by RealRaven2000** [comment]
Issue needs to be relocated to the [smartTemplates github](https://github.com/RealRaven2000/SmartTemplates/issues). Doesn't apply to QuickFolders.
