### ISSUE TITLE
Feature request: show subfolders upon hover, and not only when moving

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#229]
When moving an email via a quickFolder, a list of subdirectories can appear. It would be good were such a list to appear (or rather be configured to appear) when merely hovering over a quickFolder. Or perhaps that option exists already and I have failed to locate the option!

**Comment by RealRaven2000** [comment]
there is no such option by merely hovering - while it would be possible it would give a very "twitchy" experience - you would have lots of menus popping up while merely "traversing" between the top and bottom half of the screen, so I am doubtful that it would be really that beneficial - most users would regard it as a distraction. I understand you want to "save one click" but if you are really unsure where a seldomly visited folder is located, you can use the quickJump function (click the quickJump button or hit Shift+J and start typing the folder name):

![image](https://user-images.githubusercontent.com/6314674/145719488-a5779407-3ef3-401f-afcd-ce6a38f43e63.png)

simply hit ESCape to stop this operation.

**Comment by LinuxOnTheDesktop** [comment]
All that makes sense. Thank you. I had forgotten about the quickJump function!
