### ISSUE TITLE
Quickjump fails when TB folders are in 'Unread Compact' mode

### ISSUE THREAD

**Issue by RobertvanderHulst** [RealRaven2000/QuickFolders#235]
I am working with TB 91.5.1 x64 on windows, QuickFolders 5.8.3 Pro
When the folders of TB are in Unread Compact mode then a QuickJump fails and displays the message "could not find folder".
You can see that the folder view "All Folders" is selected as well as the unread compact folders.
If you try it again then he "All folders" view is deselected again.
When TB is in "All folders" mode only then it works.
It looks like QuickFolders does not know that the various folder modes are no longer mutually exclusive and can be selected side by side.

**Comment by RealRaven2000** [comment]
I tested this with the Unread Folders view, not sure whether I did that right:

![image](https://user-images.githubusercontent.com/6314674/151970969-96900c6b-7ab4-4bb1-8e65-3003467eebf8.png)

With both quickJump and quickMove (using Shift+J and Shift+M) this folder location worked for me, (jumping from an IMAP account across to a local folder) but maybe you have configured something differently? I iterate all folders of every account internally (without looking at the tree at all)

Make sure you didn't exclude any accounts in quickMove advanced settings (in QF Settings / Licenses / Premium Features [Advanced search settings...])

![image](https://user-images.githubusercontent.com/6314674/151971515-ad196013-5bae-4470-918f-c81cd4e45584.png)

**Comment by RobertvanderHulst** [comment]
Thanks for the reply.
There are NO excluded accounts.
And you are right: work with the unread folders view, but not if you also include the "compact view" option. THat is why I said "Unread Compact" in the subject

**Comment by RealRaven2000** [comment]
I was able to move a folder using the "Compact View" but wasn't able to jump there with quickJump. At first I didn't get an error message though - there seems to be a toggle between the top part (All Folders) while Unread Folders is kept being displayed in Compact mode. I think jumping to a folder in compact view may be a genuine problem right now. 

So far if the folder couldn't be displayed I may have switched to "All Folders" - but the "Compact View" setting is a new concept I haven't used before. Note that copying or moving mail (via any method in QuickFolders, including dragging the mail onto a tab or folder submenu item of it) does not require the folder tree to be in any particular state.

**Comment by RobertvanderHulst** [comment]
I know that Copy and Move work. I use that all the time. It is just the jump that has a problem.
I am glad you are seeing this too now.
It is not s show stopper, but I have gotten used to the ^J key to jump. Now I will have to make sure that the folder tree is in All Folders mode only before using the key.

**Comment by RobertvanderHulst** [comment]
Thanks,
This works as expected. 
It adds the "All Folders" view (so the folder can be selected) and the Unread /Compact is still there.

**Comment by RealRaven2000** [comment]
Fixed in 5.9, released on 30/03/2022

**Comment by RobertvanderHulst** [comment]
Thanks!
