### ISSUE TITLE
Using `=` key for folders from recent quickMove / quickJump operations (not all recent folders)

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#242]
When typing the key `=` into the search box after moving mail to the quickMove button or entering the quickMove shortcut (Shift+M being the default combo), QuickFolders will not move the files but only jump to the folder. Expected behavior: the menu should work similar to the normal search box, and allow moving / copying emails, just like the recent folders tab.

**Comment by RealRaven2000** [comment]
Here is a test version:

[QuickFolders-mx-5.9pre33.zip](https://github.com/RealRaven2000/QuickFolders/files/8235746/QuickFolders-mx-5.9pre33.zip)

to install download the zip file and drag directly into Thunderbird Add-ons Manager.

**Comment by jaysmithgit** [comment]
Now using [QuickFolders-mx-5.9pre33.zip] ...

quickMove now works as expected with the assigned "move key" followed by "=". 

Wonderful.

**Comment by RealRaven2000** [comment]
> Now using [QuickFolders-mx-5.9pre33.zip] ...
> 
> quickMove now works as expected with the assigned "move key" followed by "=".
> 
> Wonderful.

I would like to improve this feature somewhat - at the moment it shows the most recent folders, by timestamp - these timestamps are also set when new mail arrives, even triggered by filters.

I think if it is used mainly for quickJump and quickMove (so going to an explicit folder based on this particular QF function), it would be way more useful to display only folders from that list. But that also means that I need to store a queue of last moved / copied to and jumped to folders. Do you agree that this would be more useful than the standard "Recent folders" history?

**Comment by jaysmithgit** [comment]
First, in terms of my use and environment...

I had certainly noticed that the ordinary (*not* using the "=") quickMove and quickJump actions displayed the entire recent list including folders that I had randomly or intentionally clicked on. It did not "bother" me, but it is clutter.

However, I had *not* noticed that the recent list included situations where presence of a path on the list is triggered by incoming mail or incoming filtered mail. But, *I* did not notice those items on the list because *I* only *via TB* have mail coming in to the Inbox (which I am always clicking on anyway, so I expected that it would in the recent list). We have our own mail server, etc. All our "filtering" type of actions, of which we have many, are happening upstream, using Sieve, moving/copying directly into the shared IMAP structure, thus is more global, works with any email client because it happens before the email client sees incoming emails, and can copy/move mail to IMAP folders used as IMAP special-purpose inboxes by other users.

To your question...

As long as the list you are talking about displaying and storing is the folders that actually had quickMove and quickJump actions, then, yes, what you describe seems more useful and less cluttered (for some/many users).  

However, if you also meant to include the results list of ALL the paths of most recent search (including those NOT recently selected for qM/qJ actions, then that would add more clutter and confusion.  But, I don't believe you are suggesting that.

I am a little confused if, for qM/qJ, the keystroke+"=" is now duplicative, now that the whole recent list situation seems to be cleaned up.  Does the "=" **now** add additional functionality that is beyond just the qM/qJ keystroke (perhaps plus down-arrow), by itself?  (I am fine with however this works best for the largest number of users.)

**Comment by RealRaven2000** [comment]
> As long as the list you are talking about displaying and storing is the folders that actually had quickMove and quickJump actions, then, yes, what you describe seems more useful and less cluttered (for some/many users).
> 
> However, if you also meant to include the results list of ALL the paths of most recent search (including those NOT recently selected for qM/qJ actions, then that would add more clutter and confusion. But, I don't believe you are suggesting that.

no, that would be madness. Of course only the folders that you actually jumped into or moved mail into, these are the actually valuable folders that you most likely will want to to visit / file mail to again. If I am storing these, the question is should these be 2 separate lists? I believe jumping to a folder that I previously moved mail to may be desirable as well as the opposite situation too. If we had 10-15 items that could be quite powerful.

At the moment what I am doing is using the MRU (most recently used) timestamp of each folder, which is partly maintained by Thunderbird itself. Obviously I will have to manage recent quickMove/ quickJump operations completely separately

> I am a little confused if, for qM/qJ, the keystroke+"=" is now duplicative, now that the whole recent list situation seems to be cleaned up. Does the "=" **now** add additional functionality that is beyond just the qM/qJ keystroke (perhaps plus down-arrow), by itself? (I am fine with however this works best for the largest number of users.)

At the moment it is just simply an access key into the "recent folders" list (which is based on the MRU time) but I feel it would be more useful if it just restricted itself to only the folders that had been successfully jumped to / filed mail into through the actual quickJump and quickMove functions. It stands to reason that somebody who uses both these features regularly would benefit much more by this focus. 

Another possibility would be to also include filings / jumps that are carried out through clicking on a QuickFolders tab / or a subfolder menu such a tab. But that may also feel like an unnecessary duplication to somebody who uses the tabs a lot and has developer the muscle memory for their main / favorite folders?

**Comment by jaysmithgit** [comment]
> No, there is no additional functionality right now - but that's what I propose to change.
> 
> At the moment it is just simply an access key into the "recent folders" list (which is based on the MRU time) but I feel it would be more useful if it just restricted itself to only the folders that had been successfully jumped to / filed mail into through the actual quickJump and quickMove functions. It stands to reason that somebody who uses both these features regularly would benefit much more by this focus.

This sounds good.  Just to make sure I understand...

The qM/qJ keystroke would still use the MRU list as before...

but the qM/qJ keystroke PLUS "=" would use your special/new list that is "successfully jumped to / filed mail into through the actual quickJump and quickMove functions".

> Another possibility would be to also include filings / jumps that are carried out through clicking on a QuickFolders tab / or a subfolder menu such a tab. But that may also feel like an unnecessary duplication to somebody who uses the tabs a lot and has developer the muscle memory for their main / favorite folders?

I don't feel qualified to have much of an opinion about this. I think I can see both sides/opinions, but I only have 7 such tabs (for super-common folders that are not normally visible, i.e. buried deep in the IMAP structure) and thus I am not a power-user of that tab method, thus I don't know how a power-user would think about it.

What I will say is that **my** personal preference is to use the keyboard as much as possible -- having to use a mouse just slows me down, though I don't have any physical limitations using a mouse.  With this in mind, I probably **would** make use of the keyboard to qM./qJ into folders that I had recently accessed using the tabs.

**Comment by RealRaven2000** [comment]
> This sounds good. Just to make sure I understand...
> 
> The qM/qJ keystroke would still use the MRU list as before...

no, it _never_ did that, it was never based on recent lists. [That's what the other (recent folders tab) was meant for.] quickMove and quickJump purely based their results on the letters of the folder name and or parent folders, that you entered and searched through _all_ folders. The behavior (based on what you enter) is briefly explained when you click on the blue question mark to the right of the search box:

![image](https://user-images.githubusercontent.com/6314674/158032591-385cc815-12ce-4706-afbe-b838ea53c294.png)


> but the qM/qJ keystroke PLUS "=" would use your special/new list that is "successfully jumped to / filed mail into through the actual quickJump and quickMove functions".

yes that's my current new idea.


> What I will say is that **my** personal preference is to use the keyboard as much as possible -- having to use a mouse just slows me down, though I don't have any physical limitations using a mouse. With this in mind, I probably **would** make use of the keyboard to qM./qJ into folders that I had recently accessed using the tabs.

Yes that's why the keyboard shortcuts are so important and are a distinguishing feature between Standard and Pro licenses. I just don't currently want a global shortcut for accessing recent folders and leave this area to other Add-ons for now.

**Comment by jaysmithgit** [comment]
> > This sounds good. Just to make sure I understand...
> > The qM/qJ keystroke would still use the MRU list as before...
> 
> no, it _never_ did that, it was never based on recent lists. [That's what the other (recent folders tab) was meant for.] quickMove and quickJump purely based their results on the letters of the folder name and or parent folders, that you entered and searched through _all_ folders. The behavior (based on what you enter) is briefly explained when you click on the blue question mark to the right of the search box:

Sorry, my bad -- I got confused.

I look forward to what you are proposing.

**Comment by fredstluka** [comment]
Yes, I think any MRU list displayed or taken into consideration for
any reason by QF should based on folders recently moved or jumped
to, NOT based on all folders recently accessed by TB.

One MRU list is fine for me.  No need to store separate lists for move
and jump.

My 2 cents worth...
--Fred

**Comment by RealRaven2000** [comment]
So I made a prototype which doesn't show all recent folders but should only give a "focused" set of results out of recent successful quickMove / quickJump operations. In order to use this successfully you obviously have to build up the history first (you have to use quickMove / quickJump for a little while - should this be pointed out in the quick help popup?). The info is stored in the configuration setting `extensions.quickfolders.quickMove.history` )

[QuickFolders-mx-5.9pre107.zip](https://github.com/RealRaven2000/QuickFolders/files/8358053/QuickFolders-mx-5.9pre107.zip)

To install, download the zip file and drag into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment]
Implemented in 5.9, released on 30/03/2022

**Comment by RealRaven2000** [comment]
When using for the first time, there may not be any results. Should there be a warning about an empty history in this case?

In any case, the Help text could be somewhat improved, to:

Type `=` to get a list of folders that were most recently entered.

Also should it mention here that this feature requires a Pro License?

**Comment by fredstluka** [comment]
> When using for the first time, there may not be any results. Should 
> there be a warning about an empty history in this case?
>

Not necessarily.  Wouldn't hurt, but it's low priority, I'd say.
Most users will probably use QuickMove or QuickJump at least
once before trying the "=" feature.  After they've done so,
there will always be results in the future.  So, most people
would never see the empty history warning, and those who
do would only see it once, the very first time they hit "=".


> In any case, the Help text could be somewhat improved, to:
>
> Type |=| to get a list of folders that were most recently entered.
>

Sounds good.

> Also should it mention here that this feature requires a Pro License?
>

Mention in the Help text?  Yeah, may as well.

--Fred

**Comment by RealRaven2000** [comment]
> > Also should it mention here that this feature requires a Pro License?
> Mention in the Help text?  Yeah, may as well.

actually, it's not Pro only - Standard licensees are restricted to 10 results max. Maximum 25 results for Pro users - which I might make configurable for them in the future.

**Comment by fredstluka** [comment]
A default of 25, with ability to configure to a different max sounds good to me!

--Fred

**Comment by RealRaven2000** [comment]
> A default of 25, with ability to configure to a different max sounds good to me!

this will come in time. I might integrate additional search settings into the "help" panel, something like this:

![image](https://user-images.githubusercontent.com/6314674/161957073-6d6b1ab0-7219-411a-b47f-85e0b0dd1332.png)
