### ISSUE TITLE
Seamonkey (2.53.11.1): QF Tabs and search do not lead to related folders. 

### ISSUE THREAD

**Issue by ggianna** [RealRaven2000/QuickFolders#258]
After updating Seamonkey to latest (Mozilla build repository) version (2.53.11.1) on Linux (Kubuntu 20.04.4 LTS, x86_64) I am facing the following problems:

- Clicking on QF tabs does not lead me to related folders.
- Using (Pro) action Jump, searching for folder and selecting one does not lead to the selected folder.
- Shortcuts to tabbed folders (e.g. Alt+1, ...) do not lead to related folders.

**Related notes:** 

- The plugin worked up to version 2.53.2 (if I am not mistaken) for certain.
- I tried refreshing the tabs and removing orphans. No orphan found and nothing changed.
- Moving (through the Pro shortcut) works fine.
- I tried to disable and re-enable the plugin, to no avail.
- I removed and re-added tabs, to no avail.
- Searching for a folder (during move or jump) works. It is only the final step that appears to fail.

Thank you for the support and excellent plugin.

**Comment by RealRaven2000** [comment]
I am afraid I cannot support Seamonkey anymore - the code is just so outdated, it's based on mozilla-central v 53, and we are now preparing for version 102. You are probably running a very old version of QuickFolders? The current version of QuickFolders is 5.9.1, and the lowest Thunderbird version it runs on is 78. This is the Thunderbird version from which legacy Add-ons could not be installed anymore.
