### ISSUE TITLE
Rules for moving mails to a specific folder are permanentely disappearing

### ISSUE THREAD

**Issue by hanjo11** [RealRaven2000/QuickFolders#264]
When I create rules for moving mails from one folder to another folder then this rules are not working when I restart Thunderbird  next time.

Sometimes the name of the rule is existing but the rule has no content anymore. Sometimes the rule is completely gone. Checking the rule directly after its creation shows that the arguments are there as wanted.

This behavior is not only visible on one of my PCs but on all.

**Comment by hanjo11** [comment]
Sorry this is not for quickfolder but for quickfilter

**Comment by RealRaven2000** [comment]
can you check with https://github.com/RealRaven2000/quickFilters/issues/9 ?

**Comment by RealRaven2000** [comment]
> When I create rules for moving mails from one folder to another folder then this rules are not working when I restart Thunderbird next time.
> 
> Sometimes the name of the rule is existing but the rule has no content anymore. Sometimes the rule is completely gone. Checking the rule directly after its creation shows that the arguments are there as wanted.
> 
> This behavior is not only visible on one of my PCs but on all.

if you report this on quickFilters issues, can you add the Thunderbird version number?
