### ISSUE TITLE
Moving emails with QuickFolder stops working with Exchange and DavMail

### ISSUE THREAD

**Issue by stratosjl** [RealRaven2000/QuickFolders#267]
DavMail works as a proxy to the Exchange server (modern O365), offering the local TB client the option to connect via IMAP. 
However, after a few times that QuickFolders move is used, TB stops responding to moves (although it produces the message "moved X messages to folder". The solution here is to shut down TB and restart. 

In order to test this, I have purchased an annual subscription to "OWL for Exchange" and replaced DavMail. The issue does not seem to exist there, so it is either caused by DavMail or IMAP interworkings. 

Just a heads up, you may close the issue, as QuickFolders do not directly cause it.

**Comment by RealRaven2000** [comment]
ok, good to know.
