### ISSUE TITLE
QuickFolders navigation pane distorted and unusable

### ISSUE THREAD

**Issue by beeskeptical** [RealRaven2000/QuickFolders#28]
In Thunderbird 68.5.0 for Mac OS, the folder navigation pane opens in a distorted and unusable state until I click to customize the menu bars and widgets, upon which it returns to normal.  But i have to do this every time I launch Thunderbird to be able to use QuickFolders.  See images:

Distorted:

![Screen Shot 2020-03-05 at 6 34 36 PM](https://user-images.githubusercontent.com/40899073/77836114-95829580-7110-11ea-8648-f92b85db024b.png)

Corrected:

![Screen Shot 2020-03-05 at 6 47 57 PM](https://user-images.githubusercontent.com/40899073/77836122-a59a7500-7110-11ea-86cd-a5b0c651b45b.png)

**Comment by RealRaven2000** [comment]
Can you please show a larger screenshot for context - I am not really sure where this "folder navigation pane" is. Is it part of the 3-pane window? Are there special configuration steps to make it visible?

**Comment by beeskeptical** [comment]
@RealRaven2000 Here you go:

![Screen Shot 2020-03-29 at 2 08 45 PM](https://user-images.githubusercontent.com/40899073/77860949-ee146a00-71c6-11ea-840b-36154f930687.png)

**Comment by beeskeptical** [comment]
Any plans to fix this?

**Comment by RealRaven2000** [comment]
sure. Only problem  - I cannot reproduce this on windows and I do not own a Mac. The folder navigation always looks fine. The best way tro check what is happenign would be (on a Mac system) to open inspector (Tools / Developer Tools / Developer Toolbox) and then using inspector to find the offending element - this is what it looks lijke on windows;
![image](https://user-images.githubusercontent.com/6314674/78713665-88388880-7912-11ea-8e3c-830f769810eb.png)

I can't really find the smaller rectangle that you have - can you find out what id it has or what it is? You can click on it and also check the Rules to see whether any have been overwritten by a quickfolder related css file.

**Comment by beeskeptical** [comment]
@RealRaven2000 Hey, sorry for the delay.  It's called the "QuckFolders Toolbar" and looks like this in the group of widgets one can select to customize the Thunderbird toolbar on Mac:

![Screen Shot 2020-04-17 at 2 18 49 PM](https://user-images.githubusercontent.com/40899073/79614904-61b6e200-80b6-11ea-8d79-052eff6cf8ec.png)

![Screen Shot 2020-04-17 at 2 18 41 PM](https://user-images.githubusercontent.com/40899073/79614912-67142c80-80b6-11ea-999b-0af147004ee5.png)

I don't know how to access Rules, sorry.

**Comment by beeskeptical** [comment]
@RealRaven2000 Hey, sorry for the delay. The widget, found in the group of widgets one can select to customize the Thunderbird toolbar on Mac, is called "Folder Location." 

Perhaps it's not yours after all?  Sorry, I don't know how to access "Rules."

**Comment by RealRaven2000** [comment]
> 
> 
> @RealRaven2000 Hey, sorry for the delay. The widget, found in the group of widgets one can select to customize the Thunderbird toolbar on Mac, is called "Folder Location."
> 
> Perhaps it's not yours after all? Sorry, I don't know how to access "Rules."

that's correct. It isn't mine. It's also complete news to me that somebody called it Quickfolders (like my (Add-on). However it is a built in widget of Thunderbird; at least here in Windows none of the contained elements seem top be affected by any of my own style rules.

![image](https://user-images.githubusercontent.com/6314674/79618031-dc0c5400-8100-11ea-8155-c1ec46b9b6f4.png)

**Comment by beeskeptical** [comment]
@RealRaven2000 OK, thank you and apologies for wasting your time and attention with it.  Happy either to delete this thread to prevent confusion, or leave it for clarification in case anyone else has the same issue/confusion as me.
