### ISSUE TITLE
Slowdown of Thunderbird 102 with QuickFolders

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#283]
From a user report:

"Thunderbird 102.0.1 is down on her knees after updating QuickFolders to 5.10.2. Either the response is very slow, or the title at the top displays "Not Responding". When I disable QF everything is back to normal."

I also experience sluggish Thunderbird UI, (even after rolling back to QuickFolders 5.10) I suspect this is related to the Folder Tree rewrite.  Hiding the folder tree with [F9] gives some temporary relief.

**Comment by RealRaven2000** [comment]
To do:

investigate whether calls to / exceptions thrown by `nsIMsgFolder.getStringProperty()` can slow down Thunderbird. I will have to write some test mode that completely bypasses folder tree icon manipulation

**Comment by pol-hallen** [comment]
I've same problem

**Comment by RealRaven2000** [comment]
> I've same problem

Can you check whether hiding the folder tree (you can use the shortcut F9 or just View / Layout / Folder Pane makes Thunderbird faster? So far I haven't found an older version of QuickFolders that fixest the problem, so I definitely still need to find the code that causes slow down.

**Comment by RealRaven2000** [comment]
It would be a good idea to check for activity in Javascript error console (Ctrl+Shift+J) to see if there is a lot of activity. I did kind of minimize a lot of output in 5.2.10 but I am still noticing a log of messages like this when I start up:

```
Error in addSubFoldersPopupFromList
Component returned failure code: 0x80550007 [nsIMsgFolder.getStringProperty]
```

**Comment by RealRaven2000** [comment]
I also notice that the height of the windows (number of folders currently displayed) has an influence on the slowdown. The more folders in the tree are shown, the slower Thunderbird gets.

Here is a patched version that supports bypassing the icon code for the folder tree:

[QuickFolders-mx-5.10.3pre5.zip](https://github.com/RealRaven2000/QuickFolders/files/9072841/QuickFolders-mx-5.10.3pre5.zip)

In order to bypass icon processing, you need to set
`extensions.quickfolders.folderTree.icons = false`
![image](https://user-images.githubusercontent.com/6314674/178013728-4a29923e-0d9f-4b70-afbb-9c0374b6dfb4.png)

Then install the patched version above (download zip file and drag into Add-ons Manager)

To re-enable Icons, set `extensions.quickfolders.folderTree.icons = true` again, then reload the Add-on 

(Add-ons Manager QuickFolders / right-click /  reload) or restart Thunderbird.

![image](https://user-images.githubusercontent.com/6314674/178014004-b29f0791-e5e4-4d25-9d29-9cdd17cb97e4.png)

**Comment by RealRaven2000** [comment]
Here is a version that alleviates problems from issue #284 - it may also overall speed up Thunderbird with QuickFolders (if you also omit icon code) - again a lot of slowdown is caused by the function `nsIMsgFolder.getStringProperty()` - I will try to eliminate it completely from QuickFolders' code:

[QuickFolders-mx-5.11pre13.zip](https://github.com/RealRaven2000/QuickFolders/files/9079043/QuickFolders-mx-5.11pre13.zip)

To install, download zip file and drag into Add-ons Manager. This version is also compatible with Thunderbird 91 (and is a lot faster there).

**Comment by adamgolebiowski** [comment]
I have just installed 5.11pre13 - it works better now (I no longer get unresponsive window), but there is still difference comparing to running Thunderbird with quickfolders disabled.

**Comment by RealRaven2000** [comment]
> I have just installed 5.11pre13 - it works better now (I no longer get unresponsive window), but there is still difference comparing to running Thunderbird with quickfolders disabled.

There is definitely more work to do here - but did you also set `extensions.quickfolders.folderTree.icons = false` ?

**Comment by mscag** [comment]
> From a user report:
> 
> "Thunderbird 102.0.1 is down on her knees after updating QuickFolders to 5.10.2. Either the response is very slow, or the title at the top displays "Not Responding". When I disable QF everything is back to normal."
> 
> I also experience sluggish Thunderbird UI, (even after rolling back to QuickFolders 5.10) I suspect this is related to the Folder Tree rewrite. Hiding the folder tree with [F9] gives some temporary relief.

I've same problem

**Comment by mscag** [comment]
> I have just installed 5.11pre13 - it works better now (I no longer get unresponsive window), but there is still difference comparing to running Thunderbird with quickfolders disabled.

5.11pre13 didn't change the situation that much. Still can not use TB when QF is enabled. I wonder if the number of messages (400K+) have any effect.

**Comment by RealRaven2000** [comment]
> I was wondering why is TB so slow lately... Turning QF off fixes the issue, waiting for solution as I need this plugin.

Try to install the prerelease version ([5.11pre13](https://github.com/RealRaven2000/QuickFolders/files/9079043/QuickFolders-mx-5.11pre13.zip)) in the comment above and _disable icons_, using Thunderbird Menu / Tools / Settings / General / Config Editor...

![image](https://user-images.githubusercontent.com/6314674/178714719-ea6ecd82-a265-492e-b9a3-7415fa38e686.png)

in search field insert "extensions.quickfolders.folderTree.icons" and toggle the setting to false
![image](https://user-images.githubusercontent.com/6314674/178714834-73b63c94-efc6-459d-8fa6-45c1e3a242ec.png)

You may have to restart Thunderbird to see the effect. I will post improved versions that hopefully still support icons without performance penalty soon. Note that automatic Add-on updates (the next official version of QF 5.11) will automatically replace the preview version - and should contain the final fix for this problem.

**Comment by RealRaven2000** [comment]
Continuing development on [Branch ESR102](https://github.com/RealRaven2000/QuickFolders/tree/ESR102). Just committed my changes so far. I will test @jobisoft 's method of hardcoding the folderIcon with a function that generates the CSS selector on the fly (from the connected folder's URI) - this will avoid calls to `getStringProperty()`.

**Comment by RealRaven2000** [comment]
My observations so far:

When adding popup sets to the tabs there is considerable performance waste while loading the folder buttons. I have about 249 Tabs, but not all of them are visible (using folder categories I only display a subset of these) - however when I reload the add-on a popupset if generate for every single one of the buttons (even if they are not shown on screen) - this adds an overhead of around 3500 mseconds. I cannot completely omit generating these menus because they are needed for speedy reaction times when dragging emails to the tabs. But I can try two measures  here

- make sure to only generate popup menus for buttons that are / will be shown on screen
- generate the popup menus asynchronously (they are not needed immediately when generating the tabs)
- when a tab is clicked a fresh menu is generated anyway so there is no rush in generating all menus immediately on starting Thunderbird / reloading the Add-on.

- On startup (after a timer) repairFolderTreeIcons is called. This calls setFolderTreeIcon multiple times (as many times as tree icons are defined). setFolderTreeIcon calls QuickFolders.updateFolders() which adds a lot of overhead.

I have removed the call to updateFolders() from the setFolderTreeIcon routine, and added a different way of styling the tree icons - there is some fallout with "invisible" folder icons now, but it's a good start with better performance so far:

[QuickFolders-mx-5.11pre29.zip](https://github.com/RealRaven2000/QuickFolders/files/9103656/QuickFolders-mx-5.11pre29.zip)

to install this optimized version, download the zip file and then drag the zip file into Thunderbird Add-ons Manager (do not unpack it)

**Comment by RealRaven2000** [comment]
I added more optimizations mainly when loading the Add-on. If a non-folder tab is selected while updating there is no unnecessary recreation of *all* folders and submenus in the background. There is also now an initial state for the selected category "INIT" (empty category) rather than starting from "ALL". The actual category should be set later by the tab.

I still need to solve the Add-on restoring the current tab independently of the Thunderbird session (see #279). It's highly likely that I have to store the category per tab using internal session management.

[QuickFolders-mx-5.11pre35.zip](https://github.com/RealRaven2000/QuickFolders/files/9105684/QuickFolders-mx-5.11pre35.zip)

to install this optimized version, download the zip file and then drag the zip file into Thunderbird Add-ons Manager (do not unpack it)

**Comment by RealRaven2000** [comment]
Here is the latest version with additional performance fixes. 

- avoids unnecessary category operations when a Thunderbird tab is clicked - #279 is still WIP
- improved the new profiling functions that log how long certain operations take

[QuickFolders-mx-5.11pre48.zip](https://github.com/RealRaven2000/QuickFolders/files/9111970/QuickFolders-mx-5.11pre48.zip)

to install this optimized version, download the zip file and then drag the zip file into Thunderbird Add-ons Manager (do not unpack it)

**Comment by RealRaven2000** [comment]
> can confirm version 5.11pre48 runs on TB 103 beta 5 also very smooth.

Good to know - do you know roughly how many folders your folder tree has?

**Comment by cbroult** [comment]
I also confirm that with 5.11pre48 Thunderbird 102.0.2 slowness has drastically been reduced despite the large number of folders I have. Thank you for that version.

**Comment by RealRaven2000** [comment]
Latest patch (includes categories fix)

[QuickFolders-mx-5.11pre77.zip](https://github.com/RealRaven2000/QuickFolders/files/9127568/QuickFolders-mx-5.11pre77.zip)

As always - to install this preview, download the zip file above and drag it into Thunderbird Add-ons Manager. (Do not unpack the folder or the install will fail).

**Comment by fanis** [comment]
Came here for the same slowdown issue in latest TB 102.0.3 - installed latest Quickfolders 5.11pre77 and slowdown is no more. Good job, @RealRaven2000.

**Comment by RealRaven2000** [comment]
> Came here for the same slowdown issue in latest TB 102.0.3 - installed latest Quickfolders 5.11pre77 and slowdown is no more. Good job, @RealRaven2000.

Nice. if you are having trouble with categories (which may also lead to invisible tabs) remember to have a look at issue #279 - this can lead to no tabs being shown. All these issues will be rolled into the next official release 5.11

**Comment by mscag** [comment]
Hi,
Does that mean we can now safely revert back the "extensions.quickfolders.folderTree.icons = false" modification after Pre77, or should we wait for the official update ?
Regards.

**Comment by RealRaven2000** [comment]
> Hi, Does that mean we can now safely revert back the "extensions.quickfolders.folderTree.icons = false" modification after Pre77, or should we wait for the official update ? Regards.

yes you can revert this now, there won't be a significant difference in speed (if any) with this. I believe more performance improvements are possible downstream, but they may have to be partially provided by changes in Thunderbird Core code...

**Comment by RealRaven2000** [comment]
I removed an unnecessary call to the function `repairTreeIcons()` on startup (which goes through all tree elements one additional time) to save on processing time in Thunderbird 102.

[QuickFolders-mx-5.11pre113.zip](https://github.com/RealRaven2000/QuickFolders/files/9173835/QuickFolders-mx-5.11pre113.zip)

If you have custom icons in the tree, please check if they still work after installing this version.

**Comment by RealRaven2000** [comment]
Implemented in 5.11 - Published 23/07/2022

**Comment by RealRaven2000** [comment]
I am going top reopen this because I believe there is more work that can be done here. My first measure will be to create more profiling options to get proper measurements. I feel just disabling the Folder tree (with F9) before restart makes a noticeable speed difference, but I want the figures to back this up.

**Comment by RealRaven2000** [comment]
Added more performance measurements and removed some spammy messages generated by `nsIMsgFolder.getStringProperty()` unnecessarily throwing exceptions when a string property doesn't exist.

[QuickFolders-mx-5.11.1pre10.zip](https://github.com/RealRaven2000/QuickFolders/files/9190748/QuickFolders-mx-5.11.1pre10.zip)

You can enable  `extensions.quickfolders.debug.performance = true` by right-clicking the debug mode checkbox and then filter the relevant messages by entering "took:" in the search box

![image](https://user-images.githubusercontent.com/6314674/181037096-f15e88bb-c059-496f-a720-c52d4ac2deb2.png)

**Comment by ctft1** [comment]
Hi, I stopped temporarily using QuickFolders after my upgrade to TB 102, because of the slowing down described in this thread. I tried again today with the following (latest stable) versions to check if it was better :
 - Thunderbird 102.1.0 (64-bit)
 - QuickFolders 5.11

The global lag while using TB is gone (thank you!), but I still have one issue with unread messages: opening an unread message (displaying the message content in the appropriate pane) takes 2-4 seconds. This only happens with unread messages, not already read messages...

Additional info:
 - My TB is quite huge (10+ POP accounts, 25+ GB data, 1500+ folders)
 - Disabling QuickFolders solves this issue.

Is that related to the same issue in this thread?

Thank you!

**Comment by RealRaven2000** [comment]
> The global lag while using TB is gone (thank you!), but I still have one issue with unread messages: opening an unread message (displaying the message content in the appropriate pane) takes 2-4 seconds. This only happens with unread messages, not already read messages...
> 
> Additional info:
> 
> * My TB is quite huge (10+ POP accounts, 25+ GB data, 1500+ folders)
> * Disabling QuickFolders solves this issue.

that's a strange one - I am experiencing some delay opening messages (with a similar messages size, the backup of the complete profile is 28GB, and I have about 1450 folders across about 12 accounts, most are POP, some without connection to a server because legacy mail) but it is independent of whether read or unread, and it is persistent even if I disable QuickFolders.

QuickFolders uses "`setTimeout`" to update the unread mails count on the tabs when it changes in a folder but it shouldn't impact on the display of the email as it is not done immediately - but by default 500ms later. You can trace opn what is happening by enabling debug mode and the setting `extensions.quickfolders.debug.interface.update = true` via right-click on debug mode:

![image](https://user-images.githubusercontent.com/6314674/182023230-d5cdaad6-10ff-4fdc-ad66-7d3ba61bb3ab.png)

Here is a typical expected output from error console when the unread count changes in a folder:

```
QuickFolders 12:7:22.220  [10504 ms]   
 setFolderUpdateTimer(item):Inbox quickfolders-util.js:1155:13
QuickFolders 12:7:22.221  [1 ms]   
 Folder Tab Select Timer ID: 31384 quickfolders-util.js:1155:13
QuickFolders 12:7:22.221  [0 ms]   
 Setting Update Timer (after timer 31302 expired), new Timer: 31384 quickfolders-util.js:1155:13
QuickFolders 12:7:22.222  [1 ms]   
 util.touch(Inbox)
1659265642
31/7 12:7:22 quickfolders-util.js:1155:13
QuickFolders 12:7:23.725  [1503 ms]   
 updateFolders(rebuildCategories: false, minimal: true) - Number of Folders = 251 quickfolders-util.js:1155:13
QuickFolders 12:7:23.918  [193 ms]   
 28 of 251 tabs refreshed on toolbar [minimalUpdate]. quickfolders-util.js:1155:13
```


The setting for the delay can be changed in `extensions.quickfolders.queuedFolderUpdateDelay`

**Comment by ctft1** [comment]
Good point, that seems to be the case only for folders that have a lot of subfolders inside! To sumup:
 - 1 folder with no subfolder or a few ones: preview display is immediate
 - 1 folder with a lot of subfolders: preview display of unread message takes 2-4 seconds

I will try to enable the debugging and check activity to get back with more data.

**Comment by RealRaven2000** [comment]
> Good point, that seems to be the case only for folders that have a lot of subfolders inside! To sumup:
> 
> * 1 folder with no subfolder or a few ones: preview display is immediate
> * 1 folder with a lot of subfolders: preview display of unread message takes 2-4 seconds
> 
> I will try to enable the debugging and check activity to get back with more data.

also does it only happen on the first unread message in the folder (so when you change to the folder) or on other unread messages in the same folder, again and again?

**Comment by ctft1** [comment]
It happens for each unread message, even if no folder change
It also happens if a message is read, then "set unread", and read it again (that helps for the diagnosis, as we don't need to send new mail each time)

**Comment by ctft1** [comment]
Ok I tried in the Inbox folder, it's even worst as it's the main "super folder"... around 30 seconds before displaying an unread message

Some logs :

QuickFolders 14:43:56.743  [32636 ms]   
 util.touch(Inbox)
1659271436
31/7 14:43:56

QuickFolders 14:44:28.900  [32157 ms]   
 Persisted tab category: __ALL quickfolders-util.js:1155:13
QuickFolders 14:44:28.901  [1 ms]   
 Persisted tab category: undefined quickfolders-util.js:1155:13

**Comment by ctft1** [comment]
![QuickFoolders log](https://user-images.githubusercontent.com/95131518/182027335-4b2d5849-be57-46d0-ba82-ea0264e032f5.png)

Some other logs on an intermediate folder (having a bunch of subfolders)

**Comment by ctft1** [comment]
And last information that could be useful: when changing folder, the first message is "slow" to display (acctually depending on how many subfolders are in the folder we are viewing... the more subfolders the slowest), but this time whatever the read status is (read or unread)

After the first message is displayed, everything is smooth.

Disabling QuickFolders solves this issue (immediate display)

**Comment by RealRaven2000** [comment]
I have discussed the issue of slow folder iteration on the Add-on developer call. I think the long term (or even short term) solution will be to iterate the complete folder tree once (e.g. on start up) and then keeping a cached version around; this would greatly improve the speed as it wouldn't need to iterate all accounts when doing a global search or creating recent folders lists. 

It would however make it necessary to constantly update the cached copy whenever there are modifications in the folder structure (renaming / removing / creating folders). This could be implemented using the API instead of legacy code and the data could then be persisted in local storage for the next restart of Thunderbird. I will try to write some experimental code for this next week. I would expect another cut in processing time by around 50% or more.

**Comment by jaysmithgit** [comment]
Regarding "solution will be to iterate the complete folder tree once (e.g. on start up)" please keep in mind that there are installations with...

a) Many thousands (even tens of thousands) of folders and a folder tree structure at least 8 levels deep (and perhaps more).

b) Potentially connection to IMAP server(s) that may be on slower-than-desirable connections or the server(s) may be temporarily slow for some reason.

c) Such iteration should **only** record the existence of the folder, not its status (count, read vs unread, etc.).  Trying to report that level of detail would surely cause TB to crash unless TB has been greatly improved.  [I don't yet use the latest TB version, and I have not yet accidentally done it in the 78.7.1 version that I do use, but in versions prior to 78.7.1, an accidental "Compact All" command would eventually -- after an hour or two of running doing the compacting of thousands of folders, 8 levels deep, containing many tens of thousands of emails -- cause TB to crash.  It is not pretty.  If the iteration being discussed were to do that, TB would become unusable because **for me** TB would probably never actually start up before it crashed.

As you will recall, the iteration you seem to be describing is something that I have been asking for since day one (because otherwise, at least at the time, all the folders (local and on IMAP) were **not** visible to TB thus **not** visible to QF if they had not been **manually** "exposed" by opening each folder that contains folders, but now there seems to be a broader need for it. **On TB 78.7.1 that is still a problem** -- if another user on our IMAP system adds a folder (within a folder), it is not visible to me until I manually open the folder that contains the added folder.

WHAT I WOULD PROPOSE -- if the process turns out to take longer than a couple minutes -- is that, instead of automatically starting the iteration on either TB or QF startup -- present the QF user with a notice/dialog box explaining that some/many/most folders may not be visible until the iteration has been done, warning the user about how long it may take (if that turns out to be an issue), and to give the user an option of WHEN to do the iteration (either by clicking "Iterate Now" or perhaps allowing the user to set a date/time when to do the iteration, such as overnight).

I am concerned that TB with QF installed may **seem** impossibly slow on startup and the user may not understand why. Especially if TB is connecting to remote IMAP systems that might be slow sometimes.  Once the user is caught in that loop, the user may not understand that TB is perfectly fine -- it is the QF which is launching a process which is slowing things down. And when the user starts TB, QF starts automatically and potentially automatically starting the iteration process, not giving the user the option to understand (or change) what is happening.

So... I am all for doing this iteration, but be sure that the user remains in control of the "when" and that the user is fully informed.

**Comment by RealRaven2000** [comment]
> a) Many thousands (even tens of thousands) of folders and a folder tree structure at least 8 levels deep (and perhaps more).
 
I am aware of this, and that's exactly what QF iterates when you type in the search field, every time at the moment. The proposal is to iterate it ONCE in a session or even just ONCE and then store forever and update "stale" / "changed" parts dynamically.

> b) Potentially connection to IMAP server(s) that may be on slower-than-desirable connections or the server(s) may be temporarily slow for some reason.

I know, I need a nice routine that can maybe break this down into chunks to do it in the background. Even if it takes a few minutes processing time for the very first time, when ever folders need to be iterated to:

- show contained folders submenus
- iterate folders to find out the MRU time (recent folders)
- trying to find a matching folder name / pattern

the operation would just use a flat list instead, and in most cases would not  need to access the original folders. (For recent folders this may still be necessary, but the MRU times could be updated in place in the cached tree instead)

> c) Such iteration should **only** record the existence of the folder, not its status (count, read vs unread, etc.). Trying to report that level of detail would surely cause TB to crash unless TB has been greatly improved.

Definitely. I wouldn't propose to save any such full information - as a minimum I a folder record could contain:

- account id
- relative folder path
- URI
- prettyName
- [MRUtime} (?)

any other information could be resolved directly from the folder (by resolving folder URI) but only for a subset of them. (e.g. folders containing unread mail, folders containing folders with unread mail) - I am using some built in functions to retrieve this data already. The goal is to only retrieve this information where it is absolutely necessary.

For example to update the unread mails count on the **currently visible QuickFolders tabs**, I may have to use the actual folders, but that won't be thousands of accesses into the folder tree.

> WHAT I WOULD PROPOSE -- if the process turns out to take longer than a couple minutes -- is that, instead of automatically starting the iteration on either TB or QF startup -- present the QF user with a notice/dialog box explaining that some/many/most folders may not be visible until the iteration has been done, warning the user about how long it may take (if that turns out to be an issue), and to give the user an option of WHEN to do the iteration (either by clicking "Iterate Now" or perhaps allowing the user to set a date/time when to do the iteration, such as overnight).

> I am concerned that TB with QF installed may seem impossibly slow on startup and the user may not understand why. Especially if TB is connecting to remote IMAP systems that might be slow sometimes. Once the user is caught in that loop, the user may not understand that TB is perfectly fine -- it is the QF which is launching a process which is slowing things down.

Remember that you currently already experience this delay when you type the first letter in the quickMove box. It shouldn't be any worse than that. Once it is done, the information can be persisted in local storage and reused when Thunderbird is restarted. So it doesn't have to be created from scratch every time Thunderbird starts.

Also, QuickFolders can show its tabs instantly even if the folder tree hasn't been fully iterated - it's only a subset of folders (e.g. 100) but it could be used to populate the submenus from Cache once the list is complete. This will especially be helpful when using drag+&+drop  (currently I build cached popup menus for this purpose, but they need to be frequently updated based on portions of the "real" folder tree, which again may lead to sluggishness)

In an ideal world, Thunderbird would cache the folder tree itself and gives us fast results transparently on any consecutive account / folder iterations, but they don't seem to have that problem so much as they must have a clever way of populating the folder tree dynamically. I haven't currently looked into the Detail for this,

**Comment by jaysmithgit** [comment]
Great! It sounds like you have considered all aspects. Thanks for considering and possibly implementing this.

FYI: On "ancient" TB 78.7.1 with QG 5.9pre33, folders within folders are not visible (on TB or with QF) until on TB I manually open the folder that contains them.  I don't know if that has been improved in more modern TB versions.

A couple thoughts about updating the local cache (with newly added -- or removed -- folder information)... based on experiences with other types of software...

- The Filezilla SFTP program, when doing a transfer, at least from a local system to a remote system, seems to "just know" if a higher level directory contains new/different/removed directories and files when comparing the local system to the remote system.  There is a 3000-file directory structure that I regularly upload to a remote system. The second level of that directory structure has four directory "branches" (each containing many more directories and/or files, several levels deep). If I have made a change to only one file, thus in only one of those four branches, the program ONLY deals with that one branch and does not even visibly seem to do compares within the other branches.  (But within the branch it is comparing, it compares all the directories and files.) The method it uses to know whether a branch contains changes could be useful.

- The general linux rsync program seems to do something similar. Perhaps there is a useful method or technique within that.

**Comment by RealRaven2000** [comment]
I just found this related issue that also affects speed of the "Quick folder move" extension by Philip Kewisch:

https://bugzilla.mozilla.org/show_bug.cgi?id=1773822#c10

the quote from the linked comment is particularly enlightening as it also explains frequent messages on my system that fail to move mails due to inaccessible folders when Thunderbird starts (caused by filter rules running automatically). 

> GetStringProperty is called from the add-on on all folders :-(
https://github.com/kewisch/quickmove-extension/blob/1774546923c4667fc93096a6ff4e3a04a6269bec/src/content/quickmove.js#L288

> This is a little surprising since using QFM in TB 91 didn't usually cause an MSF exodus. As stated in [comment #8](https://bugzilla.mozilla.org/show_bug.cgi?id=1773822#c8), it's also much slower these days, perhaps the slowness comes from deleting 800 files from the system. So some backend changes have led to databases not being closed any more.

Calling getStringProperty() on a native property like MRUTime shouldn't cause such destructive behavior - but if destructive Cache invalidation as described may be caused by read accessing  folder properties such as message counts it would certainly explain slow downs with QuickFolders a lot. 

Related bug: #284

**Comment by hannesdorn** [comment]
On my computer message preview is slow. Even if I just use only quick folders addon and no other addons.
Windows 10, TB 102.1.1, QF 5.11.

**Comment by RealRaven2000** [comment]
Important related bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1776280

This will likely be uplifted to ESR102.

**Comment by RealRaven2000** [comment]
> On my computer message preview is slow. Even if I just use only quick folders addon and no other addons. Windows 10, TB 102.1.1, QF 5.11.

Slow here as well on Tb102.1.1, even with QuickFolders disabled.

**Comment by hannesdorn** [comment]
> > On my computer message preview is slow. Even if I just use only quick folders addon and no other addons. Windows 10, TB 102.1.1, QF 5.11.
> 
> Slow here as well on Tb102.1.1, even with QuickFolders disabled.

TB needs a restart after disabling the addon.

**Comment by RealRaven2000** [comment]
> > > On my computer message preview is slow. Even if I just use only quick folders addon and no other addons. Windows 10, TB 102.1.1, QF 5.11.
> > 
> > 
> > Slow here as well on Tb102.1.1, even with QuickFolders disabled.
> 
> TB needs a restart after disabling the addon.

I tried this too, but I still had the delay. however, disabling the Add-on "Display Mail User Agent" removed the delay. That one injects the user agent icon into the email itself and could probably be coded in a different way (maybe asynchronously) to avoid the delay. I am not aware of any such scripts in QuickFolders but I may keep looking.

**Comment by RealRaven2000** [comment]
Latest version:

[QuickFolders-mx-5.12pre43.zip](https://github.com/RealRaven2000/QuickFolders/files/9334105/QuickFolders-mx-5.12pre43.zip)

there are some minor changes with using `getStringProperty()` more cautiously to avoid folder invalidation. I am still hoping on the patch for bug 1776380 langing in 102 soon.

**Comment by ilNebbioso** [comment]
> Latest version:
> 
> [QuickFolders-mx-5.12pre43.zip](https://github.com/RealRaven2000/QuickFolders/files/9334105/QuickFolders-mx-5.12pre43.zip)
> 
> there are some minor changes with using `getStringProperty()` more cautiously to avoid folder invalidation. I am still hoping on the patch for bug 1776380 langing in 102 soon.

Ciao!
I just jumped here because I'm too experiencing slowdown with TB 102.1.2 + QF 5.11.

QF 5.12pre43 seems to have solved its issues: I immediately found benefits using it. In case, I'll come back here,

Thank you!

**Comment by RealRaven2000** [comment]
> Ciao! I just jumped here because I'm too experiencing slowdown with TB 102.1.2 + QF 5.11.
> 
> QF 5.12pre43 seems to have solved its issues: I immediately found benefits using it. In case, I'll come back here,
> 
> Thank you!

Nice one - _Molto Grazie_ for the feedback. I think the main issue is still the "recent folders" item that's quite slow (#284), If you use quickMove / quickJump you can use the `=` key there for a faster result.

**Comment by ilNebbioso** [comment]
> > Ciao! I just jumped here because I'm too experiencing slowdown with TB 102.1.2 + QF 5.11.
> > QF 5.12pre43 seems to have solved its issues: I immediately found benefits using it. In case, I'll come back here,
> > Thank you!
> 
> Nice one - _Molto Grazie_ for the feedback. I think the main issue is still the "recent folders" item that's quite slow (#284), If you use quickMove / quickJump you can use the `=` key there for a faster result.

I confirm you the "Recent folders" issue on TB 102.1.2 + QF 5.12pre43. But it isn't so long, here.

**Comment by avegaweiss** [comment]
I've skiping lasta thunderbird updates because of this.
Just try the new 102.2 version. Same problem (too slow), but somehow google provide an answer.

After clearing thunderbir cache, performances was normal again
Prese Ctrl-Shift-Delete, selecte 'Everithing'

Hope it works .

**Comment by RealRaven2000** [comment]
Thunderbird 102.2 appears to have solved all my performance problems: the recent folders popup isn't slow anymore. I believe Thunderbird finally fixed some issues that lead to folder Cache invalidation (in Windows throwing errors from iterated folders would open more than 250 file handles and cause performance problems)

**Comment by hspindel** [comment]
Just want to report that with the latest Thunderbird/QuickFolders it is now very speedy.

**Comment by ctft1** [comment]
Same here, fixed !

**Comment by cbroult** [comment]
Great job in getting the performance issue fixed: Thunderbird/QuickFolders is again usable. Thank you very much.

**Comment by RealRaven2000** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1778888

I think most of the credit goes to the Thunderbird Crew, they fixed the underlying issue in Tb 102.2 - quite happy they listened to my input on this.

**Comment by cbroult** [comment]
The Thunderbird team did a great job fixing that performance issue, and you also did great by being persistent and convincing, so they took care of it.

**Comment by wsmwk** [comment]
Yes. Focused, productive approaches bear fruit again.

**Comment by RealRaven2000** [comment]
Please check out the latest update from Thunderbird.

[Update-Info from Mozilla](https://www.thunderbird.net/en-US/thunderbird/102.2.2/releasenotes/): Version 102.2.2, first offered to channel users on September 7, 2022

- fixed: Accessing mail folders in profiles with many folders was slow

![image](https://user-images.githubusercontent.com/6314674/189089649-acfc1889-019f-403f-8398-a9c2cba5da2b.png)

I am still searching for the related bugzilla bug.

**Comment by wsmwk** [comment]
> I am still searching for the related bugzilla bug.

[Bug 1788901 - Folder property caching handles missing properties badly: Re-instate code from bug 1726319 and bug 1776280 removed in bug 1778888](https://bugzilla.mozilla.org/show_bug.cgi?id=1788901)

**Comment by RealRaven2000** [comment]
> > I am still searching for the related bugzilla bug.
> 
> [Bug 1788901 - Folder property caching handles missing properties badly: Re-instate code from bug 1726319 and bug 1776280 removed in bug 1778888](https://bugzilla.mozilla.org/show_bug.cgi?id=1788901)
If I recall correctly I only found the actual information somewhere in phabricator (and not on bugzilla).
