### ISSUE TITLE
Quickfolders closed

### ISSUE THREAD

**Issue by Ciuciuca** [RealRaven2000/QuickFolders#286]
QF closed at 2-3 minutes by Thunderbird 91.11.0 (32-Bit), when i  switch on/off it come back for little pic time

**Comment by RealRaven2000** [comment]
can you give more detail - what is "little pic time"? When you say "QF closed" do you mean the toolbar is removed?

IF QF works / is shown after startup, head on to the error console (Cltr+Shift+J), reset the contents and then wait whether it happens again - you can capture the log with right-click menu.

**Comment by RealRaven2000** [comment]
Do you still have the problem? More detail might be helpful/
