### ISSUE TITLE
Drag & Drop does not open sub folders on tab anymore (QF 5.11)

### ISSUE THREAD

**Issue by reinerblock** [RealRaven2000/QuickFolders#288]
When trying to copy or move messages by Drag & Drop over tab does not open the sub folders list anymore on QF 5.11 and TB 91.11.0.

![grafik](https://user-images.githubusercontent.com/5745579/181229123-68a04959-67af-4fc6-904e-5a45ae990e70.png)

**Comment by RealRaven2000** [comment]
works for me here in 91.11:

![image](https://user-images.githubusercontent.com/6314674/181252197-1682de07-ce20-4d20-84dc-58f6d7f14c51.png)

takes a little while for the very first one to appear. The dropdown menus are generated (cached) when QuickFolders starts up. Are there errors in JS error console (Ctrl+Shift+J)

What happens (in error console) if you enable "Debug mode" on QF advanced settings?
Can you also enable `extensions.quickfolders.debug.performance=true` via right-click?

![image](https://user-images.githubusercontent.com/6314674/181252760-b696a3fa-1441-4360-a5dc-df4f6b74536a.png)

**Comment by RealRaven2000** [comment]
To get a meaningful error log, you should enable these three options (errors, Warnings, Logs). You can also disable content and time stamps for a cleaner / easier to read output:

![image](https://user-images.githubusercontent.com/6314674/181256356-370c00e5-5047-42fe-a9ee-a5e3a8a059e1.png)


you can copy the complete log via right-click on any message:

![image](https://user-images.githubusercontent.com/6314674/181256151-c741ca00-6b3f-47fb-9358-e8485f5f71e7.png)

_Export visible messages to Clipboard_

**Comment by reinerblock** [comment]
I don't know what happened. After the above comments, I restarted TB, and now it works.

Sorry! The only thing I can think of is that somehow during the last start of TB there were some problems during the initialization of the installed add-ons.
