### ISSUE TITLE
Documentation: "Pimp my tabs" should be "Bling my tabs"

### ISSUE THREAD

**Issue by neilkatin** [RealRaven2000/QuickFolders#29]
There's a small typo on the [faq+tips](http://quickfolders.org/faq_tips.html) page.

In the "I can see no colors..." entry, when expanded, it says:

> In Options, on the "Pimp my Tabs" page...

The page is now called "Blink my Tabs!", and the options seem to be different than described in the FAQ.

Not a big deal, but confusing to first timers.

**Comment by RealRaven2000** [comment]
Thanks for reporting, I updated it and also the [bugs](http://quickfolders.org/bugs.html) / [troubleshooting](http://quickfolders.org/support.html) pages by removing references to console2 and updating with fresh screenshots. 

If you find any other issues on the support site, feel free to append them below.
