### ISSUE TITLE
Bitdefender reports Trojan.GenericKD.61174424 in AppData\Roaming\Thunderbird\Profiles\33x63f18.default\extensions\implementation.js

### ISSUE THREAD

**Issue by Foxfan100** [RealRaven2000/QuickFolders#294]
Bitdefender reports this as noted in post title. Malwarebytes and Windows Defender scans do NOT report a trojan or otherwise.

OK to disregard/mark OK in Bitdefender or any other AV programs?

**Comment by RealRaven2000** [comment]
It's a false positive - reported by 4 of the vendors based on bad search patterns - please try the version I posted at #295

Markins as duplicate - please comment over there especially if the new version is still flagged.
