### ISSUE TITLE
Some Antivirus report false positives about Trojan infections.

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#295]
If you are affected by this issue, try this replacement version:

[QuickFolders-mx-5.11.1pre15.zip](https://github.com/RealRaven2000/QuickFolders/files/9275009/QuickFolders-mx-5.11.1pre15.zip)

to install, download the zip file - feel free to scan for viruses to make sure there are no more detections - then drag the file into Thunderbird Add-ons Manager (without unpacking it)

**Comment by pmruzicka** [comment]
So I start my computer today and now the QuickFolders Assistant button doesn't work. Going to try to reboot.

**Comment by RealRaven2000** [comment]
> So I start my computer today and now the QuickFolders Assistant button doesn't work. Going to try to reboot.
> 
> Rebooted. Button still not working.

I think you mean quickFilters assistant?
