### ISSUE TITLE
Feature request: mark messages READ in folder and all its subfolders tree "in one click"

### ISSUE THREAD

**Issue by stayen** [RealRaven2000/QuickFolders#3]
Hello,

As mentioned in thread in tb-planning@ mailing list, I post the feature request here: ability to mark messages in IMAP folder and all its subfolders tree "in one click".

Thanks.

**Comment by RealRaven2000** [comment]
Thanks for the suggestion, I assigned myself to it. I have some important Thunderbird 68 fixes lined up for the next release 4.16 but I will definitely land the feature in the following release (or maintenance release 4.16.1)

I will post some test versions here.

**Comment by RealRaven2000** [comment]
I changed the title (I think you were missing the keyword "READ") - also we might not need to restrict this to just IMAP folders; might as well give the function to POP users, too. However, I suggest that I add a confirmation message [Are you Sure?] just to avoid problems if somebody accidentally clicks the wrong menu item. Setting everything from unread to read may be quite disruptive to some users, and cannot be easily undone.

**Comment by RealRaven2000** [comment]
Here is a trial version. You have to enable the new command on the QF Settings / Advanced tab:
![image](https://user-images.githubusercontent.com/6314674/71519509-b63c1480-28af-11ea-89e8-9d9f7a34004b.png)

I decided to hide this by default and to not add a "are you sure?" confirmation. If you decide to have this command, then you will be able to use it responsibly,

[QuickFolders-wx-4.17.5pre23.zip](https://github.com/RealRaven2000/QuickFolders/files/4005430/QuickFolders-wx-4.17.5pre23.zip)

**Comment by RealRaven2000** [comment]
Implemented in 4.17.5 released on 27/12/2019
