### ISSUE TITLE
Feature request: move message to a specific folder

### ISSUE THREAD

**Issue by neilkatin** [RealRaven2000/QuickFolders#30]
Right now there is an accelerated 'open specific folder': ALT-number, where number is displayed on the folder in the bar (with the right option setting).

There is a quickmove, which moves the selected messages, but the folder has to be selected each time (with a last-folder pre-selected option).

I find myself moving messages much more than opening folders; I'd like a key sequence to move a message to a specific folder in one modifier+key press.

I'm happy if its shift-alt-number matching the open folder model.  I'm OK if the accelerator is settable on a per-folder basis.

And ideally I'd love to make the "move" the simpler alt-number one, and open the shift-alt-number (or whatever modifier).

**Comment by RealRaven2000** [comment]
Did you test Alt+Shift+Number? Make sure you have this option enabled:

![image](https://user-images.githubusercontent.com/6314674/79156417-bf071680-7dca-11ea-8270-2571c10dd2be.png)

**Comment by RealRaven2000** [comment]
See also issue #6

**Comment by neilkatin** [comment]
I agree, duplicate of #6.  Is the alt-shift behavior documented anywhere?  I didn't notice it.
