### ISSUE TITLE
After disabing and then reenabling Quickfolders, folders containing a blank in the name are reported as broken

### ISSUE THREAD

**Issue by stolp** [RealRaven2000/QuickFolders#305]
Quickfolders Version: 5.12.1
Thunderbird Version: 102.2.1

I had around 50 quick folders active when I decided to disable and later reenable the add-on.

Upon reactivation all Quickfolders containing a blank in the name are reported as broken, although the folder structure was never touched.

This is really annoying as I had to re-add all folders again.

![QuickFolders_2022-09-02_15-48-51](https://user-images.githubusercontent.com/522940/188276572-728bdf6f-d50d-4f71-88a3-4054871aa734.png)

**Comment by RealRaven2000** [comment]
Can be fixed very quickly without adding all folders manually again. The reason for this is Thunderbird changing their shit without telling the Add-on. These cause that (in some profiles):
[bug 1483485](https://bugzilla.mozilla.org/show_bug.cgi?id=1483485) 
[bug 1573690](https://bugzilla.mozilla.org/show_bug.cgi?id=1573690)

The detail is explained in #281

1st step - Just try to export and import your tabs:
![image](https://user-images.githubusercontent.com/6314674/188285090-f22eb951-edfe-4f1a-af98-ae6c85f5123c.png)

If that doesn't work you can either edit the exported configuration yourself or send it to me offline. We will need the info of the affected accounts.

For each account that has tab hold down SHIFT and click on the tools menu, then select "debug / copy current folder info!"

![image](https://user-images.githubusercontent.com/6314674/177572157-fa9d624b-8eea-4c89-8b85-cf0e575eaf1c.png)

this will copy the faulty URI and account information for the tab into the clipboard, for example:

```
QuickFolders Tab: [my foldername]
account: account1
URI: imap://thunderbirddaily67%wef40gmail.com@imap.gmail.com/addons/quickfolders/my folder
```

the first part of the URL  "thunderbirddaily67%wef40gmail.com@imap.gmail.com" is userName@hostName and was most likely changed by Thunderbird and will be different from the URIs in the QuickFolders export. Once you can match the account number it's very easy to change all paths in the export file accordingly and then reimport.

**Comment by stolp** [comment]
Thank you for your detailed answer.

Luckily I had a recent export of the tabs and changed the URIs according to your instructions.

As it turned out, some of the URIs contained the working host name while others an alias name of that host, which gave errors upon reactivation. I probably have changed the imap host name in the past, I consider this the cause of the problem.

Thanks again for the great support, I will definitely extend my license because of this experience.

**Comment by RealRaven2000** [comment]
> Thank you for your detailed answer.
> 
> Luckily I had a recent export of the tabs and changed the URIs according to your instructions.
> 
> As it turned out, some of the URIs contained the working host name while others an alias name of that host, which gave errors upon reactivation. I probably have changed the imap host name in the past, I consider this the cause of the problem.

This is correct - Thunderbird made that change on their side and simply threw away the original setting hostName and userName (which may have been aliases, and part of the old URIs). QuickFolders saved the account# as a precaution and is able to match the rest of the URI string when you import.
