### ISSUE TITLE
New Function: mark folder as read and jump to next unread folder

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#320]
In my own daily usage this combined function will prove useful for some of my news subscriptions where I only read mails selectively. Sometimes I have time to read 3 or 4 daily mails, sometimes I just want to skip and move on.

This could be first implemented by using the CTRL modifier key while clicking the "mark thread as read and go next". Sort of augmenting that for the whole folder.

![image](https://user-images.githubusercontent.com/6314674/196035310-c464c46a-b1b6-4ad6-a09a-a0de2faadd96.png)

I could also imagine an augmented shortcut `CTRL`+`T` for this operation. (Based on `T` for mark thread)

**Comment by RealRaven2000** [comment]
Test version:

[QuickFolders-mx-5.13.2pre37.zip](https://github.com/RealRaven2000/QuickFolders/files/9794734/QuickFolders-mx-5.13.2pre37.zip)

Hold down the `Ctrl` key while clicking the "Mark Conversation as Read and jump to next unread Email" button.

**Comment by RealRaven2000** [comment]
Implemented in 5.14 - Published 14/11/2022

**Comment by fanis** [comment]
Looks good, already using it. Please consider adding the keyboard shortcut you suggested, even better if behind a changeable option.

**Comment by RealRaven2000** [comment]
> Looks good, already using it. Please consider adding the keyboard shortcut you suggested, even better if behind a changeable option.

Will do, it's just hard to decide on the correct one as a default... Ctrl+Shift+S  ("skip, but on steroids") or Ctrl+Shift+T ("mark thread as read, but on steroids") ?

**Comment by fanis** [comment]
Ctrl+Shift+T reopens a closed tab by default I believe.
Mark All Read in current view is "Shift + C" so maybe Ctrl + Shift + C?

**Comment by RealRaven2000** [comment]
> Ctrl+Shift+T reopens a closed tab by default I believe. Mark All Read in current view is "Shift + C" so maybe Ctrl + Shift + C?

I didn't even know! that would make a lot of sense in that case.
