### ISSUE TITLE
Jump to Folder does not work when Tb is in "Unread Folders" "Compact View

### ISSUE THREAD

**Issue by RobertvanderHulst** [RealRaven2000/QuickFolders#323]
Jump to Folder (Shift J) does not work when Tb is in "Unread Folders" "Compact View" mode.
This problem existed before and has come back.
QF 5.14
TB 10.2.4.2
Mac OS

**Comment by RealRaven2000** [comment]
It works for me... are you sure your keyboard focus is on either of the following screen elements of the 3-pane window:

- one of the folders in the tree
- one of the emails / conversations in the list of emails
- in the preview area of an email

When does the shortcut not work? (pay attention what screen element you clicked just before using the shortcut)

- If you are in a text box / editable field. I think this would also include if you use the editor of the conversations Add-on.
- If you are in a search box (e.g. the quick filter area) - one of my bugfix makes sure that using `Shift`+(Any Key) when entering a filtered search won't accidentally trigger moving emails.

**Comment by RobertvanderHulst** [comment]
I am not sure what happened. Tb is 102.5.0 now and it works.
