### ISSUE TITLE
[Create Option to] make QuickFolders appear at the Bottom of Other Toolbars

### ISSUE THREAD

**Issue by gh658804** [RealRaven2000/QuickFolders#34]
After the latest update to 4.18, Quickfolders now appears above the mail toolbar. At first i didn't understand that, it looked as if the mail toolbar had been hidden. Couln't find an option to restore the previous order.

**Comment by RealRaven2000** [comment]
I believed the toolbar underneath the QF toolbar is the default behavior - for now, you can change a configuration setting:

`extensions.quickfolders.toolbar.ordinalPosition = 100`

this will "push down" the QuickFolders toolbar below the mail toolbar.

- To set this, go to Thunderbird Options Tb Menu Tools / Options), then click on the Advanced tab (bottom left). Find the config editor at the bottom right and click it:

![image](https://user-images.githubusercontent.com/6314674/83851129-d77c1900-a709-11ea-9221-d805c3490689.png)


- In the search box, paste the string `quickfolders.toolbar.ordinalPosition`
- Right-click and select Modify:
- Enter the value `100`:
![image](https://user-images.githubusercontent.com/6314674/83851281-07c3b780-a70a-11ea-8e05-a43d154064df.png)
- Click OK, then go back to the mail tab (first tab on the left) or close the options tab.
- Click the blue tools icon on the QuickFolders toolbar, and execute "Refresh Visible Tabs":
![image](https://user-images.githubusercontent.com/6314674/83851335-1ad68780-a70a-11ea-8e1d-730c1b8cd755.png)

The QF toolbar should now move down to the desired position.

**Comment by gh658804** [comment]
It worked, thanks.

I must note however that since i installed QuickFolders, it appeared below the mail toolbar...

**Comment by RealRaven2000** [comment]
I propose to change the default value to 100 for now but I would also like to show an edit box in advanced settings. See also issue #20

**Comment by gh658804** [comment]
Yup, it would be nice to be able to change that from Options.

**Comment by RealRaven2000** [comment]
Here is a trial version with a GUI for the new option on the Advanced tab:

![image](https://user-images.githubusercontent.com/6314674/83895061-17fb8700-a74a-11ea-8d85-040df0ccd886.png)

please unpack and then drag the contained xpi file into Thunderbird's installed extensions list

[QuickFolders-wx-4.18.1pre5.zip](https://github.com/RealRaven2000/QuickFolders/files/4736982/QuickFolders-wx-4.18.1pre5.zip)

set the value to 100 to move the toolbar to the bottom, 0 for on top of other toolbars. Default is now bottom again.

**Comment by RealRaven2000** [comment]
Fixed in release 4.18.1 - published today (07/06/2020).

**Comment by fredstluka** [comment]
Good feature!  I prefer 0 myself.  It would be good to add info about 0 being the top, 100 being the bottom.  I had to find my way to this ticket to re-read the explanation when 1 didn't do what I wanted.  Perhaps as a popup tooltip on the text field where I type in the value?  Hmm...  Just checked.  The popup tooltip is already there.  Doh!   Damn, you're good!  :-)

--Fred Stluka
fred@bristle.com

**Comment by RealRaven2000** [comment]
> Perhaps as a popup tooltip on the text field where I type in the value? Hmm... Just checked. The popup tooltip is already there. Doh! Damn, you're good! :-)
> 

LOL!  😂

The thing is all the various toolbars have different values, they may be 20, 30, 40 but it's always possible another Add-on comes along and sets its value to 1000000 just to be on the "real bottom". This could start an "ordinal arms race" :D

**Comment by fredstluka** [comment]
RealRaven2000,

Right.  Where's MAXINT when you need it?  And even that's no
good when the software or the OS moves from 16-bit to 32-bit
to 64-bit.  I've had to go back and update old code a few times
over the years.  Also, most users don't want to see (and certainly
don't want to have to type) a huge decimal (or hex) number that
happens to be 2^x-1.

--Fred
------------------------------------------------------------------------
Fred Stluka
Bristle Software, Inc.
http://bristle.com 		#DontBeATrump #SadLittleDonny
#ShakeOffTheTrumpStink
#MakeAmericaHonorableAgain
http://MakeAmericaHonorableAgain.us/Trump/Countdown.htm

------------------------------------------------------------------------
