### ISSUE TITLE
Feature request: Add option to skip folder(s) when going to next unread mail

### ISSUE THREAD

**Issue by fmommeja** [RealRaven2000/QuickFolders#344]
Hi, it would be great to be able to define somewhere a list of folders to exclude from the _jump to the next unread mail_ action.

This would be very usefull, notably for **virtual folders**.
Thanks!

**Comment by RealRaven2000** [comment]
> Hi, it would be great to be able to define somewhere a list of folders to exclude from the _jump to the next unread mail_ action.
> 
> This would be very useful, notably for **virtual folders**. Thanks!

You can already do this via tabs. 

- Right-click the tab.
- Click "QuickFolders Commands / tab Specific Properties..."

![image](https://user-images.githubusercontent.com/6314674/220113491-d004e5e6-4e77-4d82-83cf-8ac110734d99.png)

Click on "Omit from quickJump / quickMove":

![image](https://user-images.githubusercontent.com/6314674/220113941-5fb5eb44-abd9-49ea-ba75-2ff132cd18ad.png)

You can use Tab categories to hide the tab if you don't want it visible - the exclusion setting will still work.

You can also exclude whole accounts on the Advanced search settings which is located on the Licenses tab:

![image](https://user-images.githubusercontent.com/6314674/220114510-46ce428b-8fd4-490d-bf00-5b795b7d9798.png)

At the bottom of the dialog you can activate which account to ignore:

![image](https://user-images.githubusercontent.com/6314674/220114691-e24c0d34-d0fa-4e9a-8559-401be01c3711.png)

**Comment by fmommeja** [comment]
> You can already do this via tabs.

Ooooh, thank you so much ! 🙏🏻
