### ISSUE TITLE
QF Pro feature "Skip Unread Folder" hides "Add star" function...

### ISSUE THREAD

**Issue by fredstluka** [RealRaven2000/QuickFolders#35]
The QF Pro feature "Skip Unread Folder" works w/o the Shift key.

Therefore, hitting "s" does NOT do the native TB "Add star" function.
Instead, it jumps to the next unread message in the next folder.
Even when the Shift Key is not used.  It should work only with Shift.

QF version 4.18.1
TB version 68.9.0
Mac OS X version 10.11.6
--Fred

Adding an at-mention to see if it causes GitHib to email me this ticket.
@fredstluka

--Fred

**Comment by fredstluka** [comment]
Adding a comment to see how long email notifications take to be sent.

--Fred

**Comment by fredstluka** [comment]
No, the @fredstluka mention did not work trigger an email.  But adding the comment did.  Looks like all edits of the main description field to NOT trigger emails.  Good to know...

--Fred

**Comment by fredstluka** [comment]
Yeah, adding a comment causes a quick email notification.  Within a few seconds.  --Fred

**Comment by RealRaven2000** [comment]
> The QF Pro feature "Skip Unread Folder" works w/o the Shift key.
> 
> Therefore, hitting "s" does NOT do the native TB "Add star" function.
> Instead, it jumps to the next unread message in the next folder.
> Even when the Shift Key is not used. It should work only with Shift.

you found a bug. [S] without [Shift] should definitely NOT replace the Star / Unstar feature. Bet it's a regression

**Comment by RealRaven2000** [comment]
Here is a quick fix. it's bad, I should star messages more often!

[QuickFolders-wx-4.18.2pre1.zip](https://github.com/RealRaven2000/QuickFolders/files/4806831/QuickFolders-wx-4.18.2pre1.zip)

needs to be unpacked to be installed (xpi are viewed as binaries and not accepted in comments)

**Comment by fredstluka** [comment]
It works fine now (in 5.1). Thanks! --Fred
