### ISSUE TITLE
Add visible warning about impending license expiry

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#350]
There is currently no visible warning before the QuickFolders (both Pro and Standard) licenses expire.  Instead the user will be met with restricted functionality of the non-licensed product - some users may even think this as a bug without realizing their license has expired until they get a warning when using an extra tab or feature.

The only place the expiry date (and an extend license button) is visible is if the user goes to the license screen:

![YZS69F6NQoM5dsdR](https://user-images.githubusercontent.com/6314674/228211974-2804edc1-6bfb-4f6a-841a-b463e6e4d25d.png)

Therefore I propose we use the QuickFolders label to communicate a near future expiry:

![RpXLF4rlGR0tvtvl](https://user-images.githubusercontent.com/6314674/228212073-0b929317-3368-4408-8468-259575a5ac1d.png)

**Comment by jaysmithgit** [comment]
I very much agree that this is an important improvement.

**Comment by RealRaven2000** [comment]
> I very much agree that this is an important improvement.

that's great - I already implemented a version of this in quickFilters, see its [issue 170](https://github.com/RealRaven2000/quickFilters/issues/171) - which I released today. I had a bunch of changes queued up that also affected the way it looks once the license is expired, so I rolled in this change there:

![image](https://user-images.githubusercontent.com/6314674/228367278-bef975b7-d6ae-4c92-8d91-ca9e2e600dbd.png)

I had changed the button from a simple pushbutton to a more obvious dropdown, giving more choices to the user. I will probably try to add the chevron (dropdown arrow) to the QuickFolders label as well to make it more obvious that there are consequent choices once it is clicked. It is never quite clear whether a user knows that they can click the QuickFolders label.

**Comment by RealRaven2000** [comment]
Here is a preview version, this is what it looks like. It will also add a menu item for checking the license status to the top of the tools menu:

![image](https://user-images.githubusercontent.com/6314674/231167240-168dee8b-152a-466e-a0b4-23c3cd5803ec.png)

The menu opens QuickFolders settings on the Licenses tab, which shows the real expiry date and a button for extending it.

Once the license is expired the label will look like this:

![image](https://user-images.githubusercontent.com/6314674/231167434-1b5b9907-08c5-407c-b39d-a3c84e46b8c8.png)

The preview version already has translations for the main locales (ca, de, es, fr, hu, it, ja, nl, pl, pt, ru, sl , sr, sv, vi, zh-CN, zv-TW):

[QuickFolders-mx-5.16pre24.zip](https://github.com/RealRaven2000/QuickFolders/files/11200841/QuickFolders-mx-5.16pre24.zip)

To install, download the zip file above then drag into Thunderbird Add-ons manager (**without** extracting!). If anyone needs test licenses that expire soon, hmu via the support email!

**Comment by RealRaven2000** [comment]
implemented in 5.16 - published 21/04/2023
