### ISSUE TITLE
Adding a New Folder when Moving Files

### ISSUE THREAD

**Issue by MSamitz** [RealRaven2000/QuickFolders#356]
So often when cleaning up the inbox, and moving files to alternate location that a destination is not already defined. So, one has to move to the new destination, create the new folder and then return to selecting the files to now be moved to the just created new folder. It would be nice if one could create the New Folder and move files to it all in the same process.
This feature is common in most applications.

**Comment by RealRaven2000** [comment]
> So often when cleaning up the inbox, and moving files to alternate location that a destination is not already defined. So, one has to move to the new destination, create the new folder and then return to selecting the files to now be moved to the just created new folder. It would be nice if one could create the New Folder and move files to it all in the same process. This feature is common in most applications.

this feature exists - you can either do it by dragging to a QuickFolders tab (and generate a child folder directly) or preferably use the quickMove feature:

**To a QuickFolders Tab (or subfolder)**

![image](https://user-images.githubusercontent.com/6314674/236539116-d7ead9fb-2458-4290-a017-5d7060f99c40.png)

note: with this way you can only create a subfolder to any folder if there is at least one subfolder in it already.

**Using quickMove**

- drag the file onto the quickMove button (or use the QF Pro shortcut `Shift+M`, once it's enabled on the licenses tab)

![image](https://user-images.githubusercontent.com/6314674/236537945-7ae940f8-c4b2-4526-af84-ee98e91575d1.png)

- you can start entering the parent folder name (or the grandparent). e.g. Social/Twitter/  (the first 2 letters are usually enough)
 
![image](https://user-images.githubusercontent.com/6314674/236538211-dd6b8b54-24e6-4925-ab81-8d939eb0cbac.png)

- then enter / followed by the new folder name:

![image](https://user-images.githubusercontent.com/6314674/236538302-1426bf0b-f64e-4875-a429-82c192cabb4e.png)

if the folder exists you can move the mail there, if not you can create it in that step. the mail will then be moved to the new folder.
