### ISSUE TITLE
quickfolders right click drop down menus text too small - unreadable

### ISSUE THREAD

**Issue by softedge88** [RealRaven2000/QuickFolders#358]
on quickfolders 5.15.2, the right click options and settings drop down menu is unreadable due to the text size being so small it is unreadable. i cannot find a setting to increase the font size.

**Comment by RealRaven2000** [comment]
that's an old version of QuickFolders, what version of Thunderbird are you running? Do you use any specific Themes?

**Comment by softedge88** [comment]
thanks for the response. i'm running the latest, thunderbird 102.11.0. quickfolders shows this as the most current release quickfolders 5.15.2. 

i'm using the thunderbird suave theme that i've been using for more than 15 years. i like how clean the theme is and how unified the look is with firefox suave.

**Comment by RealRaven2000** [comment]
> thanks for the response. i'm running the latest, thunderbird 102.11.0. quickfolders shows this as the most current release quickfolders 5.15.2. i'm using the thunderbird suave theme that i've been using for more than 15 years. i like how clean the theme is and how unified the look is with firefox suave.

strange. the most recent version for Tb102.11.0 is 5.16.1. Can you force an update?

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/a6d54ebd-2f59-4d33-bf36-ed396207be51)

if you click on the QuickFolders entry in Add-ons Manager, it should show 5.16.1:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/a5682076-440b-40cd-901f-e928a2e2bf1d)
![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/99d44b19-ef2b-4b5e-ae2f-0e7db612620f)

**Comment by RealRaven2000** [comment]
with "suave" loaded, this is what the menus look like:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/ea7d889e-7e86-4517-a1da-b934d83ffb99)

Also, **I made some newer versions of this theme**, one is called Thunderbird-60 and the other one is called Earlybird.
