### ISSUE TITLE
Line feeds not displayed

### ISSUE THREAD

**Issue by Vacoas** [RealRaven2000/QuickFolders#368]
![QF 102 line feed](https://github.com/RealRaven2000/QuickFolders/assets/45902444/e035f41e-ac12-4a1a-b577-39fd6bca76f1)
![QF 115 line feed](https://github.com/RealRaven2000/QuickFolders/assets/45902444/b514f3d7-5c31-43a1-af5c-f63c72f53285)

With Thunderbird 102 and QuickFolders 5.16, line feeds inserted before a tag were taken care of properly (cf tag with a yellow line on it).
With Thunderbird 115 and QuickFolders 6.0pre231 (and earlier), the line feeds are not applied (cf tag with a yellow line on it). Applying line feeds on other tags does not work either. However, there is a proper line wrap for tags that do not fit on a line.

Separators work nicely in all versions.

**Comment by RealRaven2000** [comment]
Thanks for reporting, good catch!

**Comment by RealRaven2000** [comment]
[Uploading QuickFolders-mx-6.0pre237.zip…]()

**Comment by RealRaven2000** [comment]
Here is a quick fix. Because of using flex for the toolbar, I had to insert a `<div>` with a special class (it wouldn't work with the `<br>` even though I applied the same style:

```css
#QuickFolders-FoldersBox div.break {
  flex-basis: 100% !important;
  height: 0;
}
```

[QuickFolders-mx-6.0pre239.zip](https://github.com/RealRaven2000/QuickFolders/files/12063706/QuickFolders-mx-6.0pre239.zip)

You may have to restart Thunderbird to see the change, as it likes to cache the style sheets...

**Comment by Vacoas** [comment]
Line breaks work nicely now.

Many thanks for an extremely quick fix. Such speed reminds me of the French comics hero, Lucky Luke, "the man who shoots faster than his shadow".

Moving to Thunderbird 115, I realised that the only two add-ons I REALLY needed were QuickFolders and QuickFilters... 

All the best.

**Comment by RealRaven2000** [comment]
Since there is no published version on ATN, I will close the issue here. See latest version over at #351

https://github.com/RealRaven2000/QuickFolders/issues/351#issuecomment-1637054326
