### ISSUE TITLE
Tab Backgroud of activ Tab not swap if click on group folders in tree

### ISSUE THREAD

**Issue by Herbert-Testmann** [RealRaven2000/QuickFolders#369]
The aktiv tab has a background color.
If I click on the tabs it works fine.
If a single Folder in tree is aktiv and I click on a group folder in tree, the tab for the group folder don't become the aktiv color.
Group folder ... Inbox, send, junk ...

![Bildschirmfoto 2023-07-30 um 21 04 11](https://github.com/RealRaven2000/QuickFolders/assets/20645041/a67a534e-1f69-4c13-9c6e-515ba7000619)

**Comment by Herbert-Testmann** [comment]
MacOs 13.5
TB 115.0.1
QF  6.0
Layout: Flat Style

**Comment by RealRaven2000** [comment]
Thanks for reporting, however I can't reproduce this here, with QuickFolders v 6.0 - can you try the release version [from here](https://github.com/RealRaven2000/QuickFolders/releases/6.0)?

This one currently awaits review on ATN. When I switch tabs (or select a unified folder from the tree) it works as expected:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/2d805047-58c4-40dc-aee8-c35bd8d09703)

**Comment by RealRaven2000** [comment]
FYI, I also added a feature request to give access to all subfolders of a unified folder, here: #370

**Comment by Herbert-Testmann** [comment]
- one restart of thunderbird later - it works.  close
- it was the version 6.0 from github, the addon manager from thunderbird don't find the quickfolders addon.

**Comment by RealRaven2000** [comment]
> * one restart of thunderbird later - it works.  close
> 
> * it was the version 6.0 from github, the addon manager from thunderbird don't find the quickfolders addon.

it's actually under review and will be published this week, hopefully.
