### ISSUE TITLE
"/" in quickMove box for non-existent parent - show "no match" instead of "..."

### ISSUE THREAD

**Issue by fredstluka** [RealRaven2000/QuickFolders#37]
In the quickMove box, you can type "/" after a folder name prefix
and then type the name of a new or existing subfolder.  Nice feature!

But if you type a prefix that does NOT match an existing folder
name, when you type "/" it shows a "..." dropdown that does nothing.
This is harmless, but probably not intended.

QF version 4.18.1
TB version 68.9.0
Mac OS X version 10.11.6
--Fred

**Comment by RealRaven2000** [comment]
would this be clearer if we showed a label "no matching folders"?

**Comment by fredstluka** [comment]
Yes, that would be clearer.  Thanks!  --Fred

**Comment by RealRaven2000** [comment]
Here is a test version, the message menuitem is hard-coded in in English:
![image](https://user-images.githubusercontent.com/6314674/106951651-eea35880-6727-11eb-9f3a-29130a137458.png)

This will be only shown if at least one "/" is entered as it only covers the case of looking for matching parent folders.

[QuickFolders-wx-5.3pre28.zip](https://github.com/RealRaven2000/QuickFolders/files/5928327/QuickFolders-wx-5.3pre28.zip)

(to try out, download the zip file and drag into Thunderbird Add-ons Manager)

**Comment by RealRaven2000** [comment]
Implemented in 5.3 / 4.20 - released 22/02/2021
