### ISSUE TITLE
Changing 'minimum height'  opens help topic (bug 25021)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#372]
I incremented the minimum height setting. So doing duplicated a tab, each time I did it. Screenshot:

![QF](https://github.com/RealRaven2000/QuickFolders/assets/47056543/969abf55-1213-4d1f-8c8c-97488bb88280)

EDIT: The 'minimum height' setting at issue is the _'toolbar'_ minimum height setting.

QF 6.1pre16
Thunderbird 115.0.1 (x64)
Windows 10 Pro - 22H2 (2009: 19045)

**Comment by RealRaven2000** [comment]
wow! :) that's very peculiar. thanks for finding this.
I see what;s happening, there is a bog article describing the minimum height fix on the label (to the left of the checkbox), and the click event is passed up as the checkbox is contained within the label now.
Anyway, I tried preventDefault and stopPropagation without any avail. Then I fixed it inside the event handler by checking event.target. If it still happens, then you should see a red message in error console with (clickable) detail about the event.

[QuickFolders-mx-6.1pre26.zip](https://github.com/RealRaven2000/QuickFolders/files/12221907/QuickFolders-mx-6.1pre26.zip)

PS: to see the output, debug mode must be enabled.

**Comment by RealRaven2000** [comment]
Ok, that's actually an old bug, it also happens in 102. Must be there since the options dialog was converted to HTML. so I am going to backport the same fix to 5.16.2

**Comment by LinuxOnTheDesktop** [comment]
Great stuff: QuickFolders-mx-6.1pre26, running in Thunderbird 115.0.1, on Windows, seems to fix the problem.

**Comment by RealRaven2000** [comment]
Fixed in 5.17 published 07/Aug/2023.
Will soon be fixed in 6.1 for ESR115

**Comment by LinuxOnTheDesktop** [comment]
Thanks. Trying to load 5.17 into my Windows Thunderbird 115.1.0 generates an incompatibility notice.

**Comment by RealRaven2000** [comment]
> Thanks. Trying to load 5.17 into my Windows Thunderbird 115.1.0 generates an incompatibility notice.

yeah, like I said this is for ESR 102.* - fixes for ESR 115.* will follow in 6.1 - we have 2 separate code branches / releases because the changes were so freaking enormous.

**Comment by RealRaven2000** [comment]
Fixed in 6.1 (published 08/08/2023) and 5.17.1 (published 07/08/2023)
