### ISSUE TITLE
Toolbar background: colour setting seems ignored

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#373]
Setting the colour of the toolbar background, and/or setting it to transparent, seems to have no effect. Whatever I do, the background appears as a cyan line. Perhaps though I misunderstand the UI.

Screenshot:

![image](https://github.com/RealRaven2000/QuickFolders/assets/47056543/5641fa78-e54c-4bfd-93af-32b443c73a2d)

**My system**

QF 6.1pre16
Thunderbird 115.0.1 (x64)
Windows 10 Pro - 22H2 (2009: 19045)

**Comment by RealRaven2000** [comment]
you need to deactivate the "transparent" checkbox or you'll only get a slight tint of that color.

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/292a69ee-e792-439a-851f-ae11fbca974b)

The "thin line" is the last color stop of the Active Tab Color and can be set here:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/9a52912c-4782-4c1d-b853-307dc01bd417)

**Comment by RealRaven2000** [comment]
one thing that is missing here is the label "Bottom Line Width:" which should show to the left of the first numeral input in the toolbar line:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/55423d80-e4c8-4d38-ad30-d6885a2bb8b0)

the label is there in inspector, but just not wide enough to be visible:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/b4960060-3f9e-45fe-8707-2229eebfef4c)

**Comment by RealRaven2000** [comment]
I fixed the missing label for the bottom line, too:

[QuickFolders-mx-6.1pre28.zip](https://github.com/RealRaven2000/QuickFolders/files/12222160/QuickFolders-mx-6.1pre28.zip)

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/bb9815e0-31b3-4b8b-af8d-57d40feb49af)

There was also a tooltiptext attribute that isn't visible anymore in HTML elements, I have converted this into a "title" attribute which will show up when you hover over the input box:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/559d5cd8-4454-4c4e-b2fa-a556471ea780)

**Comment by RealRaven2000** [comment]
I think this is working "as designed" - couldn't really find much to fix...
