### ISSUE TITLE
Retire option to set QuickFolders Bar Position in Tb115

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#380]
1) No value that I enter into the QuickFolders Bar Position (pictured below) seems to do anything, even after pressing 'Apply position value!'. I tried 100, some positive integers, and some negative integers.

![image](https://github.com/RealRaven2000/QuickFolders/assets/47056543/2dc380fe-2d49-420b-84a9-ed8065a5ed99)

2) Inputting a value only works only via the increment and decrement buttons; selecting the field and typing did nothing. Or rather that latter problem happens _sometimes_ - I am unsure just when. Possibly the behaviour varies depending upon whether something - or which text - is highlighted within the field.

**My system**

QF 6.1pre28
Thunderbird 115.0.1 (x64)
Windows 10 Pro - 22H2 (2009: 19045)

**Comment by RealRaven2000** [comment]
Yeah I think that one doesn't work anymore in Thunderbird 115. I might have to retire this setting.

**Comment by RealRaven2000** [comment]
Remove settings from messages.json : `qf.label.toolbarPosition` + `qf.btn.applyPosition`  + `qf.toolbarPosition.tooltip`
preference: `qfpa-ToolbarPosition`
legacy setting: `extensions.quickfolders.toolbar.ordinalPosition`
event listeners for: #applyPosition

Redesigned the Advanced panel - removed the QuickFolders Position group and moved down Updates beside Miscellanous, which was turned from horizontal to vertical flow:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/332d21fb-07be-439f-ae25-773d4ca5462c)

After all code changes, we also managed to shave of 1.6kByte in code size- less code = less complexity = less sources for error.

[QuickFolders-mx-6.1.2pre19.zip](https://github.com/RealRaven2000/QuickFolders/files/12378529/QuickFolders-mx-6.1.2pre19.zip)

---

To test the version above, download the zip file, drag into Thunderbird Add-ons Manager, do not extract contents or if won't install.

**Comment by RealRaven2000** [comment]
Implemente in 6.2 - Published 30/08/2023
