### ISSUE TITLE
Open folder in new tab while viewing a message in tab (single mail tab)

### ISSUE THREAD

**Issue by dzlater** [RealRaven2000/QuickFolders#398]
Hi, 
It looks like something changed, with v.6.2 I now need to <ctrl> click to open a folder while viewing a message, 
this appears to be new behavior with this release. 

Thank you.

**Comment by RealRaven2000** [comment]
> Hi, It looks like something changed, with v.6.2 I now need to click to open a folder while viewing a message, this appears to be new behavior with this release.

hmm,  I am not 100% sure what you mean. click what?

**Comment by BobEckman0348** [comment]
What I'm seeing is that if I have a message open, clicking on a folder tab does not work. It only works (opens a folder) when a message is not displayed. Running 115.2.0 and 6.2

**Comment by RealRaven2000** [comment]
> What I'm seeing is that if I have a message open, clicking on a folder tab does not work. It only works (opens a folder) when a message is not displayed. Running 115.2.0 and 6.2

ok - it works for me (opening a message in another tab) but I am still let's say in my inbox, and then click any QuickFolders tab - this will change the current folder to the one on the tab. However I feel you mean something different. is the tab with the message active (is it the current tab)? If that's the case what would you expect - should QF open a completely new tab with a folder or jump back to the very first tab and open the folder there?

**Comment by RealRaven2000** [comment]
> is the tab with the message active (is it the current tab)? If that's the case what would you expect - should QF open a completely new tab with a folder

to be quite honest, I have _never_ tried that. it seems like in **Thunderbird 102**, when I am on a message in a tab and see the QF toolbar, and then click a folder, it opened a completely new tab with the folder. Is that the behavior you expect?

**Comment by RealRaven2000** [comment]
> What I'm seeing is that if I have a message open, clicking on a folder tab does not work. It only works (opens a folder) when a message is not displayed. Running 115.2.0 and 6.2

what should happen? since you are on a mail tab (not a folder tab) we need to open the folder in another tab. New tab? or the first tab? I think the old behavior was that QF opened a new tab unless the selected folder was already open elsewhere...

**Comment by dzlater** [comment]
> what should happen? since you are on a mail tab (not a folder tab) we need to open the folder in another tab. New tab? or the first tab? I think the old behavior was that QF opened a new tab unless the selected folder was already open elsewhere...

IMHO it should open in the first tab, but I could live with it opening a new tab.
In my ideal world users would have the option to select (open in first tab, open in new tab, don't open)

**Comment by BobEckman0348** [comment]
OK, picture worth a thousand words. With this message open, clicking on ANY of the tabs does nothing. I need to close the message to open another tab.

![image](https://github.com/RealRaven2000/QuickFolders/assets/54083423/4308b236-25c8-4a57-b30b-20f0d77aac5c)

**Comment by RealRaven2000** [comment]
OK, I think is just old behavior from Thunderbird 102. I will see what I can do.

**Comment by RealRaven2000** [comment]
Test version below. Behavior was caused by the rename of tab mode from `message` to `mailMessageTab`. Apparently I still had some code using the old identifier, especially in he function `QuickFolders_MySelectFolder()`. Also some code that would guard against the wrong tab mode here, needed to expanded to include this tab mode.

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/1bbd1f00-00df-4bd5-be30-c1efbdef81f8)

[QuickFolders-mx-6.2.1pre6.zip](https://github.com/RealRaven2000/QuickFolders/files/12700055/QuickFolders-mx-6.2.1pre6.zip)

---------

To test the version above, download the zip file, drag the file into Thunderbird Add-ons Manager, do not extract contents or if won't install. 

- Edit: pre5 had a problem from non-working code for issue #378, please refresh and restart if you installed pre5.

**Comment by RealRaven2000** [comment]
Implemented in 6.3 - Published 30/10/2023
