### ISSUE TITLE
Make registration screen less tall / easily resizable

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#400]
The registration dialog is too tall for some devices like laptops with smaller screens:

![license-screen-too-tall-redacted](https://github.com/RealRaven2000/QuickFolders/assets/6314674/7ca47e62-7583-4b86-812b-e145d4c10d1d)

this makes it hard to close it and even reach the top / bottom buttons. Make sure the screen can always be closed and nothing is cut off.

**Comment by Isocelt** [comment]
- Display resolution: 2560*1140 (Windows 10's recommended option for this laptop's screen)
- Scaling: 200% (Windows 10's recommended option for this resolution)

Opening the registration dialog in a tab, as you suggested, would indeed be better, I think.

**Comment by RealRaven2000** [comment]
> * Display resolution: 2560*1140 (Windows 10's recommended option for this laptop's screen)
> 
>     * Scaling: 200% (Windows 10's recommended option for this resolution)
> 
> 
> Opening the registration dialog in a tab, as you suggested, would indeed be better, I think.

thanks for the added info. 200% is indeed very extreme, but it's also a great way of testing this - I have two 2.5k monitors as well (I think mine are 27inch, so I only use 125%)

**Comment by RealRaven2000** [comment]
As a first workaround, I am adding a button to collapse the section with license terms:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/f596bd5f-de09-4ab4-9cf4-f697e3c135ae)

this will move the more important parts (identity selection and purchase buttons) up on the screen,. Still need to figure out how to resize the dialog to react. I assume the new button (Close license terms) should always be visible on screen. Also the dialog can be closed using [ESC] on the keyboard if the close buttons are not visible.

[QuickFolders-mx-6.3pre72.zip](https://github.com/RealRaven2000/QuickFolders/files/12829382/QuickFolders-mx-6.3pre72.zip)

----

To test the version above, download the zip file, drag the file into Thunderbird Add-ons Manager, do not extract contents or if won't install.

**Comment by Isocelt** [comment]
It sorta works. However, because the top of the window is still hidden, the only way to close the window is to click on one of the "buy" buttons, or to crash Thunderbird:

![1](https://github.com/RealRaven2000/QuickFolders/assets/131725002/b1c45661-1521-45c0-a1cd-c4c8df84c9a6)

Note that the update announcement window _can_ be closed (though the button is more than half hidden), and that it has a vertical scroll bar:

![2](https://github.com/RealRaven2000/QuickFolders/assets/131725002/cc9c45a7-ff46-46f9-828b-e474fc4ae2f2)

**Comment by RealRaven2000** [comment]
> It sorta works. However, because the top of the window is still hidden, the only way to close the window is to click on one of the "buy" buttons, or to crash Thunderbird:

does the [ESC] key not work? What about ALT+F4? I definitely want to make it auto-resize, and maybe I can position it so it is not vertically centered but aligns with the top of the screen for very small screens.

> Note that the update announcement window can be closed (though the button is more than half hidden), and that it has a vertical scroll bar:

I recently added that (expirementally) but this window is written in pure HTML. THe registration screen is (sadly) still CHMLT / XUL, and needs to be converted eventually.

**Comment by Isocelt** [comment]
[ESC] doesn't work for me, and neither does ALT+F4 (which I hadn't tried but have now). Sorry. :o/

**Comment by RealRaven2000** [comment]
> [ESC] doesn't work for me, and neither does ALT+F4 (which I hadn't tried but have now). Sorry. :o/

that is strange, maybe it only works in Windows 10?  I need a way to avoid the title bar going "out of bounds"

**Comment by Isocelt** [comment]
Correction: Alt+F4 works. The first time I tried, I forgot to press Fn to switch from the media keys to the actual F keys.

Sorry.

**Comment by RealRaven2000** [comment]
I have decided to make the terms panel invisible initially; this will also make the dialog less daunting. See test version below:

[QuickFolders-mx-6.3pre85.zip](https://github.com/RealRaven2000/QuickFolders/files/12857366/QuickFolders-mx-6.3pre85.zip)


![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/9554203a-5271-49d0-8605-c47951fef19a)

To make the effect more obvious I decided to add a striped background when hovering in the field:
![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/b33d90fd-b5c1-473c-8f86-82b2056405ae)

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/6a269a72-2df2-44ce-9fa1-0ad8f2c04a7e)

The user will have to close license terms to click on the Upgrade/ buy / renew buttons, but I think it's very obvious. the onlyt downside is that the hyperlink for comparing features is not visible initially...

Should the label on the button be changed in some way?

-----

To test the version above, download the zip file, drag the file into Thunderbird Add-ons Manager, do not extract contents or if won't install.

**Comment by RealRaven2000** [comment]
I decided to change the flow a little more, by moving the button to the bottom of the terms + conditions section and then hiding the bottom form while the license terms are displayed. The button then reads "Continue to License Selection"

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/16acea58-6840-408d-a5a8-1b0eeac271ab)

After each change of the layout I call `window.sizeToContent()` to make sure there is no wasted space on the dialog.

this way the screen and ordering flow should become much clearer. To test, just use "QuickFOlders Pro License..." from the QF tools menu:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/c575f349-5f29-4fcf-a59d-9af608f82eda)

new test version:

[QuickFolders-mx-6.3pre92.zip](https://github.com/RealRaven2000/QuickFolders/files/12857704/QuickFolders-mx-6.3pre92.zip)

----

To test the new version download the zip file, drag the file into Thunderbird Add-ons Manager, do not extract contents or if won't install.

**Comment by Isocelt** [comment]
Ah! It's weird, but it works.

**Comment by RealRaven2000** [comment]
> Ah! It's weird, but it works.

how is it weird? (guess the "show license terms" isn't necessarily something all people want to read anyway, so I actually felt the window was much easier to parse at a glance...)

Very latest version (fully translated) with some style stuff added. is the diagonal striped background too much?

[QuickFolders-mx-6.3pre94.zip](https://github.com/RealRaven2000/QuickFolders/files/12869406/QuickFolders-mx-6.3pre94.zip)

**Comment by Isocelt** [comment]
Rather than "weird," I should have said "uncommon" (compared to the usual scrolling). The current system does work as intended, and the diagonal striped background is perfectly fine, especially since you can remove the stripes simply by moving your mouse cursor out of the striped section.

**Comment by RealRaven2000** [comment]
Thanks for the feedback. ideally I would have like to remove the background when the cursor moves off the button, but I haven't found a CSS only way to do this (yet). I might yet find a way to do this, hoping a solution may be here:

https://www.geeksforgeeks.org/how-to-style-parent-element-when-hover-over-a-child-element-in-css/

**Comment by RealRaven2000** [comment]
> Rather than "weird," I should have said "uncommon" (compared to the usual scrolling). The current system does work as intended, and the diagonal striped background is perfectly fine, especially since you can remove the stripes simply by moving your mouse cursor out of the striped section.

Yeah since it wasn't super obvious that you have to move the mouse entirely out of that area I found a way to only show it while the mouse is on the toggle button. This signals the fact that the button affects that area:

[QuickFolders-mx-6.3pre102.zip](https://github.com/RealRaven2000/QuickFolders/files/12879336/QuickFolders-mx-6.3pre102.zip)

The good thing is that I can reuse all this work for my other 2 commercial Add-ons, quickFilters and SmartTemplates. Thanks to all participants for getting this completed. In open source, sometimes motivation is important.

**Comment by Isocelt** [comment]
Thank you for caring about even small details like that. Keep up the good work, Axel!

**Comment by RealRaven2000** [comment]
Implemented in 6.3 - Published 30/10/2023
