### ISSUE TITLE
odd "null" text appears on message window below menu and above toolbar

### ISSUE THREAD

**Issue by gitedgr** [RealRaven2000/QuickFolders#401]
After installing Thunderbird 115.2.0 (64-bit) yesterday, all of my email messages (not when I'm composing, but all that I receive and those that I later view from my Sent folder), have this odd "null" text in the top left corner, below the menu and just above (and to the left of) the window toolbar.

It's taking up a whole line (i.e., if I can get rid of it, the toolbar moves up to be immediately under the menu).

When I disable the QuickFolders extension, the "null" text and blank line at the top disappear. As soon as I re-enable, it returns.

**Comment by gitedgr** [comment]
![TestEmailTBird](https://github.com/RealRaven2000/QuickFolders/assets/140623422/34c6a4a9-01ce-4e5a-b3f8-1774d1bafba9)
Here's a screenshot of what I mean from the above comment - see "null" in the top left corner of the window.

**Comment by RealRaven2000** [comment]
this has been fixed in a previous version, closing for now
