### ISSUE TITLE
Toolbar issues in Single Message window: "null" element

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#404]
In sinlge message windows, an element with the text content "null" is inserted at the top. it shows underneath the navigation toolbar if that is enabled, otherwise directly under the menu / toolbox:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/49335981-53f7-492f-b55e-d6342a75b2c1)

**Comment by RealRaven2000** [comment]
Pretty sure this is caused by some code duplication in qf-MessageWindow.js. Here is a version with attempt to fix:

[QuickFolders-mx-6.3pre21.zip](https://github.com/RealRaven2000/QuickFolders/files/12743685/QuickFolders-mx-6.3pre21.zip)

I also remove the navigation toolbars and the filter button, as they are not really relevant in this context.

---------

to try this prerelease, download the zip file and drag it into Tb Add-ons Manager (do not extract contents)

**Comment by Clstei** [comment]
The bugfix 6.3pre21 works!

I did not report this bug, but I had the same problem with Thunderbird 115.1.1 and Quickfolders 6.2. I installed the above mentioned bugfix 6.3pre21 and the problem with "null" display is gone. Thanks

**Comment by RealRaven2000** [comment]
Fixed in 6.3 - Published 30/10/2023
