### ISSUE TITLE
Bug: overflowing Navigation toolbar into message header in vertical view

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#409]
In Vertical view (3 columns layout: folder tree, thread pane, message preview) - the elements of the navigation bar overflow into the header area:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/9f546ab0-8cda-41c0-92de-6227a5eeba5d)

the items should be clipped to the right.

**Comment by RealRaven2000** [comment]
quickfix:
[QuickFolders-mx-6.3pre23.zip](https://github.com/RealRaven2000/QuickFolders/files/12751493/QuickFolders-mx-6.3pre23.zip)

-----

to try this prerelease, download the zip file and drag it into Tb Add-ons Manager (do not extract contents)
Also, don't forget to restart Thunderbird, because it caches style sheets, so it won't load the new rule until then!!!!

**Comment by fthommen** [comment]
The Quickfix ([QuickFolders-mx-6.3pre23.zip](https://github.com/RealRaven2000/QuickFolders/files/12751493/QuickFolders-mx-6.3pre23.zip)) solves the overflow into the message header (thanks), but IMHO there should be no QF navigation toolbar in the maillist column in the vertical view layout at all. Instead, it should be placed on top of the email pane (rightmost column), as it does in the other layout variants.

**Comment by RealRaven2000** [comment]
> The Quickfix ([QuickFolders-mx-6.3pre23.zip](https://github.com/RealRaven2000/QuickFolders/files/12751493/QuickFolders-mx-6.3pre23.zip)) solves the overflow into the message header (thanks), but IMHO there should be no QF navigation toolbar in the maillist column in the vertical view layout at all. Instead, it should be placed on top of the email pane (rightmost column), as it does in the other layout variants.

I tried that but it makes the email preview non functional/ haven't found a way to do this, I guess Thunderbird uses firstchild or something to access the email preview pane. and tha email pane is in a different document on top of that. It's not as easy as all the older Thunderbird versions before that were all within the same document.

**Comment by fthommen** [comment]
@RealRaven2000 I see. Thanks for the explanation.

**Comment by RealRaven2000** [comment]
Fixed in 6.3 - Published 30/10/2023
