### ISSUE TITLE
Cannot add new tab to QuickFolders toolbar, no error message on screen

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#413]
With QuickFolders 6.2 adding a new folder to the toolbar with drag+drop fails silently. Enabling the `extensions.quickfolders.debug.dnd ` switch the following log is generated:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/e96b474e-2ca8-4650-b6d5-1a0728bd11ed)

**Comment by RealRaven2000** [comment]
Checked the code, in quickfolders,js line 1002 the information is retrieved from the drop event's dataTransfer object:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/e6621707-88e6-4e74-982c-8dcc11d2b272)

it looks like mozTypesAt(0) retrieves an empty contentType array. We need to know the `contentType` in order to know what was dragged (a folder, a file and email?). I haven't seen this problem before and currently have no idea how to work around it. The error was reported on Thunderbird 115.3.1 and it works for me (and probably majority of my users) as I haven't gotten any other reports of this kind from about 6000 users.

The contentType needs to be `"text/x-moz-folder"` or `"text/x-moz-newsfolder"` in order for the tab to be added. It can also be "text/currentfolder" for moving the current folder tab (from the navigation bar in the center of screen) oder `"text/plain"` / `"text/unicode"` for moving buttons left or right.

**Comment by RealRaven2000** [comment]
I made a test version that supplies more information in JavaScript error console:

[QuickFolders-mx-6.3pre83.zip](https://github.com/RealRaven2000/QuickFolders/files/12856104/QuickFolders-mx-6.3pre83.zip)

It generates the following output when the drag fails:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/7c59b2d5-b41e-4fbc-a667-7f5997e5d116)

Click on the last variable ("DatratransferItemList") to expand the contents and get more information.

-----

to install the test version, download the zip file and then drag the file into Thunderbird Add-ons Manager (do not extract contents).

**Comment by bernd-o-mat** [comment]
[console-export-2023-10-10_13-14-22.txt](https://github.com/RealRaven2000/QuickFolders/files/12856370/console-export-2023-10-10_13-14-22.txt)
this is the output from the error log. The list seems to be empty?!

**Comment by RealRaven2000** [comment]
> [console-export-2023-10-10_13-14-22.txt](https://github.com/RealRaven2000/QuickFolders/files/12856370/console-export-2023-10-10_13-14-22.txt) this is the output from the error log. The list seems to be empty?!

that's a problem! What other Add-ons have you installed? Anything that might interfere with the folder tree, such as the "Manually sort folders" extension?

can you re-order the tabs by dragging them left-right?

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/4cd7f535-a1f2-4368-ad01-2da9eaa4024b)

(an arrow will indicate the new position. do not try to drag "in between" the tabs just one tab on top of the other)

**Comment by bernd-o-mat** [comment]
You got it! I use the Add-On "Disable DragAndDrop (Thunderbird)" to make sure that I don't occasionally move some folder in the folder tree. Disabling this specific Add-On makes Qucikfolders work again!

**Comment by bernd-o-mat** [comment]
Now I will try to contact the developer of "Disable DragAndDrop (Thunderbird)" because it used to work before TB 115 update. Maybe he has an idea to help in this case. Actually I really need both Add-Ons to work together. I happened to often that I accidentally move email folders without noticing it.

**Comment by RealRaven2000** [comment]
> You got it! I use the Add-On "Disable DragAndDrop (Thunderbird)" to make sure that I don't occasionally move some folder in the folder tree. Disabling this specific Add-On makes Qucikfolders work again!

I am not surprised. Will close as completed. :)

**Comment by bernd-o-mat** [comment]
Still one problem remains: I can't load the config from json-file. This is the error log:
Uncaught TypeError: document.getElementById(...) is null
    windowControlShowing chrome://cardbook/content/wdw_cardbook.js:3739
    nIntervId chrome://cardbook/content/wdw_cardbook.js:2135
4 wdw_cardbook.js:3739:18
QuickFolders 13:48:56.605  [7701 ms]   
 Setting default path for filepicker: C:\Users\bseufert\Desktop quickfolders-util.js:1304:13
Uncaught TypeError: document.getElementById(...) is null
    windowControlShowing chrome://cardbook/content/wdw_cardbook.js:3739
    nIntervId chrome://cardbook/content/wdw_cardbook.js:2135
wdw_cardbook.js:3739:18
QuickFolders 13:48:58.947  [2342 ms]   
 File Picker Path: C:\Users\bseufert\Desktop\QuickFolders-Config.json quickfolders-util.js:1304:13
QuickFolders 13:48:58.948  [1 ms]   
 Storing Path: C:\Users\bseufert\Desktop quickfolders-util.js:1304:13
Uncaught TypeError: document.getElementById(...) is null
    windowControlShowing chrome://cardbook/content/wdw_cardbook.js:3739
    nIntervId chrome://cardbook/content/wdw_cardbook.js:2135
wdw_cardbook.js:3739:18
XPCWrappedNative_NoHelper { QueryInterface: QueryInterface(), logLevel: Getter, timeStamp: Getter, microSecondTimeStamp: Getter, message: Getter, isForwardedFromContentProcess: Getter & Setter, errorMessage: Getter, sourceName: Getter, sourceLine: Getter, sourceId: Getter, … }
quickfolders-util.js:1330:15

Maybe this requires another issue?
Regards
Berndomat

**Comment by bernd-o-mat** [comment]
This happens even with all other Add-Ons disabled.

**Comment by RealRaven2000** [comment]
> Now I will try to contact the developer of "Disable DragAndDrop (Thunderbird)" because it used to work before TB 115 update. Maybe he has an idea to help in this case. Actually I really need both Add-Ons to work together. I happened to often that I accidentally move email folders without noticing it.

just an idea: only touch the folder tree when you want to add a new Tab. Do not use it for the following tasks:
- jumping to a folder. scrolling takes too long, you can use a QF tab or the quickJump button on the top left:
![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/c8fe869c-bd36-4d5a-ab9b-427a07c89f07)
- moving mails. again use a QF tab or the quickMove button (same as above just with drag+ drop). Once you have more than 100 folder altogether I promise this is going to save you buckets of time every week.
- with QuickFolders Pro you can use keyboard shortcuts for the above functions.

For people with many folders, the Folder tree is a lost cause and a waste of time. Once I stopped using it for navigation and mail management I had a much nicer experience. All my development efforts in QF are toward making live easier and prevent repetitive strain injuries and time.

**Comment by RealRaven2000** [comment]
> Maybe this requires another issue?
> Regards
> Berndomat

yes please, open a new one. piggy backing new issues in existing ones is a  bad idea, because it creates never ending issues and frustration on all sides.

**Comment by RealRaven2000** [comment]
PS: you can use the `<code>` button for large log sections and code:

highlight the section then press:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/9eb051ee-563c-4278-95c2-63bfcce6c385)

this will make your issues more readable, at least when on the Github website (superior to using Emails for following up)
