### ISSUE TITLE
QuickFolders 6.2, Linux: 'null' appearing at top of emails, with Thunderbird 115.3.1x64

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#414]
Hello there.

I'm having the problem that is reported [here](https://support.mozilla.org/en-US/questions/1423397) and traced to QuickFolders (as against to [this](https://bugzilla.mozilla.org/show_bug.cgi?id=248703) fixed-20-years-ago Thunderbird bug). I verified that QuickFolders was the (at least proximate) cause by disabling the AddOn and restarting Thunderbird. I have the problem on Linux. I don't think I see the problem on Windows.

**Comment by RealRaven2000** [comment]
Thanks for reporting - there is a fix at #404 - it will be part of the next release.  (Closing this one as duplicate)
