### ISSUE TITLE
replacement of icons

### ISSUE THREAD

**Issue by matze-babbo** [RealRaven2000/QuickFolders#415]
Replacing icons no longer works in the current Thunderbird version Supernova 115.3.1. We work for different suppliers and had replaced the icons in the folder area with the company logos. Is it possible to enable this function again?

Greetings fron Frankurt
Jörg

**Comment by matze-babbo** [comment]
Sorry, this theme belongs to issue #399. this one can be closed

**Comment by RealRaven2000** [comment]
> Sorry, this theme belongs to issue 399. this one can be closed

Of course, no problem. There is a version there that can already read your old icon setup. I am currently working on the feature to set the icon via folder tree context menu.

**Comment by RealRaven2000** [comment]
Link to newest version: [issue 399](https://github.com/RealRaven2000/QuickFolders/issues/399#issuecomment-1749801223)
