### ISSUE TITLE
Request: automatically select next message after quickMove (multiple messages)

### ISSUE THREAD

**Issue by MichaelJFischer** [RealRaven2000/QuickFolders#419]
After moving multiple messages with quickMove, the next following message is highlighted in light gray, but Thunderbird controls don't recognize it as current selected.  In particular, up/down arrow keys don't move it to allow a new selection.  However, quickMove thinks it is still selected and will move it if I type shift-M and select a target folder.
Workaround:  After a quickMove, use mouse to select it.

**Comment by MichaelJFischer** [comment]
TBird version:  115.3.3 (64-bit).
quickFolders version: 6.2

**Comment by RealRaven2000** [comment]
> After moving multiple messages with quickMove, the next following message is highlighted in light gray, but Thunderbird controls don't recognize it as current selected. In particular, up/down arrow keys don't move it to allow a new selection. However, quickMove thinks it is still selected and will move it if I type shift-M and select a target folder. Workaround: After a quickMove, use mouse to select it.

First of all, can you try and reproduce the behavior with the latest build:

[Uploading QuickFolders-mx-6.3pre111.zip…]()

I did some changes related to highlighting the message pane and selecting the current email in #417 

I did put in a 1000ms (1 Second) delay because something else removed the focus again, not sure where it went and why.

**Comment by RealRaven2000** [comment]
I will test this behavior and check what ( and how) is selected by Thunderbird when the user moves messages to a folder in the tree. Full disclosure: i haven’t moved mails to the tree in many years.

**Comment by RealRaven2000** [comment]
I think it is fixed (works for me) in 6.3 - feel free to re-open if you think otherwise
