### ISSUE TITLE
Feature request : showing subfolders permanently without clicking

### ISSUE THREAD

**Issue by joomlafun** [RealRaven2000/QuickFolders#421]
Hi,

Thunderbirds vertical folders allow to view the tree of the subfolders individually.

However Quickfolders which does not have this feature tend to make you reorganize folder without the same visual logic and so you pass from one logic to another when it would not be necessary if you could choose to pick certain quickfolders to have their full tree under it.

Please think about it,but  I know that it is easier to achieve vertically than horizontally though :)

**Comment by RealRaven2000** [comment]
> Thunderbirds vertical folders allow to view the tree of the subfolders individually.

I em not sure what you mean, are you talking about Layout / Vertical View? A screenshot might be helpful...

the main idea of QuickFolders is not to have to use the (vertical) folder tree at all anymore, thus avoiding painful and lengthy daily scrolling - but obviously the subfolders displayed on QF tabs can still be long. With really big folder hierarchies, using quickMove will often be the fastest solution:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/905a6d7c-9b4d-4991-8ee0-ebc358babf3d)

**Comment by joomlafun** [comment]
There are certain folders in the TB folder tree which you leave open as are you are working in this folder and its subfolder right?

Now in quickfolder it would be great to be able to open a folder in the same way in order to show the subfolder temporarely by adding thus an horizontal line below with all the subfolder.

![image](https://github.com/RealRaven2000/QuickFolders/assets/63743077/82624273-1f6f-45ea-8444-f7bc9e00c338)

**Comment by RealRaven2000** [comment]
> There are certain folders in the TB folder tree which you leave open as are you are working in this folder and its subfolder right?
> 
> Now in quickfolder it would be great to be able to open a folder in the same way in order to show the subfolder temporarely by adding thus an horizontal line below with all the subfolder.

I disagree with this design choice. You can always have more submenus, horizontal rows are very hard to navigate, especially if you do it into multiple levels drilling down - you would constantly have to go left / right with the mouse and it would be ultimately much harder to navigate, even if it would "look fancy".

**Comment by joomlafun** [comment]
Thank you for your feedback 

Vertical subfolder do work great and I'm sure that a mix between horizontal folder with vertical subfolders could work if a limitation can be setup to show only a chosen  "x" # number of subfolders

But it is indeed not easy to put in place. I would be curious of the opinion of more people over this subject.
