### ISSUE TITLE
Add-on doesn't load on new profiles from Policies

### ISSUE THREAD

**Issue by biofers** [RealRaven2000/QuickFolders#426]
Hi, since some month ago I can't deploy anymore the addon when I install a new profile.

Policies.jsm: Incompatible add-on - https://addons.thunderbird.net/thunderbird/downloads/latest/quickfolders-tabbed-folders Policies.jsm:1362
1698737374965	addons.xpi-utils	WARN	Add-on quickfolders@curious.be is not compatible with application version.

the addon is pass with a reg file and it's there before the profile its open by first time.
So, if I do this reg file I will have your addon installed, but well this doesn't happens anymore.

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Thunderbird\Extensions\Install]
"1"=hex(2):68,00,74,00,74,00,70,00,73,00,3a,00,2f,00,2f,00,61,00,64,00,64,00,\
  6f,00,6e,00,73,00,2e,00,74,00,68,00,75,00,6e,00,64,00,65,00,72,00,62,00,69,\
  00,72,00,64,00,2e,00,6e,00,65,00,74,00,2f,00,74,00,68,00,75,00,6e,00,64,00,\
  65,00,72,00,62,00,69,00,72,00,64,00,2f,00,64,00,6f,00,77,00,6e,00,6c,00,6f,\
  00,61,00,64,00,73,00,2f,00,6c,00,61,00,74,00,65,00,73,00,74,00,2f,00,71,00,\
  75,00,69,00,63,00,6b,00,66,00,6f,00,6c,00,64,00,65,00,72,00,73,00,2d,00,74,\
  00,61,00,62,00,62,00,65,00,64,00,2d,00,66,00,6f,00,6c,00,64,00,65,00,72,00,\
  73,00,00,00

![image](https://github.com/RealRaven2000/QuickFolders/assets/57214353/395fde55-08f8-420a-9a18-6a59dae5cae1)

I used for long time the option to install certain addons like yours, after many changes we have end up with the registries position that was working well, it's still works with all rest of addons, but it has stop to work with QuickFolders, it's a bit annoying, seems its one of the main addon that we use daily.

Best

**Comment by biofers** [comment]
ok, its seems that it's trying to install the latest version that not compatible with the 102 version of thunderbird. all clear now. change to download the lastest for 102 5.18 version seems to work.

**Comment by RealRaven2000** [comment]
> ok, its seems that it's trying to install the latest version that not compatible with the 102 version of thunderbird. all clear now. change to download the lastest for 102 5.18 version seems to work.

yes this is a known bug in the Core code. it also leads to the Addon not being found from the search box in Addons Manager in 102. this happens when a new branch has to break backwards compatibility. 

115 had so many fundamental changes that staying compatible was nit technically feasible.
