### ISSUE TITLE
Popup menus not removed when dragging across QuickFolders tabs

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#428]
I had seen behavior of popup menus not closing intermittently, but popups left when dragging seems to be more consistent. I am not sure that 6.3 introduced the problem or deprecations of code in the Thunderbird back-end (they keep phasing out XUL features).

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/85522707-8ef4-440f-a274-ce80d57b4b9b)

**Comment by RealRaven2000** [comment]
I made another observation - when dragging the email to a tab that has no subfolders (and hence no popup menu is triggered) some or sometimes all of the other menus are closed. I know there is code that iterates old popup menus forcing a closing, I think this is still in force but maybe only for this one case.

**Comment by ardent42c** [comment]
Have the same issue, but it doesn't seem to be right to left only issue. If I drag over from left to right on the buttons, it has the same problem.

**Comment by RealRaven2000** [comment]
After a bit more research I see that my `dragExit()` function was never triggered and that a lot of chrome browsers do not support this event but instead `dragLeave`, which is a more HTML compatible event, whereas `dragExit` is specific to XUL (the old Mozilla platform code). Although we still are using (some) XUL / xhtml code, there is an ongoing rewrite in the Tb UI to go towards standard HTML, so I decided to simply rename those functions, with some encouraging results. Here is a test version:

[QuickFolders-mx-6.3.1pre4.zip](https://github.com/RealRaven2000/QuickFolders/files/13382452/QuickFolders-mx-6.3.1pre4.zip)

------

To test the version above, download the zip file, drag the file into Thunderbird Add-ons Manager, do not extract contents or if won't install.

**Comment by RealRaven2000** [comment]
There seems to be a side effect with the "hover" background color being stuck when dragging away, so I need to fix that as well...

**Comment by RealRaven2000** [comment]
> There seems to be a side effect with the "hover" background color being stuck when dragging away, so I need to fix that as well...

Ok fixed the side effect, I did some explite calls to `dragExit` that I also needed to renamed...

[QuickFolders-mx-6.3.1pre5.zip](https://github.com/RealRaven2000/QuickFolders/files/13382499/QuickFolders-mx-6.3.1pre5.zip)

discussion on the `dragExit` vs `dragLeave` event  [can be read here](https://stackoverflow.com/questions/42775095/dragexit-vs-dragleave-which-should-be-used).


----

To test the version above, download the zip file, drag the file into Thunderbird Add-ons Manager, do not extract contents or if won't install.

**Comment by ardent42c** [comment]
I can confirm that the issue is indeed resolved with this version. Thanks!

**Comment by RealRaven2000** [comment]
Fixed in 6.4 released on 04/12/2023
