### ISSUE TITLE
quickfilter loses focus after clicking a QF tab

### ISSUE THREAD

**Issue by theovanoostenbrugge** [RealRaven2000/QuickFolders#434]
Hi, 

When i jump to a folder via a tab and click in the (always open) quick filter on Thunderbird, the focus in quickfilter is disappeared. I must click twice in quickfilter.

When i open a folder normaly the quickfilter works fine.

**Comment by RealRaven2000** [comment]
It could be a `setTimeout()` implementation (with the delay being there for a reason), can you check whether it happens if you wait for approx 1.5 seconds and then click?

I will out of office for 2 days and can test this and check the source code over the weekend.

**Comment by theovanoostenbrugge** [comment]
Yes, when I wait for 1,5sec it works fine.

**Comment by RealRaven2000** [comment]
Great then i can make the delay configurable so you can tweak it for your own needs.

**Comment by theovanoostenbrugge** [comment]
That will be great!

**Comment by RealRaven2000** [comment]
I am out of office but will be back tomorrow, then i can build you a test version.

**Comment by RealRaven2000** [comment]
I had the delay (1000ms) in my function `setFocusThreadPane()` - I decided to make it 0 for selecting folders via tab and leave it as is when it is called from the `findFolder()` routine (I think the delay is still there for a reason)

[QuickFolders-mx-6.4pre37.zip](https://github.com/RealRaven2000/QuickFolders/files/13473227/QuickFolders-mx-6.4pre37.zip)

-----

to install the test version, download the zip file and then drag the file into Thunderbird Add-ons Manager (do not extract contents).

**Comment by theovanoostenbrugge** [comment]
it seems like it has been resolved. Thank you!

**Comment by RealRaven2000** [comment]
Fixed in 6.4 released on 04/12/2023
