### ISSUE TITLE
Feature request : open subfolder popup on hover

### ISSUE THREAD

**Issue by joomlafun** [RealRaven2000/QuickFolders#447]
Hi,

Instead of clicking, it would be nice to be able to just hover the tabs in order to view their sub folders

**Comment by RealRaven2000** [comment]
I decided against that because it would be quite disruptive whenever you have multiple rows of tabs or when you use the top menu or buttons on the toolbar it would potentially trigger popups, and they also would have to be removed via a timer event to complicate matters...

**Comment by joomlafun** [comment]
would have been convenient, but you explained why it is difficult to implement, I understand
