### ISSUE TITLE
Larger Icons

### ISSUE THREAD

**Issue by PotatoCarl** [RealRaven2000/QuickFolders#466]
Hi,
I am using very intensly the "Move to folder" function including Quickfilter to generate Filters for incoming emails.
To do this, I move an email to the "move to folder icon" and then select the folder to move it into this folder.
However, the icon is very small, so I have troubles hitting it. 
I do not want to increase the size of all buttons, but this one specifically. Would it be possible to have a larger "landing area"?

**Comment by RealRaven2000** [comment]
Yes, and this will be handled in #462 - closing this one as duplicate
