### ISSUE TITLE
Make QuickFolders compatible with current Thunderbird's beta version 126

### ISSUE THREAD

**Issue by NetBod** [RealRaven2000/QuickFolders#469]
HI,
Can you drop a new version that's works with the current bate version 126 in to issue #454 like you have before please when u have 5 mins.
Thanks

**Comment by RealRaven2000** [comment]
will do later this evening-just out of office today.i meant to update all Add-ons later today.

**Comment by RealRaven2000** [comment]
done, see:

https://github.com/RealRaven2000/QuickFolders/issues/454#issuecomment-2077898796
