### ISSUE TITLE
Make QuickFolders compatible with current Thunderbird's beta version 127

### ISSUE THREAD

**Issue by NetBod** [RealRaven2000/QuickFolders#472]
HI,
Can you drop a new version that's works with the current bate version 127 that has been released in to issue https://github.com/RealRaven2000/QuickFolders/issues/454 like you have before please when u have 5 mins.
Thanks

**Comment by RealRaven2000** [comment]
Done: https://github.com/RealRaven2000/QuickFolders/issues/454#issuecomment-2118767912

WIll updatge my other Repos next.
