### ISSUE TITLE
QuickFolders for TB 128esr

### ISSUE THREAD

**Issue by sv68** [RealRaven2000/QuickFolders#479]
Have been using for a few years now (pro version).
Just updated to TB128esr- looks like current version of QuickFolders is not supported. 
Is there a plan to release TB125+ compatible version soon or is there a work around ?
Thanks

**Comment by RealRaven2000** [comment]
Yes - there is a plan and a compatible version, latest one here:

https://github.com/RealRaven2000/QuickFolders/issues/454#issuecomment-2188440775

I will probably fix #480 first (which was reported yesterday) and then release an official version. You can safely install the prerelease and it will be updated automatically once the official version goes live.

**Comment by RealRaven2000** [comment]
Please check the [latest version here](https://github.com/RealRaven2000/QuickFolders/issues/454#issuecomment-2230664983). It fixes #480 which was the latest bug report. The regression was caused by changes in Tb 126 .

**Comment by RealRaven2000** [comment]
Implemented in 6.6 - Published 21/07/2024
