### ISSUE TITLE
Owl accounts cannot be license validated in Tb128.1

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#482]
When using an email address on an exchange server via owl to validate a license there is an error message that the email cannot be found. So far I was able to reproduce the bug on Thunderbird 128.

Unfortunately there is currently no other workaround than using an account that has a different server access method (such as IMAP or POP3).

This is caused by a bug in the accounts extension API. 

I have raised a bug with Mozilla to handle this:

https://bugzilla.mozilla.org/show_bug.cgi?id=1909005

**Comment by dbonner** [comment]
Hi,
I have the same issue.  I have just now emailed my error console message to QuickFolders Support.  It contains details regarding my email addresses and setup.  So I have not pasted the error console messages here.
All the best,
Daniel

**Comment by RealRaven2000** [comment]
> Hi, I have the same issue. I have just now emailed my error console message to QuickFolders Support. It contains details regarding my email addresses and setup. So I have not pasted the error console messages here.

thanks, I will reply you directly there as well. The workaround is to choose any other account and forward me its (default identity) email address so I can issue a new license key until Thunderbird has fixed their issue. Owl accounts are currently invisible to Add-ons!

**Comment by RealRaven2000** [comment]
This problem has been fixed in Thunderbird 128.2.0esr - thanks to John for the fast turnaround!

https://bugzilla.mozilla.org/show_bug.cgi?id=1909005
