### ISSUE TITLE
Tab text with new messages in folder is not readable

### ISSUE THREAD

**Issue by micz** [RealRaven2000/QuickFolders#485]
_Windows 10
Thunderbird 115.13
QuickFolders 6.6.1_

With newly received messages in a folder, the folder name is difficult to read.
It was fine in the previous QuickFolders version (6.5.1).

With no new messages:
![photo_2024-08-02_23-25-16](https://github.com/user-attachments/assets/a5283882-c7d0-4f57-a68b-146cc121b280)

With new messages:
![photo_2024-08-02_23-25-10](https://github.com/user-attachments/assets/aabf7871-b4f5-44b4-ac40-1c685cd5f811)
The black border makes not readable the text.

**Comment by RealRaven2000** [comment]
Please refer issue #468 :

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/61a4b58b-a04e-41de-bfbe-4f4e560601d4)

Switched off (bright background) - this will retain the original font color and not force it to be white:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/ae002e79-743e-42be-a5b9-c2ab8ced186a)

Switched on (bright background):

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/283406a5-54ed-479b-9237-cfdddf10a457)

Switched on (dark background):

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/17288cf7-0028-4297-9ff1-bd432a90156c)

This looks better with larger font sizes, as I believe there may still be some rendering issues with the `-webkit-text-stroke` CSS attribute.

**Comment by micz** [comment]
It works, thank you.
