### ISSUE TITLE
New feature: find related = search filter based on currently selected mail

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#488]
Just leaving this experimental feature here for the moment (it may go into its own Add-on at one stage). I often need to filter the current folder based on the (subject of) the currently selected email. I usually select a portion of the subject line and then paste it into the Thunderbird QuickFilter textbox - if the box is currently hidden I have to hit CTRL+Shift+K first:

![image](https://github.com/user-attachments/assets/5c1b2cb5-4925-4f94-9baf-10edb865e3a1)

I use this to list related orders based on a customer's name which shows up in the subject line - usually, in addition to `Subject` I have filter by `Sender` and `Recipients` also enabled but in this example it would not work as it is my own name.  I have not enable [Body] as this is faster than searching all body of many emails. 

So this is quite a complex set of actions I need to carry out that also involve the mouse, I would like it to be a single click operation, based on a regular expression. In this case a functional regex would be:

`"Order: (QUI\d*\-\d*\-\d*) - (.*) -"`

, with the group argument being 2 (the second set of parentheses will return the searched result, the customer name. It would be best to add a button to the current folder bar (a.k.a Navigation bar) which is located in center screen to automate this operation. A second click on the same button could somehow clear the search box again (this could be based on the same search term already being displayed). Additional functionality would be to select a predefined set of the 4 filter criteria buttons (sender, recipients, subject, body) for the search and then returning to a default setting when the search is reset to "None".

I think I can use the webextension APIs for the actual filtering, namely [`mailTabs.setQuickFilter()`](https://webextension-api.thunderbird.net/en/latest/mailTabs.html#setquickfilter-tabid-properties) .

**Comment by RealRaven2000** [comment]
Here is the first trial version for the feature:

New interfaces - enable in options (to make this visible a valid QuickFolders Pro license is required)

![image](https://github.com/user-attachments/assets/c46f37e1-7285-49b3-b7b7-4275e4e98a1a)


Clicking the configuration wheel to the right opens up the detailed settings:

![image](https://github.com/user-attachments/assets/3e064de2-7a4c-48d7-a4e8-55eeeee30d42)

`extensions.quickfolders.findRelated.pattern` - a regular expression string representing a search pattern that can be used to retrieve a matching string from the currently selected email. FOr example, use "`\[.*\]`" to capture a word or group of words that are in square brackets

`extensions.quickfolders.findRelated.group` - number of match group. 0 represents the complete match, higher numbers are for following (search groups). Please reger to regex101.com for detail.

`extensions.quickfolders.findRelated.searchSelected` - an array of fields that are used to retrieve the search string from the current mail. E.g. ["subject"] to only search the subject line of the currently selecte mail for a match. Once a match is found, it is inserted in the quick filter field of Thunderbird to filter all visible emails. If nothing is found, no filter is set.

`extensions.quickfolders.findRelated.searchCriteria` - an array of fields that can be matched to generate the matching mail resultset. E.g. use ["subject","author","recipients"] to search subject lines, senders and recipients for the search term.

**Example**

I want to find related mails by customer, and I know my mails have subject lines of the following format:

Order: QUIxxxx-xxxx-xxxx - _customerName_ - _productname_

where `xxxx` is an arbitrary number of digits. 

`pattern` = "Order: (QUI\d*\-\d*\-\d*) - (.*) -"
`group` = 2
`searchSelected` = ["subject"]

This defines the pattern, note that the second (expression in parentheses) contains the name of the customer (hence group=2). The patter specified that the name will be between "- name -" and has any arbitrary format. It retrieved from the subject (searchSelected) only. Once a result is retrieved the quick filter will be filled with the name and the filter options specified in `searchCriteria` will be activated, for example ["subject","recipients"] - so any email that is sent to the retrieved name or mentions the name in the subject line.

In future versions we can build a proper interface for settings these parameters, but for now we have something that can already be used to find matching emails in a flexible manner.

[QuickFolders-mx-6.6.2pre33.zip](https://github.com/user-attachments/files/16530812/QuickFolders-mx-6.6.2pre33.zip)


----

To try the version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by BGMcoder** [comment]
There used to be an addon for Thunderbird long ago called "Pivot".  There was a toolbar button.  You push it, and it would change the quickfilter to display messages related to the current message.  It had teeny buttons for parameters - you could pivot on the subject, authour, keywords, etc.  I loved this and got used to it and I've missed it ever since until XUL went out the door.  (old addon is attached)
[qfb_pivot-1.1-tb.zip](https://github.com/user-attachments/files/17002882/qfb_pivot-1.1-tb.zip)

**Comment by RealRaven2000** [comment]
> There used to be an addon for Thunderbird long ago called "Pivot". There was a toolbar button. You push it, and it would change the quickfilter to display messages related to the current message. It had teeny buttons for parameters - you could pivot on the subject, authour, keywords, etc. I loved this and got used to it and I've missed it ever since until XUL went out the door. (old addon is attached) [qfb_pivot-1.1-tb.zip](https://github.com/user-attachments/files/17002882/qfb_pivot-1.1-tb.zip)

Thanks for sharing - I will have a look when I get time. My current plan is to just the button on the navigation bar and a dropdown list with different patterns that the user can set the filter to. The UI for setting (and maybe testing) these filters will be in a new tab in QuickFolders settings, see the latest version:

![image](https://github.com/user-attachments/assets/42093fee-a8ab-4866-85e0-56888d3b5f22)

(the settings don't work yet but they will at least display the controls shown above, of course more well designed)

[QuickFolders-mx-6.8pre24.zip](https://github.com/user-attachments/files/17002950/QuickFolders-mx-6.8pre24.zip)

---

To try the version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by RealRaven2000** [comment]
Latest version, with this one we can define multiple searchs and then preselect one for further searches through the right-click menu:

![image](https://github.com/user-attachments/assets/d174a0b9-e646-478d-970c-93bdcb3731d7)

If the user already has a single search pattern set up they can add it to the menu through the "Update" button:

![image](https://github.com/user-attachments/assets/a502486d-d759-4d41-90b9-e928d3c86bab)

A normal click repeats the last search.

To do: 
- add a checkmark to the currently active search
- add some global options (behaviors) to the _find related_ page
- the "settings" wheel on the current folder settings needs to open the _find related_ page (instead `about:config`)

[QuickFolders-mx-6.8pre48.zip](https://github.com/user-attachments/files/17821500/QuickFolders-mx-6.8pre48.zip)

-----

To test this prerelease, please download the zip file and then drag it into Thunderbird Add-ons Manager (without extracting)

**Comment by RealRaven2000** [comment]
implemented in 6.8 - Published 25/11/2024
