### ISSUE TITLE
Suppress moved-email notifications

### ISSUE THREAD

**Issue by sebawild** [RealRaven2000/QuickFolders#499]
On Ubuntu, every email moved with QuickFolders shortcuts generates a notification like the one below:
![image](https://github.com/user-attachments/assets/0bdee672-e5f4-4997-b344-4e8edc589a0f)
Is there a way to suppress these notifications from QuickFolders (without muting all notifications)?  They are quite intrusive (the number is shown on the app icon) and not overly helpful for me.

**Comment by RealRaven2000** [comment]
Yes - to disable the notification popup: 

- open QuickFolders settings, License tab
- click advanced search settings...
  ![image](https://github.com/user-attachments/assets/f02b593b-2e7d-4b53-958c-656bbb4983fd)
- check the bus "omit notificaitons" and click OK:
  ![image](https://github.com/user-attachments/assets/860bc2bd-f696-482a-80bd-950b9d720d80)

**Comment by sebawild** [comment]
Ohh, thanks!  That's exactly what I was looking for.
