### ISSUE TITLE
[6.8.1]Relocate or jump to folder shortcuts not working after update on TB128.4.3

### ISSUE THREAD

**Issue by joomlafun** [RealRaven2000/QuickFolders#511]
Hi,

I'm on TB 128.4.3esr (64 bits)  flatpack on kubuntu 24.10(kde plasma 6.15) and since the update those shortcuts don't work anymore ; I disabled tbkeys but the situation is the same.

Kind regards,

**Comment by RealRaven2000** [comment]
I assume you have a valid QF Pro license? What shortcuts do you have configured here (QF Options / Licenses Page):

![image](https://github.com/user-attachments/assets/2895e3b2-d16b-492d-9c40-fb891c220b4d)

**Comment by joomlafun** [comment]
Hi, I do.

I switched back to the initial shorcuts shown in your image but situation is the same.

**Comment by joomlafun** [comment]
128.5.0 esr on fedora flatpak with QF 6.8.2 has no more this issue

**Comment by RealRaven2000** [comment]
I made some changes for Apple users to make sure that shortcuts using the command key [⌘] (apple) wouldn't trigger the shortcuts - see #514 - there is a version there that may also be relevant to Linux users (especially for those using QuickFolders on a Mac hardware - there are quite a few Mac users who dual boot into Linux).
