### ISSUE TITLE
Can't drop email to a subfolder

### ISSUE THREAD

**Issue by RickardSvard** [RealRaven2000/QuickFolders#59]
When I drop an email to a subfolder on QF the subfolder don't open, please see the picture.
TB: 78.2.1
QF: 5.0perp81

![image](https://user-images.githubusercontent.com/12534759/93430793-7dbbeb00-f8c3-11ea-8831-5e51d6d26e45.png)

**Comment by RealRaven2000** [comment]
Can you try the latest prerelease here?

[5.0 pre81](https://github.com/RealRaven2000/QuickFolders/releases/tag/5.0pre80)

**Comment by RickardSvard** [comment]
I use 5.0pre81

**Comment by RealRaven2000** [comment]
> 
> 
> I use 5.0pre81

can you check your error console (Ctrl+Shift+J) for warnings that happen during this operation? Make sure to enable line numbers...

@opto can you test again

**Comment by RealRaven2000** [comment]
by the way, this is a duplicate of

https://github.com/RealRaven2000/QuickFolders/issues/55

**Comment by RickardSvard** [comment]
Is this what you want?
![image](https://user-images.githubusercontent.com/12534759/93460992-60e3df80-f8e4-11ea-8bae-273bf4426c40.png)

**Comment by RealRaven2000** [comment]
See latest version below, does it fix the issue?

https://github.com/RealRaven2000/QuickFolders/releases/tag/5.0pre84

**Comment by RickardSvard** [comment]
Works fine now!
https://github.com/RealRaven2000/QuickFolders/issues/55#issuecomment-694475195
