### ISSUE TITLE
Tags for recent pre-releases wrongly set

### ISSUE THREAD

**Issue by graidl** [RealRaven2000/QuickFolders#60]
The tags 5.0pre80 and 5.0pre71 are wrongly set, both correspond to the former pre-release tag 5.0pre66, which currently also is the head of the master branch, and not to the real commits from which the releases were built.

**Comment by RealRaven2000** [comment]
> The tags 5.0pre80 and 5.0pre71 are wrongly set, both correspond to the former pre-release tag 5.0pre66


Thanks. I have no idea how to correct this. The only thing I know now is that we from now on will be using the branch ESR78 (@opto upmerged yesterday) for all future developments for the ESR78 period.

**Comment by graidl** [comment]
See e.g. https://stackoverflow.com/questions/8044583/how-can-i-move-a-tag-on-a-git-branch-to-a-different-commit on how to change a tag. 
But maybe it is not that important to change this now when a next version will follow soon. I just thought I bring this to attention as I was quite confused that Github says "5.0 prerelease 65" is the most recent release and 5.0pre80 seemed to correspond to a much older one.

**Comment by RealRaven2000** [comment]
yeah I was stumped by that one, too, didn't know how to fix it. Maybe I can fix all the tags, but really the ESR78 branch should be on top of the food chain from now on.

**Comment by RealRaven2000** [comment]
I don't think I can fix this - I do not use the git command line. Actually my frontend in windows is TortoiseSVN. I do not have time to learn the convoluted and complicated process of git for using the github code repository. I rather spend my time learning on how to get my Add-ons compatible with the now broken platform of Mozilla again.
