### ISSUE TITLE
Can't Remove/Hide Current Folder Toolbar

### ISSUE THREAD

**Issue by nischwartz** [RealRaven2000/QuickFolders#61]
When opening a message in a new window the current folder toolbar is always present.  The options in the advanced tab of the options menu is unselected for "Display the Toolbar" as well as both submenu options.  If I have an email window open, then select the "...also in Single Message windows" option, then unselect it, the toolbar will be hidden, BUT it will re-appear when the next email window is opened.

I've also gone into the config editor and reset the related settings which made no impact on the issue.

Windows 10, Version 2004
TB 78.2.2, 64-bit
QuickFolders 5.0pre87

**Comment by RealRaven2000** [comment]
I think the settings are not stored in the correct branch, can you set
extensions.quickfolders.showCurrentFolderToolbar = false
in about:config and then restart?We need to sort the preferences system, almost everything is currently stored in the wrong location.

**Comment by nischwartz** [comment]
Thanks for the quick reply - It was set to false, so I set it to true, restarted, then false and restarted, but it's still persisting.

**Comment by RealRaven2000** [comment]
> 
> 
> Thanks for the quick reply - It was set to false, so I set it to true, restarted, then false and restarted, but it's still persisting.

Ok, why didn't you leave it at true? the shortcuts should work then

**Comment by nischwartz** [comment]
Tried a bunch of things with this and can't get it to match the settings.  Still always shows the toolbar when opening an email, regardless of the settings. I'll note that this function works properly for the main window's message pane, but NOT if you open the email in a new window.  Hope that makes sense...

**Comment by RealRaven2000** [comment]
the point is that settings in the settings window are currently foobared (broken). As soon as you open settings you probably mess with stuff that isn't stored in the correct location due to Thunderbird messing up the preferences system.

If you try to set extensions.quickfolders.showCurrentFolderToolbar = false and then wait after restart (DO NOT OPEN QF SETTINGS!) the toolbar will disappear after a few seconds you just gotta select one or two emails.

**Comment by nischwartz** [comment]
Note sure if I'm doing it as you are stating, but I can't get it to hide, regardless of setting, config editor nor preferences for QuickFolders.  I can live with it, but the setting that seems not to effecting when opening the email in a new window.  I see the other options (preview pane and new tab) changing as the settings are changed.

**Comment by RealRaven2000** [comment]
ok, here is a new release, which irons some major problems with the settings dialog, but I am still not sure about that close button (it works for me)

https://github.com/RealRaven2000/QuickFolders/releases/tag/5.0pre90

**Comment by nischwartz** [comment]
Did the testing and the issue is still persistent.  The close button on the toolbar is also not effective for me.  The only way to get it to hide, which is temporary, is to open the QF settings and then uncheck the sub-option for new windows (or check and uncheck).  It immediately works in the open window, but it comes back when opening the next email.  Thanks for working on this!

**Comment by RealRaven2000** [comment]
> 
> 
> Did the testing and the issue is still persistent. The close button on the toolbar is also not effective for me. The only way to get it to hide, which is temporary, is to open the QF settings and then uncheck the sub-option for new windows (or check and uncheck). It immediately works in the open window, but it comes back when opening the next email. Thanks for working on this!

" it comes back when opening the next email" - do you mean opening the email in a separate window?

You must be talking about the single message window (which I never use for looking at mails)?? You probably do not want the toolbar to show up there are all...

**Comment by nischwartz** [comment]
Yes!  I open emails in their own window and there is an option to hide it there, but it's not sticking.  There seem to be two settings - one in the QF Options (the second sub-option under "Display the Toolbar" and in the congif editor (extensions.quickfolders.showCurrentFolderToolbar.messageWindow).  I've got them both set to off/false and it's still showing.

FYI - The open in the main window and new tab settings seem to be working fine.

**Comment by RealRaven2000** [comment]
> 
> 
> Yes! I open emails in their own window and there is an option to hide it there, but it's not sticking. There seem to be two settings - one in the QF Options (the second sub-option under "Display the Toolbar" and in the congif editor (extensions.quickfolders.showCurrentFolderToolbar.messageWindow). I've got them both set to off/false and it's still showing.
> 
> FYI - The open in the main window and new tab settings seem to be working fine.

ok - @opto can you have a look? it seems the Windowlistener variable is not correctly configured (?)
this happens (only) in a single message window within the function

`QuickFolders.Util.loadPlatformStylesheet`

it throws

`QuickFolders_globalWin.QuickFolders.WL.injectCSS is not a function`

**Comment by nischwartz** [comment]
Just installed 5.0pre92 and this is fixed.  Thank you so much!

**Comment by RealRaven2000** [comment]
For other users, here is the fixed version:

https://github.com/RealRaven2000/QuickFolders/releases/tag/5.0pre92

**Comment by nischwartz** [comment]
I got the notification for the update and it's fixed the issue.  Thank you
so much.

**Comment by nischwartz** [comment]
Quick follow up on this and it's a minor one at best - When opening multiple email windows at once (select several emails and press enter to open all at once), the most recent email will still display the current folder toolbar.  Note that the rest of the emails will display properly.
