### ISSUE TITLE
QuickJump list is confusing if folders have same name

### ISSUE THREAD

**Issue by ziomau10** [RealRaven2000/QuickFolders#62]
I have several years of archived folders that share the very same structure as the live folders.
When I press Shift-J followed by few letters of the destination folder a list with all the folders appears without letting me detect which folder is the desired one (see photo).
The option to filter out some folder from QuickJump is not good for me since everynow and then I need to move/Jump to those other folders as well.
I just need a way to tell the difference between folders with the same name.
As a suggestion, the nostalgy addon shows the complete path instead (see photo). I can use that, but it is not going to work with TB 7x and the maintainer seems not 
able to keep up.
Is it possible to show the path in QF?
Thanks in advance.
Regards.
Mau.
![QuickFolders](https://user-images.githubusercontent.com/1978719/93678487-617ba200-faad-11ea-9ab5-5923411ad1eb.jpg)
![Nostalgy](https://user-images.githubusercontent.com/1978719/93678544-66d8ec80-faad-11ea-9896-fdcb293fdea4.jpg)

**Comment by RealRaven2000** [comment]
Your screenshot is certainly confusing. It seems like you also have the same parent folder (Altri) and grandparent (Fornitori) - why is this? That would confuse the heck out of me, too...

but you asked:

> Is it possible to show the path in QF?

yes - on the QuickFolders Pro tab, you can choose between five different options:

![image](https://user-images.githubusercontent.com/6314674/93687601-bcfe5d80-fab6-11ea-8e38-b05fb88255ce.png)

**Comment by ziomau10** [comment]
Sorry, if I was not so clear ...
Actually the "real" problem lies in the option "**Maximum Path Depth**" that limited to 3 the path visualization.
If you use the "yearly archive" with "keep structure" option in TB, you always end up with a structure that is like:
Local Folders/Archives/<year>/<normal folder structure>

That adds up another two folders to the path preventing QF to show them properly with the default options of 3.
I simply pumped up the "**Maximum Path Depth**" to 10 and this allows QF to show the full path.
I didn't notice that option.
Thank you very much ...
Regards.
