### ISSUE TITLE
Order of listing matching folders in dropdown folder selection list

### ISSUE THREAD

**Issue by MichaelJFischer** [RealRaven2000/QuickFolders#63]
When I type shift-M to move messages to a folder and begin typing the folder name, I of course get a list of partial matches.  Because I keep each year's file tree in a separate root folder, I get several matches in the drop-down menu that appears.  I'd like the displayed folders to appear in the order of most recently used first.  The screenshot below shows what I see when I move a message to "quickfolder".  You'll see that I have six different folders that all match the pattern "quickfolder":

![QF_dropdown_menu-1](https://user-images.githubusercontent.com/46387272/95793972-cee9af80-0cb4-11eb-91cc-6f36a2b01ccc.png)

I would like to see the results in the order:
    Ohia mail - personal » l-q » qickfolders-quickfilters
    Ohia mail - ZZ_Last_year » personal » l-q » quickfolders-quickfilters
    Mail archive - old_2018 » personal » l-q » quickfolders-quickfilters
    Mail archive - old_2017 » personal » l-q » quickfolders-quickfilters
    Mail archive - old_2014 » personal » l-q » quickfolders-quickfilters
    Mail archive - old_2012 » personal » l-q » quickfolders-quickfilters

I'm not sure whether the order should be based on file access time, file modification time, or perhaps a timestamp that Thunderbird keeps in its caches.  The common use case is that when I file a second message in the same folder, I want the folder that I selected the first time to appear on top.  (Alternatively, of course, if I know I want the same folder, I can go to "Recent Folders", but I don't always remember to do that.)

**Comment by RealRaven2000** [comment]
please add your comments at #82 one suggestion was sorting all matches strictly by alphabet. let's discuss there
