### ISSUE TITLE
Subfolder menus do not expand 

### ISSUE THREAD

**Issue by Ludifex** [RealRaven2000/QuickFolders#65]
Subfolders (2nd and higher level) do not expand when mail is dragged over main Folder

**Comment by RealRaven2000** [comment]
This sounds like an old bug - which version of QuickFolders, on which version of Thunderbird?

See: https://github.com/RealRaven2000/QuickFolders/issues/55
latest prerelease: 
https://github.com/RealRaven2000/QuickFolders/releases/tag/5.0pre100

Latest news on Thunderbird 78 compatibility:
issue #8

**Comment by RealRaven2000** [comment]
fixed in 5.0 released 17/11/2020
