### ISSUE TITLE
Recent Folders Tab - Delayed Refresh 

### ISSUE THREAD

**Issue by Petermelli** [RealRaven2000/QuickFolders#66]
The recent folder Tab is a very useful feature. It's so useful to move in a folder a message just answered and it's answer as well as other related messages.

Unfortunately, if you try to move a message in a folder just used to store a message (that is you move a message to a folder using the folder tree) and you want to use THIS folder as destination for the following messages without browsing the folder tree, you can't find the LAST destination in the Recent Folder Tab. 

To find it, you must Manually Refresh the Visible Tabs using the appropriate item in the "service menu". 

I just installed 5.0pre116 but the issue was not fixed

**Comment by RealRaven2000** [comment]
Thanks for flagging this. Every folder has a timestamp, which Thunderbird itself updates, I also force these timestamp updates when you use the "quickMove" command or when you drag an email  to another Folder via a QuickFolders Tab. I will look into whether it is possible to also catch the event when you drag straight to the tree. If you have many folders I highly recommend not using the tree at all as it will save you time - once you need scrolling the tree, drag and drop becomes painful.

**Comment by RealRaven2000** [comment]
see also new  #80 
finally fixed in 5.1 released 10/Dec/2020
