### ISSUE TITLE
XML Parsing Error on Category Picker Launch

### ISSUE THREAD

**Issue by crablouis** [RealRaven2000/QuickFolders#68]
Quick Folders Commands > Set Tab Category
Triggers error window instead of category picker. 
See attached PNG
![Screenshot_2020-11-03_152148](https://user-images.githubusercontent.com/73916062/98051517-e7974200-1de8-11eb-924c-c3a815d0a1e7.png)

(btw, my first GitHub submission. Sorry if I blew it...)

**Comment by RealRaven2000** [comment]
There is a fix available - I had it fixed a few days ago but forgot to upload (spending too much time with support mail, LOL):

https://github.com/RealRaven2000/QuickFolders/releases/tag/5.0pre119

**Comment by crablouis** [comment]
Category picker now appears. No more rude dialog. Thanks!

Strangely though, I noticed before installing the fix, TBird Tabs (not QuickFolders tabs) were no longer staying open between TBird sessions. I'd use "Open in New Tab" from the Folder Pane, and the folder tab would only stay open for the current TBird session. Now they stay open from session to session, after installing QuickFolders-wx-5.0pre119.xpi

**Comment by RealRaven2000** [comment]
fixed in 5.0 released 17/11/2020
