### ISSUE TITLE
QuickMove: easily enable silent mode / disable notification

### ISSUE THREAD

**Issue by fluegelrad** [RealRaven2000/QuickFolders#74]
Great work, Axel! I was _really_ greatful to find QuickFolders' return after today's reboot.
Concerning QuickMove: Can you pls include an easy option in the settings to disable notifications  #appearing once one has moved/copied a message (see pic)? 

I guess I've already found the solution in the config editor:
_extensions.quickfolders.quickMove.premium.silentMode -->true_

But, as these popups really grind my gears, I guess there might be folks out there who feel the same and who'd like a shortcut.
Cheers!

![grafik](https://user-images.githubusercontent.com/44899934/99723048-eb49ea80-2ab1-11eb-9501-2050cd8fd863.png)

**Comment by RealRaven2000** [comment]
> Great work, Axel! I was _really_ greatful to find QuickFolders' return after today's reboot.
> Concerning QuickMove: Can you pls include an easy option in the settings to disable notifications #appearing once one has moved/copied a message (see pic)?
> 
> I guess I've already found the solution in the config editor:
> _extensions.quickfolders.quickMove.premium.silentMode -->true_
> 
> But, as these popups really grind my gears, I guess there might be folks out there who feel the same and who'd like a shortcut.
> Cheers!
> 

I hear you - there are actually quite a few hidden settings for quickMove, which can be accessed through a right-click on the quickMove icon here:

![image](https://user-images.githubusercontent.com/6314674/99730467-69a78c00-2ab4-11eb-99f8-85db36dbdd1c.png)

I didn't want to have too many options in the UI as there is already an overwhelming amount of them in the dialog, so I decided to add some hidden settings through this sneaky "right-click" way. You find another one on the general settings, behind the recent folders icon:

![image](https://user-images.githubusercontent.com/6314674/99730574-965ba380-2ab4-11eb-9110-fde82f7772bb.png)

I realize that a dialog that exposes relevant config settings isn't exactly 'minimal UI' but at least a quick way for me to add more configurability for advanced users without all the visual clutter.

**Comment by RealRaven2000** [comment]
Implemented in 5.4 - Released 18/03/2021
