### ISSUE TITLE
[Recent folders]: outdated display of unread mails

### ISSUE THREAD

**Issue by macdeport** [RealRaven2000/QuickFolders#78]
![thunderbird-display--201125](https://user-images.githubusercontent.com/26068595/100210477-53159080-2f0b-11eb-9926-541208819e2b.jpg)
![quickfolders-display--201125](https://user-images.githubusercontent.com/26068595/100210501-5a3c9e80-2f0b-11eb-91f6-ca1fe2e66f26.jpg)
Best, Alain L.

**Comment by macdeport** [comment]
Fixed apparently by the recent 5.1 update. Thanks Axel.

**Comment by macdeport** [comment]
Although fortunately this bug is solved the highlighting (visibility) of a change (new mails) is less than in the Tb 68 version :-( Things are maybe difficult with the new API.

**Comment by RealRaven2000** [comment]
can you be more specific? maybe open a new github issue for this one and  i see what i can  do.
generally: 
* folders with unread mails are shown in bold
* email that arrives during the session additional gets the "gold star" icon - I made my own version

**Comment by RealRaven2000** [comment]
fixed in 5.1 released on 10/Dec/2020

**Comment by RealRaven2000** [comment]
> Although fortunately this bug is solved the highlighting (visibility) of a change (new mails) is less than in the Tb 68 version :-( Things are maybe difficult with the new API.

I can make some maintenance adjustments with 4.18.2 - just releasing is tricky as it will "hide" the 5.* versions until I upload a new version for Tb78 straight after. Not easy to manage as the ATN frontend is owned by Firefox who has no interest in writing patches for legacy users.

**Comment by macdeport** [comment]
Thank you Axel for the good care of your software users.

Don't worry, it's now OK for me, thanks to your recommendations concerning the themes:

My current choice: "Bling My Tabs!" / Themes: Flat Style / Individual Tab Color Appearance [Mozilla] (filled style)

But while trying to (re)find the right theme in 5.1 I found out that:
● the update had overwritten the previous choice
● the simple browsing of the themes also overwrites the previous adjustments leading to some jam of themes (!)
Maybe some refinements to come...

You've already explained how to save / reload your JSON configuration : that's what I've lately done now ;-)
