### ISSUE TITLE
Thunderbird 84.0b2 (64-bit) - 2 instances used, one it dos not work!

### ISSUE THREAD

**Issue by GitHubbet** [RealRaven2000/QuickFolders#83]
Hi
I am not a developer, but I have 2 instances of 84.0b2 (64-bit) [the same installation], one Quick Folders works and other does not = weird!

Any help?

Thanks

**Comment by RealRaven2000** [comment]
I haven't tested with the new betas, we are still struggling with the changes in Thunderbird 78.* - most of the focus is on keeping the current ESR functional, and I really cannot guarantee (and test) with the latest betas. Thanks for you understanding!

**Comment by GitHubbet** [comment]
Of course I understand.

It is just weird!

I attached image - not sure it picked it up.

**Comment by GitHubbet** [comment]
I will leave you in peace now.
;p]

**Comment by GitHubbet** [comment]
Went back to last 68v and all works now1

**Comment by RealRaven2000** [comment]
> Went back to last 68v and all works now1

No need to go back to last years version - the official current version is 78.5.1 and QuickFolders will support this until end of next year when v88 will be released - there will be a lot of additional coding necessary but we will pass that bridge too!

**Comment by RealRaven2000** [comment]
I released v 5.3 today - Thunderbird  86.0beta1 and later will be handled in issue #114 going forward
