### ISSUE TITLE
orphaned tabs don't accept emails

### ISSUE THREAD

**Issue by trjwaugh** [RealRaven2000/QuickFolders#85]
A staff that uses QuickFolders religiously came to me with this issue today. "none of my quick folders are working......they have little brooms on them and when I attempt to drop emails into them they say something about trying "orphaned tabs". She sent me a screenshot and all of her tabs have little brooms beside them. When she tries to drag a new email into a folder, it says "No Folder for [<name of the folder>] - try the Finding Orphan Tabs command.

Is this the Ctrl + Alt + F command I found in docs? its worded a bit differently, but if not - how do I remedy this? Thanks!

**Comment by RealRaven2000** [comment]
My guess is that the base URL for one of her mail boxes may have changed
Can you export your folders on the (QuickFolders Pro) tab:
![image](https://user-images.githubusercontent.com/6314674/101519332-f8ece480-397a-11eb-8b85-94ee0a1e78cc.png)

You need to look at one single folder and find out the correct URL via folder tree / right-click / properties / location:

![image](https://user-images.githubusercontent.com/6314674/101519404-0c984b00-397b-11eb-8d7a-9c6bdce53cd3.png)

**Comment by RealRaven2000** [comment]
any news on this one?

**Comment by RealRaven2000** [comment]
any news?

**Comment by RealRaven2000** [comment]
the message wirh the empty brackets [ ] seems to indicate some sort of error while reading the folder string.  can you open tools / developer tools / error console and see what happens when you refresh visible tabs from the QuickFolders utility (wheel left of the tabs) menu.

**Comment by RealRaven2000** [comment]
also have a look at #56

**Comment by RealRaven2000** [comment]
no replies from OP, so I am closing this for now. Hope they have the orphaned tabs issue resolved by fixing the folder addresses.
