### ISSUE TITLE
After installation of 5.1 QuickFolders does not show up in Thunderbird 78.5.0 (64-Bit)

### ISSUE THREAD

**Issue by hayosc** [RealRaven2000/QuickFolders#86]
I was using the Beta before and it used to work fine.
After automatic installation of QuickFolders 5.1 the GUI is not showing up anymore.

UPDATE: One hour later I started Firefox again. Now the QuickFolders are appearing. Of course I did restart Firefox twice before I posted the original report. Updated the title with "IMMEDIATELY".
(In between I installed updates of openssl-1_1, libmariadb3-3.1.1, and ucode-intel. I don't think this is related.)

Environment
- Thunderbird 78.5.0 (64-Bit)
- openSUSE Leap 15.2
- KDE

**Comment by hayosc** [comment]
I updated the description, because it works an hour later.

**Comment by RealRaven2000** [comment]
that is indeed very weird. when it wasn't visible did you see:
- a large popup message about the update (that's how i made my investment
back for the conversions)
- any entry in Add-ons options (or was QuickFolders disabled?)
- did you install fresh or update from 5.0 / 4.18...?

>
