### ISSUE TITLE
Improvement: QF advanced properties setting "from identity" : set "Reply-to" address accordingly

### ISSUE THREAD

**Issue by macdeport** [RealRaven2000/QuickFolders#91]
This **unique** default Reply-to address is use by QF with **every** identities even if different:
![thb78-account-default-200945](https://user-images.githubusercontent.com/26068595/103309250-e5cab300-4a14-11eb-8d69-41abec5f9a70.jpg)

I suggest that last part of this answer https://github.com/RealRaven2000/SmartTemplate4/issues/103#issuecomment-751789487 concerning QF will be moved here  (and duplicate in QF web site as a great feature).

**Comment by RealRaven2000** [comment]
> This **unique** default Reply-to address is use by QF with **every** identities:

I see the image, but what exactly happens in Composer? Looks to me like the Reply-To Address is an empty string. Also, is the Default Email Address empty or did you just scrub it from the screenshot for privacy reasons/

**Comment by macdeport** [comment]
> is the Default Email Address empty or did you just scrub it from the screenshot for privacy reasons
Yes so I will send you a private mail with all the things...

Each identity has same Reply-to address than identity, but nevertheless QF set Reply-to address to default one :-(

**Comment by RealRaven2000** [comment]
> > is the Default Email Address empty or did you just scrub it from the screenshot for privacy reasons
> > Yes so I will send you a private mail with all the things...
> 
> Each identity has same Reply-to address than identity, but nevertheless QF set Reply-to address to default one :-(

I think what may be happening is that it is only setting the from address and ignoring the reply-to for now, but that can be changed!

**Comment by RealRaven2000** [comment]
Here we go:

[QuickFolders-wx-5.2pre8.zip](https://github.com/RealRaven2000/QuickFolders/files/5754965/QuickFolders-wx-5.2pre8.zip)

I changed the code for modifying the "from" identity. instead of dispatching a new `compose-from-changed` event I am calling the internal function `LoadIdentity(false)` just like it would happen if the user selected an entry from the "from" drop-down. I think this triggers all the necessary events for changing the "reply-to" according to what is configured in account settings.

**Comment by macdeport** [comment]
Improvement _quite_ done: quite because in case of **reply** `from`

**Comment by RealRaven2000** [comment]
> * Of course very good choice to simulate drag and drop, as others plugins continue naturally there jobs, if I understand well API programming +1

Except it was not drag and drop. Just simply what happens what you open the drop down menu and **click** an identity in the "from" popup:

![image](https://user-images.githubusercontent.com/6314674/103388781-e3df1d80-4b02-11eb-8930-83854664a85e.png)

**Comment by macdeport** [comment]
Thanks to clarify for better sharing of the internal game.

**Comment by macdeport** [comment]
> Just simply what happens what you open the drop down menu and click an identity in the "from" popup

But I experience a weird side effect of this good stuff (like what often happens in life)...

As I am running **SmartTemplate⁴ Pro** also in background it **trigger unfortunately 2 times**:
1. when I click Reply/Forward
2. when QuickFolders does its job of substitution

The author of both add-ons will for sure arbitrate his "children" interaction ;-)

**Comment by RealRaven2000** [comment]
> > Just simply what happens what you open the drop down menu and click an identity in the "from" popup
> 
> As I am running **SmartTemplate⁴ Pro** also in background it **trigger unfortunately 2 times**:
> 
> 1. when I click Reply/Forward
> 2. when QuickFolders does its job of substitution
> 

can you elaborate what happens from triggering SmartTemplates twice? I would like to make a test case for this.

**Comment by macdeport** [comment]
When [QuickFolders-5.2pre8](https://github.com/RealRaven2000/QuickFolders/files/5754965/QuickFolders-wx-5.2pre8.zip) (2020) forces explicitly `from` the **result of SmartTemplate⁴** processing template **is duplicated** :-(

**Comment by RealRaven2000** [comment]
> When [QuickFolders-5.2pre8](https://github.com/RealRaven2000/QuickFolders/files/5754965/QuickFolders-wx-5.2pre8.zip) (2020) forces explicitly `from` the **result of SmartTemplate⁴** processing template **is duplicated** :-(
> So to build a test case you need for example:
> 
> * a QuickFolders with advanced properties setting "from identity" for the tested tag
> * a  SmartTemplate⁴ template for _forward mode_
> * a quite arbitrary mail you forward
> 
So this may be by design, there are 2 things that trigger SmartTemplates.

1) When the composer is opened, the event "NotifyCOmposeBodyReady" happens - the template associated with the account is applied.
2) When a different identity is selected (but the user has not started editing the email) - SmartTemplates removes all parts of the mail (except for the quoted / forwarded stuff) and then injects the template of the appropriate account. But: it should _remove_ the old template first. That's actually technically sometimes not 100% possible, so it really depends on your complete SmartTemplates setup. I would expect this is really a SmartTemplates bug.

Are the templates different for the different identities (you can have different ones)?. And what's their content (they can be exported for each account with this button):

![image](https://user-images.githubusercontent.com/6314674/103439043-6f56cc80-4c31-11eb-9a54-cff6f5c87d5c.png)

If you have checked [x] use common, you need to export the common template as well.

**Comment by RealRaven2000** [comment]
Testing this, so far I have found: In smartTemplate-main.js I am setting a global attribute  `smartTemplateInserted="true"` in the <body> Element which can be used to guard again duplicated templates, but the additional Load event does not mark the fact that the template was inserted. The plot thickens

![image](https://user-images.githubusercontent.com/6314674/103439787-e7c08c00-4c37-11eb-93ef-c6055f94155a.png)

There is a separate call to `insertTemplate()` elsewhere, I have raised [this new issue](https://github.com/RealRaven2000/SmartTemplate4/issues/108)  to fix the duplication problem in SmartTemplates

**Comment by RealRaven2000** [comment]
> There is a separate call to `insertTemplate()` elsewhere, I have raised [this new issue](https://github.com/RealRaven2000/SmartTemplate4/issues/108) to fix the duplication problem in SmartTemplates

I posted a version with a fix [there](https://github.com/RealRaven2000/SmartTemplate4/issues/108).

I also raised a new issue, because the positioning of the advanced properties tab is faulty. See #94

**Comment by macdeport** [comment]
quickFolders-5.3pre44:
in the case of a reply to an email whose sender is himself the value of "From:" remains the default account regardless of the setting of folder with "Tab-specific Properties" :-(

**Comment by macdeport** [comment]
QuickFolders-5.3:

In the case of a reply to an email whose sender use Last name First name reverse of setting of folder with "Tab-specific Properties" the sender choice is used (?)

No such behavior in forward of an email.

**Comment by RealRaven2000** [comment]
> QuickFolders-5.3:
> 
> In the case of a reply to an email whose sender use Last name First name reverse of setting of folder with "Tab-specific Properties" the sender choice is used (?)
> 

I don't understand "the sender choice is used", can you add more detail? Maybe an example...  I think the "last name first name " correction is used when the name portion of an email contains a "comma", such as `"smyth, gerry" <gsmith@abc.com>`

- What is set in your tab-specific properties, a selected "from identity" for yourself or does it overwrite the "To: address"?
- What would you expect exactly. If you say it behaves a certain way, how should it behave differently?

**Comment by macdeport** [comment]
I have send you a private mail to avoid conflict between clarity and privacy. Thanks.

**Comment by RealRaven2000** [comment]
Implemented in 5.2 on 22/01/2021
